---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Returns the number of degrees difference between two yaw angles
---@param float_1 number
---@param float_2 number
---@return number
function AngleDiff(float_1, float_2) end

---Generate a vector given a QAngles
---@param QAngle_1 QAngle
---@return Vector
function AnglesToVector(QAngle_1) end

---AppendToLogFile is deprecated. Print to the console for logging instead.
---@param string_1 string
---@param string_2 string
function AppendToLogFile(string_1, string_2) end

---(vector,float) constructs a quaternion representing a rotation by angle around the specified vector axis
---@param Vector_1 Vector
---@param float_2 number
---@return Quaternion
function AxisAngleToQuaternion(Vector_1, float_2) end

---Compute the closest point on the OBB of an entity.
---@param handle_1 handle
---@param Vector_2 Vector
---@return Vector
function CalcClosestPointOnEntityOBB(handle_1, Vector_2) end

---Compute the distance between two entity OBB. A negative return value indicates an input error. A return value of zero indicates that the OBBs are overlapping.
---@param handle_1 handle
---@param handle_2 handle
---@return number
function CalcDistanceBetweenEntityOBB(handle_1, handle_2) end

---@param Vector_1 Vector
---@param Vector_2 Vector
---@param Vector_3 Vector
---@return number
function CalcDistanceToLineSegment2D(Vector_1, Vector_2, Vector_3) end

---Create all I/O events for a particular entity
---@param ehandle_1 handle
function CancelEntityIOEvents(ehandle_1) end

---Pass table - Inputs: entity, effect
---@param handle_1 handle
---@return boolean
function CreateEffect(handle_1) end

---Create an HTTP request.
---@param string_1 string
---@param string_2 string
---@return handle
function CreateHTTPRequest(string_1, string_2) end

---Create an HTTP request.
---@param string_1 string
---@param string_2 string
---@return handle
function CreateHTTPRequestScriptVM(string_1, string_2) end

---( iSeed ) - Creates a separate random number stream.
---@param int_1 integer
---@return handle
function CreateUniformRandomStream(int_1) end

---(vector,vector) cross product between two vectors
---@param Vector_1 Vector
---@param Vector_2 Vector
---@return Vector
function CrossVectors(Vector_1, Vector_2) end

---Breaks in the debugger
function DebugBreak() end

---Draw a debug overlay box (origin, mins, maxs, forward, r, g, b, a, duration )
---@param unknown_1 any
---@param Vector_2 Vector
---@param Vector_3 Vector
---@param int_4 integer
---@param int_5 integer
---@param int_6 integer
---@param int_7 integer
---@param float_8 number
function DebugDrawBox(unknown_1, Vector_2, Vector_3, int_4, int_5, int_6, int_7, float_8) end

---Draw a debug forward box (cent, min, max, forward, vRgb, a, duration)
---@param unknown_1 any
---@param Vector_2 Vector
---@param Vector_3 Vector
---@param Vector_4 Vector
---@param Vector_5 Vector
---@param float_6 number
---@param float_7 number
function DebugDrawBoxDirection(unknown_1, Vector_2, Vector_3, Vector_4, Vector_5, float_6, float_7) end

---Draw a debug circle (center, vRgb, a, rad, ztest, duration)
---@param unknown_1 any
---@param Vector_2 Vector
---@param float_3 number
---@param float_4 number
---@param bool_5 boolean
---@param float_6 number
function DebugDrawCircle(unknown_1, Vector_2, float_3, float_4, bool_5, float_6) end

---Try to clear all the debug overlay info
function DebugDrawClear() end

---Draw a debug overlay line (origin, target, r, g, b, ztest, duration)
---@param unknown_1 any
---@param unknown_2 any
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
---@param bool_6 boolean
---@param float_7 number
function DebugDrawLine(unknown_1, unknown_2, int_3, int_4, int_5, bool_6, float_7) end

---Draw a debug line using color vec (start, end, vRgb, a, ztest, duration)
---@param unknown_1 any
---@param unknown_2 any
---@param Vector_3 Vector
---@param bool_4 boolean
---@param float_5 number
function DebugDrawLine_vCol(unknown_1, unknown_2, Vector_3, bool_4, float_5) end

---Draw text with a line offset (x, y, lineOffset, text, r, g, b, a, duration)
---@param float_1 number
---@param float_2 number
---@param int_3 integer
---@param string_4 string
---@param int_5 integer
---@param int_6 integer
---@param int_7 integer
---@param int_8 integer
---@param float_9 number
function DebugDrawScreenTextLine(float_1, float_2, int_3, string_4, int_5, int_6, int_7, int_8, float_9) end

---Draw a debug sphere (center, vRgb, a, rad, ztest, duration)
---@param unknown_1 any
---@param Vector_2 Vector
---@param float_3 number
---@param float_4 number
---@param bool_5 boolean
---@param float_6 number
function DebugDrawSphere(unknown_1, Vector_2, float_3, float_4, bool_5, float_6) end

---Draw text in 3d (origin, text, bViewCheck, duration)
---@param unknown_1 any
---@param string_2 string
---@param bool_3 boolean
---@param float_4 number
function DebugDrawText(unknown_1, string_2, bool_3, float_4) end

---Draw pretty debug text (x, y, lineOffset, text, r, g, b, a, duration, font, size, bBold)
---@param float_1 number
---@param float_2 number
---@param int_3 integer
---@param string_4 string
---@param int_5 integer
---@param int_6 integer
---@param int_7 integer
---@param int_8 integer
---@param float_9 number
---@param string_10 string
---@param int_11 integer
---@param bool_12 boolean
function DebugScreenTextPretty(float_1, float_2, int_3, string_4, int_5, int_6, int_7, int_8, float_9, string_10, int_11, bool_12) end

---Execute a script (internal)
---@param string_1 string
---@param handle_2 handle
---@return boolean
function DoIncludeScript(string_1, handle_2) end

---#ScriptAssert:Asserts the passed in value. Prints out a message and brings up the assert dialog.
---@param bool_1 boolean
---@param string_2 string
function DoScriptAssert(bool_1, string_2) end

---#UniqueString:Generate a string guaranteed to be unique across the life of the script VM, with an optional root string. Useful for adding data to tables when not sure what keys are already in use in that table.
---@param string_1 string
---@return string
function DoUniqueString(string_1) end

---Play named sound on Entity
---@param string_1 string
---@param handle_2 handle
function EmitSoundOn(string_1, handle_2) end

---Play named sound only on the client for the passed in player
---@param string_1 string
---@param handle_2 handle
function EmitSoundOnClient(string_1, handle_2) end

---Turn an entity index integer to an HScript representing that entity's script instance.
---@param int_1 integer
---@return handle
function EntIndexToHScript(int_1) end

---Smooth curve decreasing slower as it approaches zero
---@param float_1 number
---@param float_2 number
---@param float_3 number
---@return number
function ExponentialDecay(float_1, float_2, float_3) end

---Fire Entity's Action Input w/no data
---@param ehandle_1 handle
---@param string_2 string
function FireEntityIOInputNameOnly(ehandle_1, string_2) end

---Fire Entity's Action Input with passed String - you own the memory
---@param ehandle_1 handle
---@param string_2 string
---@param string_3 string
function FireEntityIOInputString(ehandle_1, string_2, string_3) end

---Fire Entity's Action Input with passed Vector - you own the memory
---@param ehandle_1 handle
---@param string_2 string
---@param Vector_3 Vector
function FireEntityIOInputVec(ehandle_1, string_2, Vector_3) end

---Fire a game event.
---@param string_1 string
---@param handle_2 handle
function FireGameEvent(string_1, handle_2) end

---Fire a game event without broadcasting to the client.
---@param string_1 string
---@param handle_2 handle
function FireGameEventLocal(string_1, handle_2) end

---Get the time spent on the server in the last frame
---@return number
function FrameTime() end

---Get ability data by ability name.
---@param string_1 string
---@return table
function GetAbilityKeyValuesByName(string_1) end

---Gets the ability texture name for an ability
---@param string_1 string
---@return string
function GetAbilityTextureNameForAbility(string_1) end

---Returns the currently active spawn group handle
---@return integer
function GetActiveSpawnGroupHandle() end

---Returns the engines current frame count
---@return integer
function GetFrameCount() end

---Get the local player on a listen server.
---@return handle
function GetListenServerHost() end

---Get the name of the map.
---@return string
function GetMapName() end

---Get the longest delay for all events attached to an output
---@param ehandle_1 handle
---@param string_2 string
---@return number
function GetMaxOutputDelay(ehandle_1, string_2) end

---Get Angular Velocity for VPHYS or normal object. Returns a vector of the axis of rotation, multiplied by the degrees of rotation per second.
---@param handle_1 handle
---@return Vector
function GetPhysAngularVelocity(handle_1) end

---Get Velocity for VPHYS or normal object
---@param handle_1 handle
---@return Vector
function GetPhysVelocity(handle_1) end

---Get unit data by ability name.
---@param string_1 string
---@return table
function GetUnitKeyValuesByName(string_1) end

---InitLogFile is deprecated. Print to the console for logging instead.
---@param string_1 string
---@param string_2 string
function InitLogFile(string_1, string_2) end

---Returns true if this is lua running from the client.dll.
---@return boolean
function IsClient() end

---Returns true if this server is a dedicated server.
---@return boolean
function IsDedicatedServer() end

---Returns true if this is lua running within tools mode.
---@return boolean
function IsInToolsMode() end

---Returns true if the entity is valid and marked for deletion.
---@param handle_1 handle
---@return boolean
function IsMarkedForDeletion(handle_1) end

---Returns true if this is lua running from the server.dll.
---@return boolean
function IsServer() end

---Checks to see if the given hScript is a valid entity
---@param handle_1 handle
---@return boolean
function IsValidEntity(handle_1) end

---(vector,vector,float) lerp between two vectors by a float factor returning new vector
---@param Vector_1 Vector
---@param Vector_2 Vector
---@param float_3 number
---@return Vector
function LerpVectors(Vector_1, Vector_2, float_3) end

---Link a lua-defined modifier with the associated class ( className, fileName, LuaModifierType).
---@param string_1 string
---@param string_2 string
---@param int_3 integer
function LinkLuaModifier(string_1, string_2, int_3) end

---Register as a listener for a game event from script.
---@param string_1 string
---@param handle_2 handle
---@param handle_3 handle
---@return integer
function ListenToGameEvent(string_1, handle_2, handle_3) end

---Creates a table from the specified keyvalues text file
---@param string_1 string
---@return table
function LoadKeyValues(string_1) end

---Creates a table from the specified keyvalues string
---@param string_1 string
---@return table
function LoadKeyValuesFromString(string_1) end

---Get the current local time
---@return table
function LocalTime() end

---Checks to see if the given hScript is a valid entity
---@param string_1 string
---@return integer
function MakeStringToken(string_1) end

---Triggers the creation of entities in a manually-completed spawn group
---@param int_1 integer
function ManuallyTriggerSpawnGroupCompletion(int_1) end

---Print a message
---@param string_1 string
function Msg(string_1) end

---Get the current float time from the engine
---@return number
function Plat_FloatTime() end

---Get a script instance of a player by index.
---@param int_1 integer
---@return handle
function PlayerInstanceFromIndex(int_1) end

---Precache an entity from KeyValues in table
---@param string_1 string
---@param handle_2 handle
---@param handle_3 handle
function PrecacheEntityFromTable(string_1, handle_2, handle_3) end

---Precache a list of entity KeyValues tables
---@param handle_1 handle
---@param handle_2 handle
function PrecacheEntityListFromTable(handle_1, handle_2) end

---Print a console message with a linked console command
---@param string_1 string
---@param string_2 string
function PrintLinkedConsoleMessage(string_1, string_2) end

---(from angle, to angle, time) - Spherical lerp of angle from->to based on time
---@param QAngle_1 QAngle
---@param QAngle_2 QAngle
---@param float_3 number
---@return QAngle
function QSlerp(QAngle_1, QAngle_2, float_3) end

---Generate a random floating point number within a range, inclusive
---@param float_1 number
---@param float_2 number
---@return number
function RandomFloatWrapper(float_1, float_2) end

---Get a random int within a range
---@param int_1 integer
---@param int_2 integer
---@return integer
function RandomInt(int_1, int_2) end

---Create a C proxy for a script-based spawn group filter
---@param string_1 string
function RegisterSpawnGroupFilterProxy(string_1) end

---Reloads the MotD file
function ReloadMOTD() end

---Remove the C proxy for a script-based spawn group filter
---@param string_1 string
function RemoveSpawnGroupFilterProxy(string_1) end

---Rotate a QAngle by another QAngle.
---@param QAngle_1 QAngle
---@param QAngle_2 QAngle
---@return QAngle
function RotateOrientation(QAngle_1, QAngle_2) end

---Rotate a Vector around a point.
---@param unknown_1 any
---@param QAngle_2 QAngle
---@param unknown_3 any
---@return any
function RotatePosition(unknown_1, QAngle_2, unknown_3) end

---(quaternion,vector,float) rotates a quaternion by the specified angle around the specified vector axis
---@param Quaternion_1 Quaternion
---@param Vector_2 Vector
---@param float_3 number
---@return Quaternion
function RotateQuaternionByAxisAngle(Quaternion_1, Vector_2, float_3) end

---Find the delta between two QAngles.
---@param QAngle_1 QAngle
---@param QAngle_2 QAngle
---@return QAngle
function RotationDelta(QAngle_1, QAngle_2) end

---converts delta QAngle to an angular velocity Vector
---@param QAngle_1 QAngle
---@param QAngle_2 QAngle
---@return Vector
function RotationDeltaAsAngularVelocity(QAngle_1, QAngle_2) end

---Start a screenshake with the following parameters. vecCenter, flAmplitude, flFrequency, flDuration, flRadius, eCommand( SHAKE_START = 0, SHAKE_STOP = 1 ), bAirShake
---@param unknown_1 any
---@param float_2 number
---@param float_3 number
---@param float_4 number
---@param float_5 number
---@param int_6 integer
---@param bool_7 boolean
function ScreenShake(unknown_1, float_2, float_3, float_4, float_5, int_6, bool_7) end

---Get a random float within a range
---@param float_1 number
---@param float_2 number
---@return number
function Script_RandomFloat(float_1, float_2) end

---Send a string to the console as a client command
---@param string_1 string
function SendToConsole(string_1) end

---Sets an opvar value for all players
---@param string_1 string
---@param string_2 string
---@param string_3 string
---@param float_4 number
function SetOpvarFloatAll(string_1, string_2, string_3, float_4) end

---Sets an opvar value for a single player
---@param string_1 string
---@param string_2 string
---@param string_3 string
---@param float_4 number
---@param handle_5 handle
function SetOpvarFloatPlayer(string_1, string_2, string_3, float_4, handle_5) end

---Set Angular Velocity for VPHYS or normal object, from a vector of the axis of rotation, multiplied by the degrees of rotation per second.
---@param handle_1 handle
---@param Vector_2 Vector
function SetPhysAngularVelocity(handle_1, Vector_2) end

---Set the current quest name.
---@param string_1 string
function SetQuestName(string_1) end

---Set the current quest phase.
---@param int_1 integer
function SetQuestPhase(int_1) end

---Set rendering on/off for an ehandle
---@param ehandle_1 handle
---@param bool_2 boolean
function SetRenderingEnabled(ehandle_1, bool_2) end

---Asynchronously spawns a single entity from a table
---@param string_1 string
---@param handle_2 handle
---@param handle_3 handle
---@param handle_4 handle
function SpawnEntityFromTableAsynchronous(string_1, handle_2, handle_3, handle_4) end

---Synchronously spawns a single entity from a table
---@param string_1 string
---@param handle_2 handle
---@return handle
function SpawnEntityFromTableSynchronous(string_1, handle_2) end

---Hierarchically spawn an entity group from a set of spawn tables.
---@param handle_1 handle
---@param bool_2 boolean
---@param handle_3 handle
---@return boolean
function SpawnEntityGroupFromTable(handle_1, bool_2, handle_3) end

---Asynchronously spawn an entity group from a list of spawn tables. A callback will be triggered when the spawning is complete
---@param handle_1 handle
---@param handle_2 handle
---@return integer
function SpawnEntityListFromTableAsynchronous(handle_1, handle_2) end

---Synchronously spawn an entity group from a list of spawn tables.
---@param handle_1 handle
---@return handle
function SpawnEntityListFromTableSynchronous(handle_1) end

---(quaternion,quaternion,float) very basic interpolation of v0 to v1 over t on [0,1]
---@param Quaternion_1 Quaternion
---@param Quaternion_2 Quaternion
---@param float_3 number
---@return Quaternion
function SplineQuaternions(Quaternion_1, Quaternion_2, float_3) end

---(vector,vector,float) very basic interpolation of v0 to v1 over t on [0,1]
---@param Vector_1 Vector
---@param Vector_2 Vector
---@param float_3 number
---@return Vector
function SplineVectors(Vector_1, Vector_2, float_3) end

---Start a sound event
---@param string_1 string
---@param handle_2 handle
function StartSoundEvent(string_1, handle_2) end

---Start a sound event from position
---@param string_1 string
---@param unknown_2 any
function StartSoundEventFromPosition(string_1, unknown_2) end

---Start a sound event from position with reliable delivery
---@param string_1 string
---@param unknown_2 any
function StartSoundEventFromPositionReliable(string_1, unknown_2) end

---Start a sound event from position with optional delivery
---@param string_1 string
---@param unknown_2 any
function StartSoundEventFromPositionUnreliable(string_1, unknown_2) end

---Start a sound event with reliable delivery
---@param string_1 string
---@param handle_2 handle
function StartSoundEventReliable(string_1, handle_2) end

---Start a sound event with optional delivery
---@param string_1 string
---@param handle_2 handle
function StartSoundEventUnreliable(string_1, handle_2) end

---Pass entity and effect name
---@param handle_1 handle
---@param string_2 string
function StopEffect(handle_1, string_2) end

---Stop listening to all game events within a specific context.
---@param handle_1 handle
function StopListeningToAllGameEvents(handle_1) end

---Stop listening to a particular game event.
---@param int_1 integer
---@return boolean
function StopListeningToGameEvent(int_1) end

---Stops a sound event with optional delivery
---@param string_1 string
---@param handle_2 handle
function StopSoundEvent(string_1, handle_2) end

---Stop named sound on Entity
---@param string_1 string
---@param handle_2 handle
function StopSoundOn(string_1, handle_2) end

---Get the current server time
---@return number
function Time() end

---Pass table - Inputs: start, end, ent, (optional mins, maxs) -- outputs: pos, fraction, hit, startsolid, normal
---@param handle_1 handle
---@return boolean
function TraceCollideable(handle_1) end

---Pass table - Inputs: start, end, min, max, mask, ignore  -- outputs: pos, fraction, hit, enthit, startsolid
---@param handle_1 handle
---@return boolean
function TraceHull(handle_1) end

---Pass table - Inputs: startpos, endpos, mask, ignore  -- outputs: pos, fraction, hit, enthit, startsolid
---@param handle_1 handle
---@return boolean
function TraceLine(handle_1) end

---Removes the specified entity
---@param handle_1 handle
function UTIL_Remove(handle_1) end

---Immediately removes the specified entity
---@param handle_1 handle
function UTIL_RemoveImmediate(handle_1) end

---Check if a unit passes a set of filters. (hNPC, nTargetTeam, nTargetType, nTargetFlags, nTeam
---@param handle_1 handle
---@param int_2 integer
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
---@return integer
function UnitFilter(handle_1, int_2, int_3, int_4, int_5) end

---Unload a spawn group by name
---@param string_1 string
function UnloadSpawnGroup(string_1) end

---Unload a spawn group by handle
---@param int_1 integer
function UnloadSpawnGroupByHandle(int_1) end

---Turn a userid integer (typically, fields named 'userid' in game events) to an HScript representing the associated player controller's script instance.
---@param int_1 integer
---@return handle
function UserIDToControllerHScript(int_1) end

---Get Qangles (with no roll) for a Vector.
---@param Vector_1 Vector
---@return QAngle
function VectorToAngles(Vector_1) end

---Print a warning
---@param string_1 string
function Warning(string_1) end

---Gets the value of the given cvar, as a float.
---@param string_1 string
---@return number
function cvar_getf(string_1) end

---Sets the value of the given cvar, as a float.
---@param string_1 string
---@param float_2 number
---@return boolean
function cvar_setf(string_1, float_2) end
