---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@type CCustomNetTableManager
CustomNetTables = nil

---@type CDOTAGameManager
DOTAGameManager = nil

---@type CEntities
Entities = nil

---@type CDOTAGameRules
GameRules = nil

---@type CEntityScriptFramework
NativeFunctions = nil

---@type CScriptParticleManager
ParticleManager = nil

---@type CEntityInstance
c = nil

---@type CDebugOverlayScriptHelper
debugoverlay = nil
