---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Script handle of an engine object; the engine does not name its class.
---@alias handle any

---Referenced by the API, not declared by the engine.
---@class Quaternion

---Referenced by the API, not declared by the engine.
---@class Vector2D
