---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class bit
bit = {}

function bit.arshift(...) end

function bit.band(...) end

function bit.bnot(...) end

function bit.bor(...) end

function bit.bswap(...) end

function bit.bxor(...) end

function bit.lshift(...) end

function bit.rol(...) end

function bit.ror(...) end

function bit.rshift(...) end

function bit.tobit(...) end

function bit.tohex(...) end
