---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CBaseAnimGraph : CBaseModelEntity, C_BaseModelEntity
CBaseAnimGraph = {}

function CBaseAnimGraph:IsNull(...) end
