---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CBaseAnimatingActivity : CBaseModelEntity, C_BaseModelEntity
CBaseAnimatingActivity = {}

function CBaseAnimatingActivity:IsNull(...) end
