---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CBodyComponent
CBodyComponent = {}

---Apply an impulse at a worldspace position to the physics
---@param Vector_1 Vector
---@param unknown_2 any
function CBodyComponent:AddImpulseAtPosition(Vector_1, unknown_2) end

---Add linear and angular velocity to the physics object
---@param Vector_1 Vector
---@param Vector_2 Vector
function CBodyComponent:AddVelocity(Vector_1, Vector_2) end

---Detach from its parent
function CBodyComponent:DetachFromParent() end

---Is attached to parent
---@return boolean
function CBodyComponent:IsAttachedToParent() end

function CBodyComponent:IsNull(...) end

---@param Vector_1 Vector
function CBodyComponent:SetAngularVelocity(Vector_1) end

---@param utlstringtoken_1 any
function CBodyComponent:SetMaterialGroup(utlstringtoken_1) end

---@param Vector_1 Vector
function CBodyComponent:SetVelocity(Vector_1) end
