---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CCustomNetTableManager
CCustomNetTableManager = {}

---( string TableName, string KeyName )
---@param string_1 string
---@param string_2 string
---@return table
function CCustomNetTableManager:GetTableValue(string_1, string_2) end

function CCustomNetTableManager:IsNull(...) end
