---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTAGameRules
CDOTAGameRules = {}

---Returns the hero unit IDs banned in this game, if any
---@return table
function CDOTAGameRules:GetBannedHeroIDs() end

---Returns the hero unit names banned in this game, if any
---@return table
function CDOTAGameRules:GetBannedHeroes() end

---Returns the difficulty level of the custom game mode
---@return integer
function CDOTAGameRules:GetCustomGameDifficulty() end

---(b IncludePregameTime b IncludeNegativeTime) Returns the actual DOTA in-game clock time.
---@param bool_1 boolean
---@param bool_2 boolean
---@return number
function CDOTAGameRules:GetDOTATime(bool_1, bool_2) end

---Returns difficulty level of the custom game mode
---@return integer
function CDOTAGameRules:GetDifficulty() end

---Returns the number of seconds elapsed since the last frame was renderered. This time doesn't count up when the game is paused
---@return number
function CDOTAGameRules:GetGameFrameTime() end

---Returns the number of seconds elapsed since map start. This time doesn't count up when the game is paused
---@return number
function CDOTAGameRules:GetGameTime() end

---Get the time it takes to add a new item to stock
---@param int_1 integer
---@param string_2 string
---@param int_3 integer
---@return number
function CDOTAGameRules:GetIetmStockDuration(int_1, string_2, int_3) end

---Get the stock count of the item
---@param int_1 integer
---@param string_2 string
---@param int_3 integer
---@return integer
function CDOTAGameRules:GetItemStockCount(int_1, string_2, int_3) end

---Get the time an item will be added to stock
---@param int_1 integer
---@param string_2 string
---@param int_3 integer
---@return number
function CDOTAGameRules:GetItemStockTime(int_1, string_2, int_3) end

---Gets the extra offset to initial neutral creep spawn delay
---@return number
function CDOTAGameRules:GetNeutralInitialSpawnOffset() end

---Get Weather Wind Direction Vector
---@return Vector
function CDOTAGameRules:GetWeatherWindDirection() end

---Are cheats enabled on the server
---@return boolean
function CDOTAGameRules:IsCheatMode() end

---@return boolean
function CDOTAGameRules:IsDev() end

---Is the hero not blacklisted, and is it either whitelisted or the whitelist is empty?
---@param string_1 string
---@return boolean
function CDOTAGameRules:IsHeroEnabledViaLists(string_1) end

function CDOTAGameRules:IsNull(...) end

---Are blacklisted heroes hidden, or just dimmed, in hero picking?
---@return boolean
function CDOTAGameRules:ShouldHideBlacklistedHeroes() end

---Get the current Gamerules state
---@return integer
function CDOTAGameRules:State_Get() end
