---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTAGameManager
CDOTAGameManager = {}

---Get the hero unit
---@param string_1 string
---@return table
function CDOTAGameManager:GetHeroDataByName_Script(string_1) end

---Get the hero ID given the hero name.
---@param string_1 string
---@return integer
function CDOTAGameManager:GetHeroIDByName(string_1) end

---Get the localization token for the given hero ID.
---@param int_1 integer
---@return string
function CDOTAGameManager:GetHeroLocTokenByID(int_1) end

---Get the hero name given a hero ID.
---@param int_1 integer
---@return string
function CDOTAGameManager:GetHeroNameByID(int_1) end

---Get the hero name given a unit name.
---@param string_1 string
---@return string
function CDOTAGameManager:GetHeroNameForUnitName(string_1) end

---Get the hero unit name given the hero ID.
---@param int_1 integer
---@return string
function CDOTAGameManager:GetHeroUnitNameByID(int_1) end

function CDOTAGameManager:IsNull(...) end
