---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTA_Modifier_Lua_Vertical_Motion : CDOTA_Modifier_Lua
CDOTA_Modifier_Lua_Vertical_Motion = {}

function CDOTA_Modifier_Lua_Vertical_Motion:IsNull(...) end
