---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTA_Modifier_Lua_Motion_Both : CDOTA_Modifier_Lua
CDOTA_Modifier_Lua_Motion_Both = {}

function CDOTA_Modifier_Lua_Motion_Both:IsNull(...) end
