---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CEntities
CEntities = {}

---Begin an iteration over the list of entities
---@return handle
function CEntities:First() end

---Get the local player controller (backcompat).
---@return handle
function CEntities:GetLocalPlayer() end

---Get the local player controller.
---@return handle
function CEntities:GetLocalPlayerController() end

---Get the local player pawn.
---@return handle
function CEntities:GetLocalPlayerPawn() end

function CEntities:IsNull(...) end

---Continue an iteration over the list of entities, providing reference to a previously found entity
---@param handle_1 handle
---@return handle
function CEntities:Next(handle_1) end
