---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CEntityScriptFramework
CEntityScriptFramework = {}

function CEntityScriptFramework:IsNull(...) end
