---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CEntityInstance
CEntityInstance = {}

---Adds an I/O connection that will call the named function on this entity when the specified output fires.
---@param string_1 string
---@param string_2 string
function CEntityInstance:ConnectOutput(string_1, string_2) end

function CEntityInstance:Destroy() end

---Removes a connected script function from an I/O event on this entity.
---@param string_1 string
---@param string_2 string
function CEntityInstance:DisconnectOutput(string_1, string_2) end

---Removes a connected script function from an I/O event on the passed entity.
---@param string_1 string
---@param string_2 string
---@param handle_3 handle
function CEntityInstance:DisconnectRedirectedOutput(string_1, string_2, handle_3) end

---Fire an entity output
---@param string_1 string
---@param handle_2 handle
---@param handle_3 handle
---@param table_4 table
---@param float_5 number
function CEntityInstance:FireOutput(string_1, handle_2, handle_3, table_4, float_5) end

---@return string
function CEntityInstance:GetClassname() end

---Get the entity name w/help if not defined (i.e. classname/etc)
---@return string
function CEntityInstance:GetDebugName() end

---Get the entity as an EHANDLE
---@return handle
function CEntityInstance:GetEntityHandle() end

---@return integer
function CEntityInstance:GetEntityIndex() end

---Get Integer Attribute
---@param string_1 string
---@return integer
function CEntityInstance:GetIntAttr(string_1) end

---Get the entity name
---@return string
function CEntityInstance:GetName() end

---Retrieve, creating if necessary, the private per-instance script-side data associated with an entity
---@return handle
function CEntityInstance:GetOrCreatePrivateScriptScope() end

---Retrieve, creating if necessary, the public script-side data associated with an entity
---@return handle
function CEntityInstance:GetOrCreatePublicScriptScope() end

---Retrieve the private per-instance script-side data associated with an entity
---@return handle
function CEntityInstance:GetPrivateScriptScope() end

---Retrieve the public script-side data associated with an entity
---@return handle
function CEntityInstance:GetPublicScriptScope() end

function CEntityInstance:IsNull(...) end

---Adds an I/O connection that will call the named function on the passed entity when the specified output fires.
---@param string_1 string
---@param string_2 string
---@param handle_3 handle
function CEntityInstance:RedirectOutput(string_1, string_2, handle_3) end

---Delete this entity
function CEntityInstance:RemoveSelf() end

---Set Integer Attribute
---@param string_1 string
---@param int_2 integer
function CEntityInstance:SetIntAttr(string_1, int_2) end

---@return integer
function CEntityInstance:entindex() end
