---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CInfoWorldLayer : CBaseEntity, C_BaseEntity
CInfoWorldLayer = {}

---Hides this layer
function CInfoWorldLayer:HideWorldLayer() end

function CInfoWorldLayer:IsNull(...) end

---Shows this layer
function CInfoWorldLayer:ShowWorldLayer() end
