---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CLogicRelay : CBaseEntity, C_BaseEntity
CLogicRelay = {}

function CLogicRelay:IsNull(...) end

---Trigger( hActivator, hCaller ) : Triggers the logic_relay
---@param hActivator handle
---@param hCaller handle
function CLogicRelay:Trigger(hActivator, hCaller) end
