---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CNativeOutputs
CNativeOutputs = {}

---Add an output
---@param string_1 string
---@param string_2 string
function CNativeOutputs:AddOutput(string_1, string_2) end

---Initialize with number of outputs
---@param int_1 integer
function CNativeOutputs:Init(int_1) end

function CNativeOutputs:IsNull(...) end
