---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class Convars
Convars = {}

---GetBool(name) : returns the convar as a boolean flag.
---@param string_1 string
---@return table
function Convars:GetBool(string_1) end

---GetCommandClient() : returns the player who issued this console command.
---@return handle
function Convars:GetCommandClient() end

---GetDOTACommandClient() : returns the DOTA player who issued this console command.
---@return handle
function Convars:GetDOTACommandClient() end

---GetFloat(name) : returns the convar as a float. May return null if no such convar.
---@param string_1 string
---@return table
function Convars:GetFloat(string_1) end

---GetInt(name) : returns the convar as an int. May return null if no such convar.
---@param string_1 string
---@return table
function Convars:GetInt(string_1) end

---GetStr(name) : returns the convar as a string. May return null if no such convar.
---@param string_1 string
---@return table
function Convars:GetStr(string_1) end

function Convars:IsNull(...) end

---RegisterCommand(name, fn, helpString, flags) : register a console command.
---@param string_1 string
---@param handle_2 handle
---@param string_3 string
---@param int_4 integer
function Convars:RegisterCommand(string_1, handle_2, string_3, int_4) end

---RegisterConvar(name, defaultValue, helpString, flags): register a new console variable.
---@param string_1 string
---@param string_2 string
---@param string_3 string
---@param int_4 integer
function Convars:RegisterConvar(string_1, string_2, string_3, int_4) end

---SetBool(name, val) : sets the value of the convar to the bool.
---@param string_1 string
---@param bool_2 boolean
function Convars:SetBool(string_1, bool_2) end

---SetFloat(name, val) : sets the value of the convar to the float.
---@param string_1 string
---@param float_2 number
function Convars:SetFloat(string_1, float_2) end

---SetInt(name, val) : sets the value of the convar to the int.
---@param string_1 string
---@param int_2 integer
function Convars:SetInt(string_1, int_2) end

---SetStr(name, val) : sets the value of the convar to the string.
---@param string_1 string
---@param string_2 string
function Convars:SetStr(string_1, string_2) end
