---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CScriptHTTPRequest
CScriptHTTPRequest = {}

function CScriptHTTPRequest:IsNull(...) end

---Send a HTTP request.
---@param handle_1 handle
---@return boolean
function CScriptHTTPRequest:Send(handle_1) end

---Set the total timeout on the request.
---@param unsigned_1 integer
---@return boolean
function CScriptHTTPRequest:SetHTTPRequestAbsoluteTimeoutMS(unsigned_1) end

---Set a POST or GET parameter on the request.
---@param string_1 string
---@param string_2 string
---@return boolean
function CScriptHTTPRequest:SetHTTPRequestGetOrPostParameter(string_1, string_2) end

---Set a header value on the request.
---@param string_1 string
---@param string_2 string
---@return boolean
function CScriptHTTPRequest:SetHTTPRequestHeaderValue(string_1, string_2) end

---Set the network timeout on the request - this timer is reset when any data is received.
---@param unsigned_1 integer
---@return boolean
function CScriptHTTPRequest:SetHTTPRequestNetworkActivityTimeout(unsigned_1) end

---Set the literal body of a post - invalid after setting a post parameter.
---@param string_1 string
---@param string_2 string
---@return boolean
function CScriptHTTPRequest:SetHTTPRequestRawPostBody(string_1, string_2) end
