---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CScriptUniformRandomStream
CScriptUniformRandomStream = {}

function CScriptUniformRandomStream:IsNull(...) end

---@param flMinVal number
---@param flMaxVal number
---@return number
function CScriptUniformRandomStream:RandomFloat(flMinVal, flMaxVal) end

---@param flMinVal number
---@param flMaxVal number
---@param flExponent number
---@return number
function CScriptUniformRandomStream:RandomFloatExp(flMinVal, flMaxVal, flExponent) end

---@param iMinVal integer
---@param iMaxVal integer
---@return integer
function CScriptUniformRandomStream:RandomInt(iMinVal, iMaxVal) end

---@param iPercentage integer
---@return boolean
function CScriptUniformRandomStream:RollPercentage(iPercentage) end
