---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CScriptPrecacheContext
CScriptPrecacheContext = {}

---Precaches a specific resource
---@param string_1 string
function CScriptPrecacheContext:AddResource(string_1) end

---Reads a spawn key
---@param string_1 string
---@return table
function CScriptPrecacheContext:GetValue(string_1) end

function CScriptPrecacheContext:IsNull(...) end
