---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CScriptParticleManager
CScriptParticleManager = {}

---Creates a new particle effect
---@param string_1 string
---@param int_2 integer
---@param handle_3 handle
---@return integer
function CScriptParticleManager:CreateParticle(string_1, int_2, handle_3) end

---Creates a new particle effect that only plays for the specified player
---@param string_1 string
---@param int_2 integer
---@param handle_3 handle
---@param handle_4 handle
---@return integer
function CScriptParticleManager:CreateParticleForPlayer(string_1, int_2, handle_3, handle_4) end

---Creates a new particle effect that only plays for the specified team
---@param string_1 string
---@param int_2 integer
---@param handle_3 handle
---@param int_4 integer
---@return integer
function CScriptParticleManager:CreateParticleForTeam(string_1, int_2, handle_3, int_4) end

---(int index, bool bDestroyImmediately) - Destroy a particle, if bDestroyImmediately destroy it without playing end caps.
---@param int_1 integer
---@param bool_2 boolean
function CScriptParticleManager:DestroyParticle(int_1, bool_2) end

---@param string_1 string
---@param handle_2 handle
---@return string
function CScriptParticleManager:GetParticleReplacement(string_1, handle_2) end

function CScriptParticleManager:IsNull(...) end

---Frees the specified particle index
---@param int_1 integer
function CScriptParticleManager:ReleaseParticleIndex(int_1) end

---@param int_1 integer
function CScriptParticleManager:SetParticleAlwaysSimulate(int_1) end

---Set the control point data for a control on a particle effect
---@param int_1 integer
---@param int_2 integer
---@param Vector_3 Vector
function CScriptParticleManager:SetParticleControl(int_1, int_2, Vector_3) end

---@param int_1 integer
---@param int_2 integer
---@param handle_3 handle
---@param int_4 integer
---@param string_5 string
---@param unknown_6 any
---@param bool_7 boolean
function CScriptParticleManager:SetParticleControlEnt(int_1, int_2, handle_3, int_4, string_5, unknown_6, bool_7) end

---(int iIndex, int iPoint, Vector vecPosition)
---@param int_1 integer
---@param int_2 integer
---@param unknown_3 any
function CScriptParticleManager:SetParticleControlFallback(int_1, int_2, unknown_3) end

---[OBSOLETE - Use SetParticleControlTransformForward] (int nFXIndex, int nPoint, vForward)
---@param int_1 integer
---@param int_2 integer
---@param Vector_3 Vector
function CScriptParticleManager:SetParticleControlForward(int_1, int_2, Vector_3) end

---[OBSOLETE - Use SetParticleControlTransform] (int nFXIndex, int nPoint, vForward, vRight, vUp) - Set the orientation for a control on a particle effect (NOTE: This is left handed -- bad!!)
---@param int_1 integer
---@param int_2 integer
---@param Vector_3 Vector
---@param Vector_4 Vector
---@param Vector_5 Vector
function CScriptParticleManager:SetParticleControlOrientation(int_1, int_2, Vector_3, Vector_4, Vector_5) end

---[OBSOLETE - Use SetParticleControlTransform] (int nFXIndex, int nPoint, Vector vecForward, Vector vecLeft, Vector vecUp) - Set the orientation for a control on a particle effect
---@param int_1 integer
---@param int_2 integer
---@param Vector_3 Vector
---@param Vector_4 Vector
---@param Vector_5 Vector
function CScriptParticleManager:SetParticleControlOrientationFLU(int_1, int_2, Vector_3, Vector_4, Vector_5) end

---(int nFXIndex, int nPoint, vOrigin, qAngles)
---@param int_1 integer
---@param int_2 integer
---@param Vector_3 Vector
---@param QAngle_4 QAngle
function CScriptParticleManager:SetParticleControlTransform(int_1, int_2, Vector_3, QAngle_4) end

---(int nFXIndex, int nPoint, vOrigin, vForward)
---@param int_1 integer
---@param int_2 integer
---@param unknown_3 any
---@param Vector_4 Vector
function CScriptParticleManager:SetParticleControlTransformForward(int_1, int_2, unknown_3, Vector_4) end

---int nfxindex, int nPoint, int nPoint2, float flRadius
---@param int_1 integer
---@param int_2 integer
---@param int_3 integer
---@param float_4 number
function CScriptParticleManager:SetParticleFoWProperties(int_1, int_2, int_3, float_4) end

---int nfxindex, bool bCheckFoW
---@param int_1 integer
---@param bool_2 boolean
---@return boolean
function CScriptParticleManager:SetParticleShouldCheckFoW(int_1, bool_2) end
