---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CScriptKeyValues
CScriptKeyValues = {}

---Reads a spawn key
---@param string_1 string
---@return table
function CScriptKeyValues:GetValue(string_1) end

function CScriptKeyValues:IsNull(...) end
