---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class EntityUtils
EntityUtils = {}

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:450.
function EntityUtils.GetClassFieldType(self, classname, fieldname) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:430.
function EntityUtils.GetRootScriptClass(self, classOrObj) end
