---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class EntityFramework
---@field InputValueConverters table
---@field InstallClassMixinKeysToIgnore table
---@field InstallClassMixinKeysToMakeUnique table
---@field InstallClassVisits table
EntityFramework = {}

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:226.
function EntityFramework.AddClassToGameData(self, lookupName, classObj, GameDataObj) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:330.
function EntityFramework.CreateCppClassProxy(self, className) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:344.
function EntityFramework.CreateCppLinkClassProxyInstance(self, className) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:337.
function EntityFramework.CreateEntity(self, className, instance) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:254.
function EntityFramework.CreateScriptProxyClass(self, className) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:581.
function EntityFramework.DispatchActivate(self, ent) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:598.
function EntityFramework.DispatchInput(self, inputName, target, args) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:561.
function EntityFramework.DispatchPrecache(self, ent, context) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:572.
function EntityFramework.DispatchSpawn(self, ent, entityKeyValues) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:591.
function EntityFramework.DispatchUpdateOnRemove(self, ent) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:349.
function EntityFramework.GetClassNameOverride(self, className) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:366.
function EntityFramework.GetDesignerNameForScriptClass(self, scriptClassName) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:607.
function EntityFramework.GetEntityHandle(self, ent) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:378.
function EntityFramework.GetInputsForScriptClass(self, scriptClassName) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:406.
function EntityFramework.GetNativeClassForDesignerName(self, name) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:395.
function EntityFramework.GetNativeClassForScriptClass(self, scriptClassName) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:411.
function EntityFramework.GetNativeOutputsForClass(self, className) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:358.
function EntityFramework.GetScriptClassForDesignerName(self, designerName) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:109.
function EntityFramework.InstallClass(self, className) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:156.
function EntityFramework.InstallClass_BuildCompleteSpecification(self, classObj) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:179.
function EntityFramework.InstallClass_HandleEntityIO(self, classObj) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:136.
function EntityFramework.InstallClass_MergeSpecifications(self, primary, secondary) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:210.
function EntityFramework.InstallClass_Publish(self, className, classObj) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:88.
function EntityFramework.InstallClasses(self) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:474.
function EntityFramework.IsKeyValueUsed(self, entname, keyid) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:233.
function EntityFramework.LoadEntityClasses(self, GameDataObj) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:612.
function EntityFramework.PrecacheResource(self, resourceName) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:494.
function EntityFramework.UnserializeForPrecache(self, ent, context) end

---Defined in scripts/vscripts/framework/entities/entitiesinit.lua:525.
function EntityFramework.UnserializeForSpawn(self, ent, entityKeyValues) end
