---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class g_reloadState
---@field _G table
---@field bit table
---@field coroutine table
---@field debug table
---@field math table
---@field package table
---@field string table
---@field table table
g_reloadState = {}
