---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class GlobalSys
GlobalSys = {}

---CommandLineCheck(name) : returns true if the command line param was used, otherwise false.
---@param string_1 string
---@return table
function GlobalSys:CommandLineCheck(string_1) end

---CommandLineFloat(name) : returns the command line param as a float.
---@param string_1 string
---@param float_2 number
---@return table
function GlobalSys:CommandLineFloat(string_1, float_2) end

---CommandLineInt(name) : returns the command line param as an int.
---@param string_1 string
---@param int_2 integer
---@return table
function GlobalSys:CommandLineInt(string_1, int_2) end

---CommandLineStr(name) : returns the command line param as a string.
---@param string_1 string
---@param string_2 string
---@return table
function GlobalSys:CommandLineStr(string_1, string_2) end

function GlobalSys:IsNull(...) end
