---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class json
---@field null table
---@field version string
json = {}

---Defined in scripts/vscripts/game/dkjson.lua:201.
function json.addnewline(state) end

---Defined in scripts/vscripts/game/dkjson.lua:595.
function json.decode(str, pos, nullval, ...) end

---Defined in scripts/vscripts/game/dkjson.lua:356.
function json.encode(value, state) end

---Defined in scripts/vscripts/game/dkjson.lua:249.
function json.encodeexception(reason, value, state, defaultmessage) end

---Defined in scripts/vscripts/game/dkjson.lua:144.
function json.quotestring(value) end

---Defined in scripts/vscripts/game/dkjson.lua:600.
function json.use_lpeg() end
