---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class ParticleEffectControlPoints
---@field __class__ table
---@field __initprops__ table
ParticleEffectControlPoints = {}

---Defined in scripts/vscripts/utils/class.lua:222.
function ParticleEffectControlPoints.__getbase__(classObj) end

---Defined in scripts/vscripts/utils/class.lua:204.
function ParticleEffectControlPoints.__getclass__(instanceObj) end

---Defined in scripts/vscripts/utils/class.lua:193.
function ParticleEffectControlPoints.__instanceof__(instanceObj, classObj) end
