---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Fields, operators and method signatures found by trying a sample; parameter names unknown.
---@class QAngle
---@field x number
---@field y number
---@field z number
---@operator add(QAngle): QAngle
---@field Forward fun(self: QAngle): Vector
---@field Left fun(self: QAngle): Vector
---@field Up fun(self: QAngle): Vector

---@return QAngle
function QAngle(...) end
