---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Fields, operators and method signatures found by trying a sample; parameter names unknown.
---@class Vector
---@field b number
---@field g number
---@field r number
---@field x number
---@field y number
---@field z number
---@operator add(Vector): Vector
---@operator add(number): Vector
---@operator sub(Vector): Vector
---@operator sub(number): Vector
---@operator mul(Vector): Vector
---@operator mul(number): Vector
---@operator div(Vector): Vector
---@operator div(number): Vector
---@operator unm: Vector
---@operator len: number
---@field Cross fun(self: Vector, arg1: Vector): Vector
---@field Dot fun(self: Vector, arg1: Vector): number
---@field Length fun(self: Vector): number
---@field Length2D fun(self: Vector): number
---@field Lerp fun(self: Vector, arg1: Vector, arg2: number): Vector
---@field Normalized fun(self: Vector): Vector

---@return Vector
function Vector(...) end
