---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class vlua
vlua = {}

---Defined in scripts/vscripts/utils/library.lua:9.
function vlua.clear(t) end

---Defined in scripts/vscripts/utils/library.lua:51.
function vlua.clone(t) end

---Defined in scripts/vscripts/utils/library.lua:21.
function vlua.compare(a, b) end

---Defined in scripts/vscripts/utils/library.lua:34.
function vlua.contains(t, k) end

---Defined in scripts/vscripts/utils/library.lua:40.
function vlua.delete(t, k) end

---Defined in scripts/vscripts/utils/library.lua:184.
function vlua.extend(o, ary) end

---Defined in scripts/vscripts/utils/library.lua:83.
function vlua.find(o, arg1, ...) end

---Defined in scripts/vscripts/utils/library.lua:197.
function vlua.map(o, fn) end

---Defined in scripts/vscripts/utils/library.lua:65.
function vlua.rawdelete(t, k) end

---Defined in scripts/vscripts/utils/library.lua:73.
function vlua.rawin(t, k) end

---Defined in scripts/vscripts/utils/library.lua:207.
function vlua.reduce(o, fn) end

---Defined in scripts/vscripts/utils/library.lua:160.
function vlua.resize(o, size, ...) end

---Defined in scripts/vscripts/utils/library.lua:148.
function vlua.reverse(o) end

---Defined in scripts/vscripts/utils/library.lua:270.
function vlua.select(conditional, valueIfTrue, valueIfFalse) end

---Defined in scripts/vscripts/utils/library.lua:113.
function vlua.slice(o, starti, ...) end

---Defined in scripts/vscripts/utils/library.lua:232.
function vlua.split(str, sep) end

---Defined in scripts/vscripts/utils/library.lua:223.
function vlua.tableadd(t1, t2) end
