---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@alias DAMAGE_TYPES integer

---@type DAMAGE_TYPES
DAMAGE_TYPE_ABILITY_DEFINED = 16

---@type DAMAGE_TYPES
DAMAGE_TYPE_ALL = 7

---@type DAMAGE_TYPES
DAMAGE_TYPE_HP_REMOVAL = 8

---@type DAMAGE_TYPES
DAMAGE_TYPE_MAGICAL = 2

---@type DAMAGE_TYPES
DAMAGE_TYPE_NONE = 0

---@type DAMAGE_TYPES
DAMAGE_TYPE_PHYSICAL = 1

---@type DAMAGE_TYPES
DAMAGE_TYPE_PURE = 4

---Server only.
---@alias DOTADamageFlag_t integer

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_ATTACK_MODIFIER = 262144

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_BYPASSES_ALL_BLOCK = 524288

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_BYPASSES_INVULNERABILITY = 4

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_BYPASSES_PHYSICAL_BLOCK = 8

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_DONT_DISPLAY_DAMAGE_IF_SOURCE_HIDDEN = 2048

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_FORCE_SPELL_AMPLIFICATION = 65536

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_HPLOSS = 32

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_IGNORES_BASE_PHYSICAL_ARMOR = 16384

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_IGNORES_MAGIC_ARMOR = 1

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_IGNORES_PHYSICAL_ARMOR = 2

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_MAGIC_AUTO_ATTACK = 131072

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_NONE = 0

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_NON_LETHAL = 128

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_NO_DAMAGE_MULTIPLIERS = 512

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_NO_DIRECTOR_EVENT = 64

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_NO_REFLECTION = 1048576

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_NO_SPELL_AMPLIFICATION = 1024

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_NO_SPELL_LIFESTEAL = 4096

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_PROPERTY_FIRE = 8192

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_REFLECTION = 16

---@type DOTADamageFlag_t
DOTA_DAMAGE_FLAG_SECONDARY_PROJECTILE_ATTACK = 32768

---Server only.
---@alias DOTAHUDVisibility_t integer

---@type DOTAHUDVisibility_t
DOTA_HUD_CUSTOMUI_BEHIND_HUD_ELEMENTS = 30

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_ACTION_MINIMAP = 4

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_ACTION_PANEL = 3

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_AGHANIMS_STATUS = 31

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_COUNT = 32

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_ENDGAME = 23

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_ENDGAME_CHAT = 24

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_FIGHT_RECAP = 28

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_HERO_SELECTION_CLOCK = 16

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_HERO_SELECTION_GAME_NAME = 15

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_HERO_SELECTION_HEADER = 17

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_HERO_SELECTION_TEAMS = 14

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_INVALID = -1

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_INVENTORY_COURIER = 9

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_INVENTORY_GOLD = 11

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_INVENTORY_ITEMS = 7

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_INVENTORY_PANEL = 5

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_INVENTORY_PROTECT = 10

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_INVENTORY_QUICKBUY = 8

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_INVENTORY_SHOP = 6

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_KILLCAM = 27

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_PREGAME_STRATEGYUI = 26

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_QUICK_STATS = 25

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_SHOP_COMMONITEMS = 13

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_SHOP_SUGGESTEDITEMS = 12

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_BAR = 29

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_BAR_BACKGROUND = 19

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_BAR_DIRE_TEAM = 21

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_BAR_RADIANT_TEAM = 20

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_BAR_SCORE = 22

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_HEROES = 1

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_MENU_BUTTONS = 18

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_SCOREBOARD = 2

---@type DOTAHUDVisibility_t
DOTA_HUD_VISIBILITY_TOP_TIMEOFDAY = 0

---Server only.
---@alias DOTAInventoryFlags_t integer

---@type DOTAInventoryFlags_t
DOTA_INVENTORY_ALLOW_DROP_AT_FOUNTAIN = 8

---@type DOTAInventoryFlags_t
DOTA_INVENTORY_ALLOW_DROP_ON_GROUND = 4

---@type DOTAInventoryFlags_t
DOTA_INVENTORY_ALLOW_MAIN = 1

---@type DOTAInventoryFlags_t
DOTA_INVENTORY_ALLOW_NONE = 0

---@type DOTAInventoryFlags_t
DOTA_INVENTORY_ALLOW_STASH = 2

---@type DOTAInventoryFlags_t
DOTA_INVENTORY_ALL_ACCESS = 3

---@type DOTAInventoryFlags_t
DOTA_INVENTORY_LIMIT_DROP_ON_GROUND = 16

---Server only.
---@alias DOTAMinimapEvent_t integer

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_ANCIENT_UNDER_ATTACK = 2

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_BASE_GLYPHED = 8

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_BASE_UNDER_ATTACK = 4

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_CANCEL_TELEPORTING = 2048

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_ENEMY_TELEPORTING = 1024

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_HINT_LOCATION = 512

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_MOVE_TO_TARGET = 16384

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_RADAR = 4096

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_RADAR_TARGET = 8192

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_TEAMMATE_DIED = 64

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_TEAMMATE_TELEPORTING = 32

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_TEAMMATE_UNDER_ATTACK = 16

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_TUTORIAL_TASK_ACTIVE = 128

---@type DOTAMinimapEvent_t
DOTA_MINIMAP_EVENT_TUTORIAL_TASK_FINISHED = 256

---Server only.
---@alias DOTAMusicStatus_t integer

---@type DOTAMusicStatus_t
DOTA_MUSIC_STATUS_BATTLE = 2

---@type DOTAMusicStatus_t
DOTA_MUSIC_STATUS_DEAD = 4

---@type DOTAMusicStatus_t
DOTA_MUSIC_STATUS_EXPLORATION = 1

---@type DOTAMusicStatus_t
DOTA_MUSIC_STATUS_LAST = 5

---@type DOTAMusicStatus_t
DOTA_MUSIC_STATUS_NONE = 0

---@type DOTAMusicStatus_t
DOTA_MUSIC_STATUS_PRE_GAME_EXPLORATION = 3

---Server only.
---@alias DOTAPostGameColumn_t integer

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_ASSISTS = 4

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_DAMAGE = 8

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_DEATHS = 3

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_DENIES = 7

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_HEALING = 9

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_ITEMS = 1

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_KILLS = 2

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_LAST_HITS = 6

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_LEVEL = 0

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_MAX = 10

---@type DOTAPostGameColumn_t
DOTA_POST_GAME_COLUMN_NET_WORTH = 5

---Server only.
---@alias DOTAPostGameLayout_t integer

---@type DOTAPostGameLayout_t
DOTA_POST_GAME_LAYOUT_DOUBLE_COLUMN = 0

---@type DOTAPostGameLayout_t
DOTA_POST_GAME_LAYOUT_MAX = 2

---@type DOTAPostGameLayout_t
DOTA_POST_GAME_LAYOUT_SINGLE_COLUMN = 1

---Server only.
---@alias DOTAProjectileAttachment_t integer

---@type DOTAProjectileAttachment_t
DOTA_PROJECTILE_ATTACHMENT_ATTACK_1 = 1

---@type DOTAProjectileAttachment_t
DOTA_PROJECTILE_ATTACHMENT_ATTACK_2 = 2

---@type DOTAProjectileAttachment_t
DOTA_PROJECTILE_ATTACHMENT_ATTACK_3 = 4

---@type DOTAProjectileAttachment_t
DOTA_PROJECTILE_ATTACHMENT_ATTACK_4 = 5

---@type DOTAProjectileAttachment_t
DOTA_PROJECTILE_ATTACHMENT_HITLOCATION = 3

---@type DOTAProjectileAttachment_t
DOTA_PROJECTILE_ATTACHMENT_LAST = 6

---@type DOTAProjectileAttachment_t
DOTA_PROJECTILE_ATTACHMENT_NONE = 0

---Server only.
---@alias DOTAScriptInventorySlot_t integer

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_1 = 0

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_2 = 1

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_3 = 2

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_4 = 3

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_5 = 4

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_6 = 5

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_7 = 6

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_8 = 7

---@type DOTAScriptInventorySlot_t
DOTA_ITEM_SLOT_9 = 8

---@type DOTAScriptInventorySlot_t
DOTA_STASH_SLOT_1 = 9

---@type DOTAScriptInventorySlot_t
DOTA_STASH_SLOT_2 = 10

---@type DOTAScriptInventorySlot_t
DOTA_STASH_SLOT_3 = 11

---@type DOTAScriptInventorySlot_t
DOTA_STASH_SLOT_4 = 12

---@type DOTAScriptInventorySlot_t
DOTA_STASH_SLOT_5 = 13

---@type DOTAScriptInventorySlot_t
DOTA_STASH_SLOT_6 = 14

---Server only.
---@alias DOTASlotType_t integer

---@type DOTASlotType_t
DOTA_LOADOUT_PERSONA_1_END = 77

---@type DOTASlotType_t
DOTA_LOADOUT_PERSONA_1_START = 40

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY1 = 25

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY1_PERSONA_1 = 63

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY2 = 26

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY2_PERSONA_1 = 64

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY3 = 27

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY3_PERSONA_1 = 65

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY4 = 28

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY4_PERSONA_1 = 66

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_ATTACK = 24

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_ATTACK_PERSONA_1 = 62

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_1 = 30

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_1_PERSONA_1 = 68

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_2 = 31

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_2_PERSONA_1 = 69

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_3 = 32

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_3_PERSONA_1 = 70

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_4 = 33

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_4_PERSONA_1 = 71

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_5 = 34

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_5_PERSONA_1 = 72

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_6 = 35

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_6_PERSONA_1 = 73

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_7 = 36

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_7_PERSONA_1 = 74

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_8 = 37

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_8_PERSONA_1 = 75

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_9 = 38

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_EFFECTS_9_PERSONA_1 = 76

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_ULTIMATE = 29

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ABILITY_ULTIMATE_PERSONA_1 = 67

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_AMBIENT_EFFECTS = 23

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_AMBIENT_EFFECTS_PERSONA_1 = 61

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ANCIENT = 109

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ANNOUNCER = 80

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ARMOR = 7

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ARMOR_PERSONA_1 = 47

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ARMS = 6

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ARMS_PERSONA_1 = 46

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_BACK = 10

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_BACK_PERSONA_1 = 50

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_BELT = 8

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_BELT_PERSONA_1 = 48

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_BLINK_EFFECT = 91

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_BODY_HEAD = 17

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_BODY_HEAD_PERSONA_1 = 55

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_COSTUME = 15

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_COUNT = 112

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_COURIER = 79

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_COURIER_EFFECT = 104

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_CURSOR_PACK = 89

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_DEATH_EFFECT = 101

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_DIRE_CREEPS = 95

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_DIRE_SIEGE_CREEPS = 106

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_DIRE_TOWER = 97

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_EMBLEM = 92

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_GLOVES = 11

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_GLOVES_PERSONA_1 = 52

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_HEAD = 4

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_HEAD_EFFECT = 102

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_HEAD_PERSONA_1 = 44

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_HEROIC_STATUE = 87

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_HERO_BASE = 16

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_HERO_EFFIGY = 22

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_HERO_EFFIGY_PERSONA_1 = 60

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_HUD_SKIN = 84

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_INVALID = -1

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_KILL_EFFECT = 100

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_LEGS = 12

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_LEGS_PERSONA_1 = 51

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_LOADING_SCREEN = 85

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_MAP_EFFECT = 103

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_MEGA_KILLS = 81

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_MISC = 14

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_MISC_PERSONA_1 = 54

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_MOUNT = 18

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_MOUNT_PERSONA_1 = 56

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_MULTIKILL_BANNER = 88

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_MUSIC = 82

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_NECK = 9

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_NECK_PERSONA_1 = 49

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_NONE = 111

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_OFFHAND_WEAPON = 1

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_OFFHAND_WEAPON2 = 3

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_OFFHAND_WEAPON2_PERSONA_1 = 43

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_OFFHAND_WEAPON_PERSONA_1 = 41

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_PERSONA_SELECTOR = 78

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_PET_EFFIGY = 110

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_RADIANT_CREEPS = 94

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_RADIANT_SIEGE_CREEPS = 105

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_RADIANT_TOWER = 96

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_ROSHAN = 107

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_SHAPESHIFT = 20

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_SHAPESHIFT_PERSONA_1 = 58

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_SHOULDER = 5

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_SHOULDER_PERSONA_1 = 45

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_STREAK_EFFECT = 99

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_SUMMON = 19

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_SUMMON_PERSONA_1 = 57

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_TAIL = 13

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_TAIL_PERSONA_1 = 53

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_TAUNT = 21

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_TAUNT_PERSONA_1 = 59

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_TELEPORT_EFFECT = 90

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_TERRAIN = 93

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_TORMENTOR = 108

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_VERSUS_SCREEN = 98

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_VOICE = 39

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_VOICE_PERSONA_1 = 77

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_WARD = 83

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_WEAPON = 0

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_WEAPON2 = 2

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_WEAPON2_PERSONA_1 = 42

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_WEAPON_PERSONA_1 = 40

---@type DOTASlotType_t
DOTA_LOADOUT_TYPE_WEATHER = 86

---@type DOTASlotType_t
DOTA_PLAYER_LOADOUT_END = 110

---@type DOTASlotType_t
DOTA_PLAYER_LOADOUT_START = 79

---Server only.
---@alias DOTAUnitAttackCapability_t integer

---@type DOTAUnitAttackCapability_t
DOTA_UNIT_ATTACK_CAPABILITY_BIT_COUNT = 3

---@type DOTAUnitAttackCapability_t
DOTA_UNIT_CAP_MELEE_ATTACK = 1

---@type DOTAUnitAttackCapability_t
DOTA_UNIT_CAP_NO_ATTACK = 0

---@type DOTAUnitAttackCapability_t
DOTA_UNIT_CAP_RANGED_ATTACK = 2

---@type DOTAUnitAttackCapability_t
DOTA_UNIT_CAP_RANGED_ATTACK_DIRECTIONAL = 4

---Server only.
---@alias DOTAUnitMoveCapability_t integer

---@type DOTAUnitMoveCapability_t
DOTA_UNIT_CAP_MOVE_FLY = 2

---@type DOTAUnitMoveCapability_t
DOTA_UNIT_CAP_MOVE_GROUND = 1

---@type DOTAUnitMoveCapability_t
DOTA_UNIT_CAP_MOVE_NONE = 0

---Server only.
---@alias DOTA_GameState integer

---@type DOTA_GameState
DOTA_GAMERULES_STATE_CUSTOM_GAME_SETUP = 2

---@type DOTA_GameState
DOTA_GAMERULES_STATE_DISCONNECT = 12

---@type DOTA_GameState
DOTA_GAMERULES_STATE_GAME_IN_PROGRESS = 10

---@type DOTA_GameState
DOTA_GAMERULES_STATE_HERO_SELECTION = 4

---@type DOTA_GameState
DOTA_GAMERULES_STATE_INIT = 0

---@type DOTA_GameState
DOTA_GAMERULES_STATE_PLAYER_DRAFT = 3

---@type DOTA_GameState
DOTA_GAMERULES_STATE_POST_GAME = 11

---@type DOTA_GameState
DOTA_GAMERULES_STATE_PRE_GAME = 8

---@type DOTA_GameState
DOTA_GAMERULES_STATE_SCENARIO_SETUP = 9

---@type DOTA_GameState
DOTA_GAMERULES_STATE_STRATEGY_TIME = 5

---@type DOTA_GameState
DOTA_GAMERULES_STATE_TEAM_SHOWCASE = 6

---@type DOTA_GameState
DOTA_GAMERULES_STATE_WAIT_FOR_MAP_TO_LOAD = 7

---@type DOTA_GameState
DOTA_GAMERULES_STATE_WAIT_FOR_PLAYERS_TO_LOAD = 1

---Server only.
---@alias DamageCategory_t integer

---@type DamageCategory_t
DOTA_DAMAGE_CATEGORY_ATTACK = 1

---@type DamageCategory_t
DOTA_DAMAGE_CATEGORY_BARRIER = 2

---@type DamageCategory_t
DOTA_DAMAGE_CATEGORY_SPELL = 0

---Server only.
---@alias DotaDefaultUIElement_t integer

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_ACTION_MINIMAP = 4

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_ACTION_PANEL = 3

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_AGHANIMS_STATUS = 31

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_CUSTOMUI_BEHIND_HUD_ELEMENTS = 30

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_ELEMENT_COUNT = 32

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_ENDGAME = 23

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_ENDGAME_CHAT = 24

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_FIGHT_RECAP = 28

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_FLYOUT_SCOREBOARD = 2

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_HERO_SELECTION_CLOCK = 16

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_HERO_SELECTION_GAME_NAME = 15

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_HERO_SELECTION_HEADER = 17

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_HERO_SELECTION_TEAMS = 14

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_INVALID = -1

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_INVENTORY_COURIER = 9

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_INVENTORY_GOLD = 11

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_INVENTORY_ITEMS = 7

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_INVENTORY_PANEL = 5

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_INVENTORY_PROTECT = 10

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_INVENTORY_QUICKBUY = 8

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_INVENTORY_SHOP = 6

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_KILLCAM = 27

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_PREGAME_STRATEGYUI = 26

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_QUICK_STATS = 25

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_SHOP_COMMONITEMS = 13

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_SHOP_SUGGESTEDITEMS = 12

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_TOP_BAR = 29

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_TOP_BAR_BACKGROUND = 19

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_TOP_BAR_DIRE_TEAM = 21

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_TOP_BAR_RADIANT_TEAM = 20

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_TOP_BAR_SCORE = 22

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_TOP_HEROES = 1

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_TOP_MENU_BUTTONS = 18

---@type DotaDefaultUIElement_t
DOTA_DEFAULT_UI_TOP_TIMEOFDAY = 0

---Server only.
---@alias EDOTA_ModifyGold_Reason integer

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_AbandonedRedistribute = 5

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_AbilityCost = 7

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_AbilityGold = 19

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_BountyRune = 17

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_Building = 11

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_Buyback = 2

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_CheatCommand = 8

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_CourierKill = 16

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_CourierKilledByThisPlayer = 21

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_CreepKill = 13

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_Death = 1

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_GameTick = 10

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_HeroKill = 12

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_NeutralKill = 14

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_PurchaseConsumable = 3

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_PurchaseItem = 4

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_RoshanKill = 15

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_SelectionPenalty = 9

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_SellItem = 6

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_SharedGold = 18

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_SummonKill = 22

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_Unspecified = 0

---@type EDOTA_ModifyGold_Reason
DOTA_ModifyGold_WardKill = 20

---Server only.
---@alias EDOTA_ModifyXP_Reason integer

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_CatchUp = 6

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_CreepKill = 2

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_HeroAbility = 7

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_HeroKill = 1

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_MAX = 9

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_Outpost = 5

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_RoshanKill = 3

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_SummonKill = 8

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_TomeOfKnowledge = 4

---@type EDOTA_ModifyXP_Reason
DOTA_ModifyXP_Unspecified = 0

---Server only.
---@alias EShareAbility integer

---@type EShareAbility
ITEM_FULLY_SHAREABLE = 0

---@type EShareAbility
ITEM_NOT_SHAREABLE = 2

---@type EShareAbility
ITEM_PARTIALLY_SHAREABLE = 1

---Server only.
---@alias GameActivity_t integer

---@type GameActivity_t
ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_END = 1580

---@type GameActivity_t
ACT_DOTA_ALCHEMIST_CHEMICAL_RAGE_START = 1572

---@type GameActivity_t
ACT_DOTA_ALCHEMIST_CONCOCTION = 1573

---@type GameActivity_t
ACT_DOTA_ALCHEMIST_CONCOCTION_THROW = 1579

---@type GameActivity_t
ACT_DOTA_AMBUSH = 1627

---@type GameActivity_t
ACT_DOTA_ANCESTRAL_SPIRIT = 1677

---@type GameActivity_t
ACT_DOTA_ARCTIC_BURN_END = 1682

---@type GameActivity_t
ACT_DOTA_AREA_DENY = 1661

---@type GameActivity_t
ACT_DOTA_ATTACK = 1503

---@type GameActivity_t
ACT_DOTA_ATTACK2 = 1504

---@type GameActivity_t
ACT_DOTA_ATTACK_EVENT = 1505

---@type GameActivity_t
ACT_DOTA_ATTACK_EVENT_BASH = 1705

---@type GameActivity_t
ACT_DOTA_ATTACK_SPECIAL = 1758

---@type GameActivity_t
ACT_DOTA_AW_MAGNETIC_FIELD = 1707

---@type GameActivity_t
ACT_DOTA_BELLYACHE_END = 1614

---@type GameActivity_t
ACT_DOTA_BELLYACHE_LOOP = 1613

---@type GameActivity_t
ACT_DOTA_BELLYACHE_START = 1612

---@type GameActivity_t
ACT_DOTA_BLINK_DAGGER = 1732

---@type GameActivity_t
ACT_DOTA_BLINK_DAGGER_END = 1733

---@type GameActivity_t
ACT_DOTA_BRIDGE_DESTROY = 1640

---@type GameActivity_t
ACT_DOTA_BRIDGE_THREAT = 1650

---@type GameActivity_t
ACT_DOTA_CAGED_CREEP_RAGE = 1644

---@type GameActivity_t
ACT_DOTA_CAGED_CREEP_RAGE_OUT = 1645

---@type GameActivity_t
ACT_DOTA_CAGED_CREEP_SMASH = 1646

---@type GameActivity_t
ACT_DOTA_CAGED_CREEP_SMASH_OUT = 1647

---@type GameActivity_t
ACT_DOTA_CANCEL_SIREN_SONG = 1599

---@type GameActivity_t
ACT_DOTA_CAPTURE = 1533

---@type GameActivity_t
ACT_DOTA_CAPTURE_CARD = 1717

---@type GameActivity_t
ACT_DOTA_CAPTURE_PET = 1698

---@type GameActivity_t
ACT_DOTA_CAPTURE_RARE = 1706

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_1 = 1510

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_1_END = 1540

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_2 = 1511

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_2_ALLY = 1748

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_2_END = 1541

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_2_ES_ROLL = 1653

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_2_ES_ROLL_END = 1654

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_2_ES_ROLL_START = 1652

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_3 = 1512

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_3_END = 1542

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_4 = 1513

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_4_END = 1543

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_5 = 1514

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_6 = 1515

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_7 = 1598

---@type GameActivity_t
ACT_DOTA_CAST_ABILITY_ROT = 1547

---@type GameActivity_t
ACT_DOTA_CAST_ALACRITY = 1585

---@type GameActivity_t
ACT_DOTA_CAST_ALACRITY_ORB = 1741

---@type GameActivity_t
ACT_DOTA_CAST_BURROW_END = 1702

---@type GameActivity_t
ACT_DOTA_CAST_CHAOS_METEOR = 1586

---@type GameActivity_t
ACT_DOTA_CAST_CHAOS_METEOR_ORB = 1742

---@type GameActivity_t
ACT_DOTA_CAST_COLD_SNAP = 1581

---@type GameActivity_t
ACT_DOTA_CAST_COLD_SNAP_ORB = 1737

---@type GameActivity_t
ACT_DOTA_CAST_DEAFENING_BLAST = 1590

---@type GameActivity_t
ACT_DOTA_CAST_DEAFENING_BLAST_ORB = 1746

---@type GameActivity_t
ACT_DOTA_CAST_DRAGONBREATH = 1538

---@type GameActivity_t
ACT_DOTA_CAST_EMP = 1584

---@type GameActivity_t
ACT_DOTA_CAST_EMP_ORB = 1740

---@type GameActivity_t
ACT_DOTA_CAST_FORGE_SPIRIT = 1588

---@type GameActivity_t
ACT_DOTA_CAST_FORGE_SPIRIT_ORB = 1744

---@type GameActivity_t
ACT_DOTA_CAST_GHOST_SHIP = 1708

---@type GameActivity_t
ACT_DOTA_CAST_GHOST_WALK = 1582

---@type GameActivity_t
ACT_DOTA_CAST_GHOST_WALK_ORB = 1738

---@type GameActivity_t
ACT_DOTA_CAST_ICE_WALL = 1589

---@type GameActivity_t
ACT_DOTA_CAST_ICE_WALL_ORB = 1745

---@type GameActivity_t
ACT_DOTA_CAST_LIFE_BREAK_END = 1564

---@type GameActivity_t
ACT_DOTA_CAST_LIFE_BREAK_START = 1563

---@type GameActivity_t
ACT_DOTA_CAST_REFRACTION = 1597

---@type GameActivity_t
ACT_DOTA_CAST_SUN_STRIKE = 1587

---@type GameActivity_t
ACT_DOTA_CAST_SUN_STRIKE_ORB = 1743

---@type GameActivity_t
ACT_DOTA_CAST_TORNADO = 1583

---@type GameActivity_t
ACT_DOTA_CAST_TORNADO_ORB = 1739

---@type GameActivity_t
ACT_DOTA_CAST_WILD_AXES_END = 1562

---@type GameActivity_t
ACT_DOTA_CENTAUR_STAMPEDE = 1611

---@type GameActivity_t
ACT_DOTA_CHANNEL_ABILITY_1 = 1520

---@type GameActivity_t
ACT_DOTA_CHANNEL_ABILITY_2 = 1521

---@type GameActivity_t
ACT_DOTA_CHANNEL_ABILITY_3 = 1522

---@type GameActivity_t
ACT_DOTA_CHANNEL_ABILITY_4 = 1523

---@type GameActivity_t
ACT_DOTA_CHANNEL_ABILITY_5 = 1524

---@type GameActivity_t
ACT_DOTA_CHANNEL_ABILITY_6 = 1525

---@type GameActivity_t
ACT_DOTA_CHANNEL_ABILITY_7 = 1600

---@type GameActivity_t
ACT_DOTA_CHANNEL_END_ABILITY_1 = 1526

---@type GameActivity_t
ACT_DOTA_CHANNEL_END_ABILITY_2 = 1527

---@type GameActivity_t
ACT_DOTA_CHANNEL_END_ABILITY_3 = 1528

---@type GameActivity_t
ACT_DOTA_CHANNEL_END_ABILITY_4 = 1529

---@type GameActivity_t
ACT_DOTA_CHANNEL_END_ABILITY_5 = 1530

---@type GameActivity_t
ACT_DOTA_CHANNEL_END_ABILITY_6 = 1531

---@type GameActivity_t
ACT_DOTA_CHILLING_TOUCH = 1673

---@type GameActivity_t
ACT_DOTA_COLD_FEET = 1671

---@type GameActivity_t
ACT_DOTA_CONSTANT_LAYER = 1532

---@type GameActivity_t
ACT_DOTA_CUSTOM_TOWER_ATTACK = 1734

---@type GameActivity_t
ACT_DOTA_CUSTOM_TOWER_DIE = 1736

---@type GameActivity_t
ACT_DOTA_CUSTOM_TOWER_HIGH_FIVE = 1757

---@type GameActivity_t
ACT_DOTA_CUSTOM_TOWER_IDLE = 1735

---@type GameActivity_t
ACT_DOTA_CUSTOM_TOWER_IDLE_RARE = 1755

---@type GameActivity_t
ACT_DOTA_CUSTOM_TOWER_TAUNT = 1756

---@type GameActivity_t
ACT_DOTA_DAGON = 1651

---@type GameActivity_t
ACT_DOTA_DEATH_BY_SNIPER = 1642

---@type GameActivity_t
ACT_DOTA_DEFEAT = 1592

---@type GameActivity_t
ACT_DOTA_DEFEAT_START = 1711

---@type GameActivity_t
ACT_DOTA_DIE = 1506

---@type GameActivity_t
ACT_DOTA_DIE_SPECIAL = 1548

---@type GameActivity_t
ACT_DOTA_DISABLED = 1509

---@type GameActivity_t
ACT_DOTA_DP_SPIRIT_SIPHON = 1712

---@type GameActivity_t
ACT_DOTA_EARTHSHAKER_TOTEM_ATTACK = 1570

---@type GameActivity_t
ACT_DOTA_ECHO_SLAM = 1539

---@type GameActivity_t
ACT_DOTA_ENFEEBLE = 1674

---@type GameActivity_t
ACT_DOTA_ES_STONE_CALLER = 1714

---@type GameActivity_t
ACT_DOTA_FATAL_BONDS = 1675

---@type GameActivity_t
ACT_DOTA_FLAIL = 1508

---@type GameActivity_t
ACT_DOTA_FLEE = 1685

---@type GameActivity_t
ACT_DOTA_FLINCH = 1507

---@type GameActivity_t
ACT_DOTA_FORCESTAFF_END = 1602

---@type GameActivity_t
ACT_DOTA_FRUSTRATION = 1630

---@type GameActivity_t
ACT_DOTA_FXANIM = 1709

---@type GameActivity_t
ACT_DOTA_GENERIC_CHANNEL_1 = 1728

---@type GameActivity_t
ACT_DOTA_GENERIC_CHANNEL_1_START = 1754

---@type GameActivity_t
ACT_DOTA_GESTURE_ACCENT = 1625

---@type GameActivity_t
ACT_DOTA_GESTURE_POINT = 1624

---@type GameActivity_t
ACT_DOTA_GREET = 1690

---@type GameActivity_t
ACT_DOTA_GREEVIL_BLINK_BONE = 1621

---@type GameActivity_t
ACT_DOTA_GREEVIL_CAST = 1617

---@type GameActivity_t
ACT_DOTA_GREEVIL_HOOK_END = 1620

---@type GameActivity_t
ACT_DOTA_GREEVIL_HOOK_START = 1619

---@type GameActivity_t
ACT_DOTA_GREEVIL_OVERRIDE_ABILITY = 1618

---@type GameActivity_t
ACT_DOTA_GS_INK_CREATURE = 1730

---@type GameActivity_t
ACT_DOTA_GS_SOUL_CHAIN = 1729

---@type GameActivity_t
ACT_DOTA_ICE_VORTEX = 1672

---@type GameActivity_t
ACT_DOTA_IDLE = 1500

---@type GameActivity_t
ACT_DOTA_IDLE_IMPATIENT = 1636

---@type GameActivity_t
ACT_DOTA_IDLE_IMPATIENT_SWORD_TAP = 1648

---@type GameActivity_t
ACT_DOTA_IDLE_RARE = 1501

---@type GameActivity_t
ACT_DOTA_IDLE_SLEEPING = 1622

---@type GameActivity_t
ACT_DOTA_IDLE_SLEEPING_END = 1639

---@type GameActivity_t
ACT_DOTA_INTRO = 1623

---@type GameActivity_t
ACT_DOTA_INTRO_LOOP = 1649

---@type GameActivity_t
ACT_DOTA_ITEM_DROP = 1697

---@type GameActivity_t
ACT_DOTA_ITEM_LOOK = 1628

---@type GameActivity_t
ACT_DOTA_ITEM_PICKUP = 1696

---@type GameActivity_t
ACT_DOTA_JAKIRO_LIQUIDFIRE_LOOP = 1575

---@type GameActivity_t
ACT_DOTA_JAKIRO_LIQUIDFIRE_START = 1574

---@type GameActivity_t
ACT_DOTA_KEZ_KATANA_IMPALE = 1770

---@type GameActivity_t
ACT_DOTA_KEZ_KATANA_IMPALE_FAST = 1771

---@type GameActivity_t
ACT_DOTA_KEZ_KATANA_ULT_CHAIN_A = 1767

---@type GameActivity_t
ACT_DOTA_KEZ_KATANA_ULT_CHAIN_B = 1768

---@type GameActivity_t
ACT_DOTA_KEZ_KATANA_ULT_END = 1769

---@type GameActivity_t
ACT_DOTA_KEZ_KATANA_ULT_START = 1766

---@type GameActivity_t
ACT_DOTA_KILLTAUNT = 1535

---@type GameActivity_t
ACT_DOTA_KINETIC_FIELD = 1679

---@type GameActivity_t
ACT_DOTA_LARGO_ULT_STRUM_FAIL = 1775

---@type GameActivity_t
ACT_DOTA_LARGO_ULT_STRUM_SUCCESS = 1774

---@type GameActivity_t
ACT_DOTA_LARGO_ULT_TOGGLE_OFF = 1778

---@type GameActivity_t
ACT_DOTA_LARGO_ULT_TOGGLE_ON = 1777

---@type GameActivity_t
ACT_DOTA_LASSO_LOOP = 1578

---@type GameActivity_t
ACT_DOTA_LEAP_STUN = 1658

---@type GameActivity_t
ACT_DOTA_LEAP_SWIPE = 1659

---@type GameActivity_t
ACT_DOTA_LIFESTEALER_ASSIMILATE = 1703

---@type GameActivity_t
ACT_DOTA_LIFESTEALER_EJECT = 1704

---@type GameActivity_t
ACT_DOTA_LIFESTEALER_INFEST = 1576

---@type GameActivity_t
ACT_DOTA_LIFESTEALER_INFEST_END = 1577

---@type GameActivity_t
ACT_DOTA_LIFESTEALER_OPEN_WOUNDS = 1567

---@type GameActivity_t
ACT_DOTA_LIFESTEALER_RAGE = 1566

---@type GameActivity_t
ACT_DOTA_LOADOUT = 1601

---@type GameActivity_t
ACT_DOTA_LOADOUT_RARE = 1683

---@type GameActivity_t
ACT_DOTA_LOOK_AROUND = 1643

---@type GameActivity_t
ACT_DOTA_MAGNUS_SKEWER_END = 1606

---@type GameActivity_t
ACT_DOTA_MAGNUS_SKEWER_START = 1605

---@type GameActivity_t
ACT_DOTA_MEDUSA_STONE_GAZE = 1607

---@type GameActivity_t
ACT_DOTA_MIDNIGHT_PULSE = 1676

---@type GameActivity_t
ACT_DOTA_MINI_TAUNT = 1681

---@type GameActivity_t
ACT_DOTA_MK_FUR_ARMY = 1722

---@type GameActivity_t
ACT_DOTA_MK_SPRING_CAST = 1723

---@type GameActivity_t
ACT_DOTA_MK_SPRING_END = 1719

---@type GameActivity_t
ACT_DOTA_MK_SPRING_SOAR = 1718

---@type GameActivity_t
ACT_DOTA_MK_STRIKE = 1715

---@type GameActivity_t
ACT_DOTA_MK_STRIKE_END = 1764

---@type GameActivity_t
ACT_DOTA_MK_TREE_END = 1721

---@type GameActivity_t
ACT_DOTA_MK_TREE_SOAR = 1720

---@type GameActivity_t
ACT_DOTA_MVP_SCREEN = 1776

---@type GameActivity_t
ACT_DOTA_NECRO_GHOST_SHROUD = 1724

---@type GameActivity_t
ACT_DOTA_NIAN_INTRO_LEAP = 1660

---@type GameActivity_t
ACT_DOTA_NIAN_PIN_END = 1657

---@type GameActivity_t
ACT_DOTA_NIAN_PIN_LOOP = 1656

---@type GameActivity_t
ACT_DOTA_NIAN_PIN_START = 1655

---@type GameActivity_t
ACT_DOTA_NIAN_PIN_TO_STUN = 1662

---@type GameActivity_t
ACT_DOTA_NIGHTSTALKER_TRANSITION = 1565

---@type GameActivity_t
ACT_DOTA_NOTICE = 1747

---@type GameActivity_t
ACT_DOTA_OVERRIDE_ABILITY_1 = 1516

---@type GameActivity_t
ACT_DOTA_OVERRIDE_ABILITY_2 = 1517

---@type GameActivity_t
ACT_DOTA_OVERRIDE_ABILITY_3 = 1518

---@type GameActivity_t
ACT_DOTA_OVERRIDE_ABILITY_4 = 1519

---@type GameActivity_t
ACT_DOTA_OVERRIDE_ARCANA = 1725

---@type GameActivity_t
ACT_DOTA_OVERRIDE_LOADOUT = 1751

---@type GameActivity_t
ACT_DOTA_PET_LEVEL = 1701

---@type GameActivity_t
ACT_DOTA_PET_WARD_OBSERVER = 1699

---@type GameActivity_t
ACT_DOTA_PET_WARD_SENTRY = 1700

---@type GameActivity_t
ACT_DOTA_PIERCE_THE_VEIL = 1760

---@type GameActivity_t
ACT_DOTA_POOF_END = 1603

---@type GameActivity_t
ACT_DOTA_PRESENT_ITEM = 1635

---@type GameActivity_t
ACT_DOTA_RATTLETRAP_BATTERYASSAULT = 1549

---@type GameActivity_t
ACT_DOTA_RATTLETRAP_HOOKSHOT_END = 1553

---@type GameActivity_t
ACT_DOTA_RATTLETRAP_HOOKSHOT_LOOP = 1552

---@type GameActivity_t
ACT_DOTA_RATTLETRAP_HOOKSHOT_START = 1551

---@type GameActivity_t
ACT_DOTA_RATTLETRAP_POWERCOGS = 1550

---@type GameActivity_t
ACT_DOTA_RAZE_1 = 1663

---@type GameActivity_t
ACT_DOTA_RAZE_2 = 1664

---@type GameActivity_t
ACT_DOTA_RAZE_3 = 1665

---@type GameActivity_t
ACT_DOTA_RELAX_END = 1610

---@type GameActivity_t
ACT_DOTA_RELAX_LOOP = 1609

---@type GameActivity_t
ACT_DOTA_RELAX_LOOP_END = 1634

---@type GameActivity_t
ACT_DOTA_RELAX_START = 1608

---@type GameActivity_t
ACT_DOTA_ROQUELAIRE_LAND = 1615

---@type GameActivity_t
ACT_DOTA_ROQUELAIRE_LAND_IDLE = 1616

---@type GameActivity_t
ACT_DOTA_RUN = 1502

---@type GameActivity_t
ACT_DOTA_RUN_RARE = 1761

---@type GameActivity_t
ACT_DOTA_SAND_KING_BURROW_IN = 1568

---@type GameActivity_t
ACT_DOTA_SAND_KING_BURROW_OUT = 1569

---@type GameActivity_t
ACT_DOTA_SHADOW_VAULT = 1765

---@type GameActivity_t
ACT_DOTA_SHAKE = 1687

---@type GameActivity_t
ACT_DOTA_SHALLOW_GRAVE = 1670

---@type GameActivity_t
ACT_DOTA_SHARPEN_WEAPON = 1637

---@type GameActivity_t
ACT_DOTA_SHARPEN_WEAPON_OUT = 1638

---@type GameActivity_t
ACT_DOTA_SHOPKEEPER_PET_INTERACT = 1695

---@type GameActivity_t
ACT_DOTA_SHRUG = 1633

---@type GameActivity_t
ACT_DOTA_SHUFFLE_L = 1749

---@type GameActivity_t
ACT_DOTA_SHUFFLE_R = 1750

---@type GameActivity_t
ACT_DOTA_SLARK_POUNCE = 1604

---@type GameActivity_t
ACT_DOTA_SLEEPING_END = 1626

---@type GameActivity_t
ACT_DOTA_SLIDE = 1726

---@type GameActivity_t
ACT_DOTA_SLIDE_LOOP = 1727

---@type GameActivity_t
ACT_DOTA_SPAWN = 1534

---@type GameActivity_t
ACT_DOTA_SPIRIT_BREAKER_CHARGE_END = 1594

---@type GameActivity_t
ACT_DOTA_SPIRIT_BREAKER_CHARGE_POSE = 1593

---@type GameActivity_t
ACT_DOTA_STARTLE = 1629

---@type GameActivity_t
ACT_DOTA_STATIC_STORM = 1680

---@type GameActivity_t
ACT_DOTA_SWIM = 1684

---@type GameActivity_t
ACT_DOTA_SWIM_IDLE = 1688

---@type GameActivity_t
ACT_DOTA_TAUNT = 1536

---@type GameActivity_t
ACT_DOTA_TAUNT_SNIPER = 1641

---@type GameActivity_t
ACT_DOTA_TAUNT_SPECIAL = 1752

---@type GameActivity_t
ACT_DOTA_TELEPORT = 1595

---@type GameActivity_t
ACT_DOTA_TELEPORT_COOP_END = 1693

---@type GameActivity_t
ACT_DOTA_TELEPORT_COOP_EXIT = 1694

---@type GameActivity_t
ACT_DOTA_TELEPORT_COOP_START = 1691

---@type GameActivity_t
ACT_DOTA_TELEPORT_COOP_WAIT = 1692

---@type GameActivity_t
ACT_DOTA_TELEPORT_END = 1596

---@type GameActivity_t
ACT_DOTA_TELEPORT_END_REACT = 1632

---@type GameActivity_t
ACT_DOTA_TELEPORT_REACT = 1631

---@type GameActivity_t
ACT_DOTA_TELEPORT_START = 1753

---@type GameActivity_t
ACT_DOTA_THIRST = 1537

---@type GameActivity_t
ACT_DOTA_THUNDER_STRIKE = 1678

---@type GameActivity_t
ACT_DOTA_TINKER_REARM1 = 1555

---@type GameActivity_t
ACT_DOTA_TINKER_REARM2 = 1556

---@type GameActivity_t
ACT_DOTA_TINKER_REARM3 = 1557

---@type GameActivity_t
ACT_DOTA_TRANSITION = 1731

---@type GameActivity_t
ACT_DOTA_TRANSITION_IDLE = 1759

---@type GameActivity_t
ACT_DOTA_TRICKS_END = 1713

---@type GameActivity_t
ACT_DOTA_TROT = 1686

---@type GameActivity_t
ACT_DOTA_UNDYING_DECAY = 1666

---@type GameActivity_t
ACT_DOTA_UNDYING_SOUL_RIP = 1667

---@type GameActivity_t
ACT_DOTA_UNDYING_TOMBSTONE = 1668

---@type GameActivity_t
ACT_DOTA_UNICYCLE = 1772

---@type GameActivity_t
ACT_DOTA_UNICYCLE_END = 1773

---@type GameActivity_t
ACT_DOTA_VERSUS = 1716

---@type GameActivity_t
ACT_DOTA_VICTORY = 1591

---@type GameActivity_t
ACT_DOTA_VICTORY_START = 1710

---@type GameActivity_t
ACT_DOTA_VIPER_DIVE = 1762

---@type GameActivity_t
ACT_DOTA_VIPER_DIVE_END = 1763

---@type GameActivity_t
ACT_DOTA_WAIT_IDLE = 1689

---@type GameActivity_t
ACT_DOTA_WEAVERBUG_ATTACH = 1561

---@type GameActivity_t
ACT_DOTA_WHEEL_LAYER = 1571

---@type GameActivity_t
ACT_DOTA_WHIRLING_AXES_RANGED = 1669

---@type GameActivity_t
ACT_MIRANA_LEAP_END = 1544

---@type GameActivity_t
ACT_STORM_SPIRIT_OVERLOAD_RUN_OVERRIDE = 1554

---@type GameActivity_t
ACT_TINY_AVALANCHE = 1558

---@type GameActivity_t
ACT_TINY_GROWL = 1560

---@type GameActivity_t
ACT_TINY_TOSS = 1559

---@type GameActivity_t
ACT_WAVEFORM_END = 1546

---@type GameActivity_t
ACT_WAVEFORM_START = 1545

---Server only.
---@alias attackfail integer

---@type attackfail
DOTA_ATTACK_RECORD_CANNOT_FAIL = 6

---@type attackfail
DOTA_ATTACK_RECORD_FAIL_BLOCKED_BY_OBSTRUCTION = 7

---@type attackfail
DOTA_ATTACK_RECORD_FAIL_NO = 0

---@type attackfail
DOTA_ATTACK_RECORD_FAIL_SOURCE_MISS = 2

---@type attackfail
DOTA_ATTACK_RECORD_FAIL_TARGET_EVADED = 3

---@type attackfail
DOTA_ATTACK_RECORD_FAIL_TARGET_INVULNERABLE = 4

---@type attackfail
DOTA_ATTACK_RECORD_FAIL_TARGET_OUT_OF_RANGE = 5

---@type attackfail
DOTA_ATTACK_RECORD_FAIL_TERRAIN_MISS = 1

---Server only.
---@alias quest_text_replace_values_t integer

---@type quest_text_replace_values_t
QUEST_NUM_TEXT_REPLACE_VALUES = 4

---@type quest_text_replace_values_t
QUEST_TEXT_REPLACE_VALUE_CURRENT_VALUE = 0

---@type quest_text_replace_values_t
QUEST_TEXT_REPLACE_VALUE_REWARD = 3

---@type quest_text_replace_values_t
QUEST_TEXT_REPLACE_VALUE_ROUND = 2

---@type quest_text_replace_values_t
QUEST_TEXT_REPLACE_VALUE_TARGET_VALUE = 1

---Server only.
---@alias subquest_text_replace_values_t integer

---@type subquest_text_replace_values_t
SUBQUEST_NUM_TEXT_REPLACE_VALUES = 2

---@type subquest_text_replace_values_t
SUBQUEST_TEXT_REPLACE_VALUE_CURRENT_VALUE = 0

---@type subquest_text_replace_values_t
SUBQUEST_TEXT_REPLACE_VALUE_TARGET_VALUE = 1
