---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Add temporary vision for a given team, returns a ViewerID ( nTeamID, vLocation, flRadius, flDuration, bObstructedVision)
---Server only.
---@param int_1 integer
---@param unknown_2 any
---@param float_3 number
---@param float_4 number
---@param bool_5 boolean
---@return integer
function AddFOWViewer(int_1, unknown_2, float_3, float_4, bool_5) end

---Damage an npc.
---Server only.
---@param handle_1 handle
---@return number
function ApplyDamage(handle_1) end

---CenterCameraOnUnit( nPlayerId, hUnit ): Centers each players' camera on a unit.
---Server only.
---@param int_1 integer
---@param handle_2 handle
function CenterCameraOnUnit(int_1, handle_2) end

---( teamNumber )
---Server only.
---@param int_1 integer
function ClearTeamCustomHealthbarColor(int_1) end

---(hInflictor, hAttacker, flDamage) - Allocate a damageinfo object, used as an argument to TakeDamage(). Call DestroyDamageInfo( hInfo ) to free the object.
---Server only.
---@param handle_1 handle
---@param handle_2 handle
---@param Vector_3 Vector
---@param unknown_4 any
---@param float_5 number
---@param int_6 integer
---@return handle
function CreateDamageInfo(handle_1, handle_2, Vector_3, unknown_4, float_5, int_6) end

---Creates a DOTA hero by its dota_npc_units.txt name and sets it as the given player's controlled hero
---Server only.
---@param string_1 string
---@param handle_2 handle
---@return handle
function CreateHeroForPlayer(string_1, handle_2) end

---Create illusions of the passed hero that belong to passed unit using passed modifier data. ( hOwner, hHeroToCopy, hModiiferKeys, nNumIllusions, nPadding, bScramblePosition, bFindClearSpace )
---Supported keys:
---outgoing_damage
---incoming_damage
---bounty_base
---bounty_growth
---outgoing_damage_structure
---outgoing_damage_roshan
---Server only.
---@param handle_1 handle
---@param handle_2 handle
---@param handle_3 handle
---@param int_4 integer
---@param int_5 integer
---@param bool_6 boolean
---@param bool_7 boolean
---@return table
function CreateIllusions(handle_1, handle_2, handle_3, int_4, int_5, bool_6, bool_7) end

---Create a DOTA item
---Server only.
---@param string_1 string
---@param handle_2 handle
---@param handle_3 handle
---@return handle
function CreateItem(string_1, handle_2, handle_3) end

---Create a physical item at a given location, can start in air (but doesn't clear a space)
---Server only.
---@param unknown_1 any
---@param handle_2 handle
---@return handle
function CreateItemOnPositionForLaunch(unknown_1, handle_2) end

---Create a physical item at a given location
---Server only.
---@param unknown_1 any
---@param handle_2 handle
---@return handle
function CreateItemOnPositionSync(unknown_1, handle_2) end

---Create a modifier not associated with an NPC. ( hCaster, hAbility, modifierName, paramTable, vOrigin, nTeamNumber, bPhantomBlocker )
---Server only.
---@param handle_1 handle
---@param handle_2 handle
---@param string_3 string
---@param handle_4 handle
---@param unknown_5 any
---@param int_6 integer
---@param bool_7 boolean
---@return handle
function CreateModifierThinker(handle_1, handle_2, string_3, handle_4, unknown_5, int_6, bool_7) end

---Create a rune of the specified type (vLocation, iRuneType).
---Server only.
---@param unknown_1 any
---@param int_2 integer
---@return handle
function CreateRune(unknown_1, int_2) end

---Create a scene entity to play the specified scene.
---Server only.
---@param string_1 string
---@return handle
function CreateSceneEntity(string_1) end

---Create a temporary tree, uses a default tree model. (vLocation, flDuration).
---Server only.
---@param unknown_1 any
---@param float_2 number
---@return handle
function CreateTempTree(unknown_1, float_2) end

---Create a temporary tree, specifying the tree model name. (vLocation, flDuration, szModelName).
---Server only.
---@param unknown_1 any
---@param float_2 number
---@param string_3 string
---@return handle
function CreateTempTreeWithModel(unknown_1, float_2, string_3) end

---CreateTrigger( vecMin, vecMax ) : Creates and returns an AABB trigger
---Server only.
---@param unknown_1 any
---@param Vector_2 Vector
---@param Vector_3 Vector
---@return handle
function CreateTrigger(unknown_1, Vector_2, Vector_3) end

---CreateTriggerRadiusApproximate( vecOrigin, flRadius ) : Creates and returns an AABB trigger thats bigger than the radius provided
---Server only.
---@param unknown_1 any
---@param float_2 number
---@return handle
function CreateTriggerRadiusApproximate(unknown_1, float_2) end

---Creates a DOTA unit by its dota_npc_units.txt name
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param bool_3 boolean
---@param handle_4 handle
---@param handle_5 handle
---@param int_6 integer
---@return handle
function CreateUnitByName(string_1, unknown_2, bool_3, handle_4, handle_5, int_6) end

---Creates a DOTA unit by its dota_npc_units.txt name
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param bool_3 boolean
---@param handle_4 handle
---@param handle_5 handle
---@param int_6 integer
---@param handle_7 handle
---@return integer
function CreateUnitByNameAsync(string_1, unknown_2, bool_3, handle_4, handle_5, int_6, handle_7) end

---Creates a DOTA unit by its dota_npc_units.txt name from a table of entity key values and a position to spawn at.
---Server only.
---@param handle_1 handle
---@param unknown_2 any
---@return handle
function CreateUnitFromTable(handle_1, unknown_2) end

---Spawn a .vmap at the target location.
---Server only.
---@param string_1 string
---@param Vector_2 Vector
---@param bool_3 boolean
---@param handle_4 handle
---@param handle_5 handle
---@param handle_6 handle
---@return integer
function DOTA_SpawnMapAtPosition(string_1, Vector_2, bool_3, handle_4, handle_5, handle_6) end

---Changes the team of the hero
---Server only.
---@param handle_1 handle
function DebugChangeTeam(handle_1) end

---Creates a unit with a specified hero variant, controllable by the specified player.
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param int_3 integer
---@param int_4 integer
---@param bool_5 boolean
---@param handle_6 handle
---@return integer
function DebugCreateHeroWithVariant(handle_1, string_2, int_3, int_4, bool_5, handle_6) end

---Creates a test unit controllable by the specified player.
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param int_3 integer
---@param bool_4 boolean
---@param handle_5 handle
---@return integer
function DebugCreateUnit(handle_1, string_2, int_3, bool_4, handle_5) end

---Free a damageinfo object that was created with CreateDamageInfo().
---Server only.
---@param handle_1 handle
function DestroyDamageInfo(handle_1) end

---Kick a specific player from the game
---Server only.
---@param int_1 integer
---@param bool_2 boolean
function DisconnectClient(int_1, bool_2) end

---(hAttacker, hTarget, hAbility, fDamage, fRadius, effectName)
---Server only.
---@param handle_1 handle
---@param handle_2 handle
---@param handle_3 handle
---@param float_4 number
---@param float_5 number
---@param float_6 number
---@param float_7 number
---@param string_8 string
---@return integer
function DoCleaveAttack(handle_1, handle_2, handle_3, float_4, float_5, float_6, float_7, string_8) end

---#EntFire:Generate and entity i/o event
---Server only.
---@param string_1 string
---@param string_2 string
---@param string_3 string
---@param float_4 number
---@param handle_5 handle
---@param handle_6 handle
function DoEntFire(string_1, string_2, string_3, float_4, handle_5, handle_6) end

---#EntFireByHandle:Generate and entity i/o event
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param string_3 string
---@param float_4 number
---@param handle_5 handle
---@param handle_6 handle
function DoEntFireByInstanceHandle(handle_1, string_2, string_3, float_4, handle_5, handle_6) end

---Server only.
---@param Vector_1 Vector
---@param Vector_2 Vector
---@return number
function DotProduct(Vector_1, Vector_2) end

---Drop a neutral item for the team of the hero at the given tier.
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param handle_3 handle
---@param int_4 integer
---@param bool_5 boolean
---@return handle
function DropNeutralItemAtPositionForHero(string_1, unknown_2, handle_3, int_4, bool_5) end

---Drop a neutral item for the team of the hero at the given tier.
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param handle_3 handle
---@param int_4 integer
---@param bool_5 boolean
---@param Vector_6 Vector
---@return handle
function DropNeutralItemAtPositionForHeroWithOffset(string_1, unknown_2, handle_3, int_4, bool_5, Vector_6) end

---Emit an announcer sound for all players.
---Server only.
---@param string_1 string
function EmitAnnouncerSound(string_1) end

---Emit an announcer sound for a player.
---Server only.
---@param string_1 string
---@param int_2 integer
function EmitAnnouncerSoundForPlayer(string_1, int_2) end

---Emit an announcer sound for a team.
---Server only.
---@param string_1 string
---@param int_2 integer
function EmitAnnouncerSoundForTeam(string_1, int_2) end

---Emit an announcer sound for a team at a specific location.
---Server only.
---@param string_1 string
---@param int_2 integer
---@param unknown_3 any
function EmitAnnouncerSoundForTeamOnLocation(string_1, int_2, unknown_3) end

---Play named sound for all players
---Server only.
---@param string_1 string
function EmitGlobalSound(string_1) end

---Emit a sound on an entity for only a specific player
---Server only.
---@param string_1 string
---@param handle_2 handle
---@param int_3 integer
function EmitSoundOnEntityForPlayer(string_1, handle_2, int_3) end

---Emit a sound on a location from a unit, only for players allied with that unit (vLocation, soundName, hCaster
---Server only.
---@param unknown_1 any
---@param string_2 string
---@param handle_3 handle
function EmitSoundOnLocationForAllies(unknown_1, string_2, handle_3) end

---Emit a sound on a location for only a specific player
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param int_3 integer
function EmitSoundOnLocationForPlayer(string_1, unknown_2, int_3) end

---Emit a sound on a location from a unit. (vLocation, soundName, hCaster).
---Server only.
---@param unknown_1 any
---@param string_2 string
---@param handle_3 handle
function EmitSoundOnLocationWithCaster(unknown_1, string_2, handle_3) end

---Issue an order from a script table
---Server only.
---@param handle_1 handle
function ExecuteOrderFromTable(handle_1) end

---Finds a clear random position around a given target unit, using the target unit's padded collision radius.
---Server only.
---@param handle_1 handle
---@param handle_2 handle
---@param int_3 integer
---@return boolean
function FindClearRandomPositionAroundUnit(handle_1, handle_2, int_3) end

---Place a unit somewhere not already occupied.
---Server only.
---@param handle_1 handle
---@param unknown_2 any
---@param bool_3 boolean
---@return boolean
function FindClearSpaceForUnit(handle_1, unknown_2, bool_3) end

---Find a spawn point for the given team.
---Server only.
---@param int_1 integer
---@return handle
function FindSpawnEntityForTeam(int_1) end

---Find units that intersect the given line with the given flags.
---Server only.
---@param int_1 integer
---@param unknown_2 any
---@param unknown_3 any
---@param handle_4 handle
---@param float_5 number
---@param int_6 integer
---@param int_7 integer
---@param int_8 integer
---@return table
function FindUnitsInLine(int_1, unknown_2, unknown_3, handle_4, float_5, int_6, int_7, int_8) end

---Finds the units in a given radius with the given flags.
---Server only.
---@param int_1 integer
---@param unknown_2 any
---@param handle_3 handle
---@param float_4 number
---@param int_5 integer
---@param int_6 integer
---@param int_7 integer
---@param int_8 integer
---@param bool_9 boolean
---@return table
function FindUnitsInRadius(int_1, unknown_2, handle_3, float_4, int_5, int_6, int_7, int_8, bool_9) end

---Returns a location for the unit that is not already occupied.
---Server only.
---@param handle_1 handle
---@param unknown_2 any
---@return any
function GetClearSpaceForUnit(handle_1, unknown_2) end

---( version )
---Server only.
---@param string_1 string
---@return string
function GetDedicatedServerKey(string_1) end

---( version )
---Server only.
---@param string_1 string
---@return string
function GetDedicatedServerKeyV2(string_1) end

---( version )
---Server only.
---@param string_1 string
---@return string
function GetDedicatedServerKeyV3(string_1) end

---Get the enity index for a tree id specified as the entindex_target of a DOTA_UNIT_ORDER_CAST_TARGET_TREE.
---Server only.
---@param unsigned_1 integer
---@return integer
function GetEntityIndexForTreeId(unsigned_1) end

---Server only.
---@param unknown_1 any
---@param handle_2 handle
---@return number
function GetGroundHeight(unknown_1, handle_2) end

---Returns the supplied position moved to the ground. Second parameter is an NPC for measuring movement collision hull offset.
---Server only.
---@param unknown_1 any
---@param handle_2 handle
---@return any
function GetGroundPosition(unknown_1, handle_2) end

---Get the cost of an item by name.
---Server only.
---@param string_1 string
---@return integer
function GetItemCost(string_1) end

---Server only.
---@param int_1 integer
---@param int_2 integer
---@return integer
function GetItemDefOwnedCount(int_1, int_2) end

---Server only.
---@param int_1 integer
---@param int_2 integer
---@return integer
function GetItemDefQuantity(int_1, int_2) end

---( )
---Server only.
---@return table
function GetLobbyEventGameDetails() end

---Given the item tier and the team, roll for the name of a valid neutral item drop, considering previous drops and consumables.
---Server only.
---@param int_1 integer
---@param int_2 integer
---@return string
function GetPotentialNeutralItemDrop(int_1, int_2) end

---Get the current real world date
---Server only.
---@return string
function GetSystemDate() end

---Get the current real world time
---Server only.
---@return string
function GetSystemTime() end

---Get system time in milliseconds
---Server only.
---@return number
function GetSystemTimeMS() end

---Server only.
---@param int_1 integer
---@param int_2 integer
---@param int_3 integer
---@param unknown_4 any
---@param int_5 integer
---@param int_6 integer
---@param int_7 integer
---@return any
function GetTargetAOELocation(int_1, int_2, int_3, unknown_4, int_5, int_6, int_7) end

---Server only.
---@param int_1 integer
---@param int_2 integer
---@param int_3 integer
---@param unknown_4 any
---@param int_5 integer
---@param int_6 integer
---@param int_7 integer
---@return any
function GetTargetLinearLocation(int_1, int_2, int_3, unknown_4, int_5, int_6, int_7) end

---( int teamID )
---Server only.
---@param int_1 integer
---@return integer
function GetTeamHeroKills(int_1) end

---( int teamID )
---Server only.
---@param int_1 integer
---@return string
function GetTeamName(int_1) end

---Given and entity index of a tree, get the tree id for use for use with with unit orders.
---Server only.
---@param int_1 integer
---@return integer
function GetTreeIdForEntityIndex(int_1) end

---Gets the world's maximum X position.
---Server only.
---@return number
function GetWorldMaxX() end

---Gets the world's maximum Y position.
---Server only.
---@return number
function GetWorldMaxY() end

---Gets the world's minimum X position.
---Server only.
---@return number
function GetWorldMinX() end

---Gets the world's minimum Y position.
---Server only.
---@return number
function GetWorldMinY() end

---Get amount of XP required to reach the next level.
---Server only.
---@param int_1 integer
---@return integer
function GetXPNeededToReachNextLevel(int_1) end

---Max out a hero's level and give them all appropriate abilities and talents.
---Server only.
---@param handle_1 handle
function HeroMaxLevel(handle_1) end

---Ask fog of war if a location is visible to a certain team (nTeamNumber, vLocation).
---Server only.
---@param int_1 integer
---@param unknown_2 any
---@return boolean
function IsLocationVisible(int_1, unknown_2) end

---Is this entity a mango tree? (hEntity).
---Server only.
---@param handle_1 handle
---@return boolean
function IsMangoTree(handle_1) end

---Returns true if the unit is in a valid position in the gridnav.
---Server only.
---@param handle_1 handle
---@return boolean
function IsUnitInValidPosition(handle_1) end

---Set the limit on the pathfinding search space.
---Server only.
---@param float_1 number
function LimitPathingSearchDepth(float_1) end

---Start a minimap event. (nTeamID, hEntity, nXCoord, nYCoord, nEventType, nEventDuration).
---Server only.
---@param int_1 integer
---@param handle_2 handle
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
---@param int_6 integer
function MinimapEvent(int_1, handle_2, int_3, int_4, int_5, int_6) end

---Pause or unpause the game.
---Server only.
---@param bool_1 boolean
function PauseGame(bool_1) end

---Asynchronously precaches a DOTA item by its dota_npc_items.txt name, provides a callback when it's finished.
---Server only.
---@param string_1 string
---@param handle_2 handle
function PrecacheItemByNameAsync(string_1, handle_2) end

---Precaches a DOTA item by its dota_npc_items.txt name
---Server only.
---@param string_1 string
---@param handle_2 handle
function PrecacheItemByNameSync(string_1, handle_2) end

---( modelName, context ) - Manually precache a single model
---Server only.
---@param string_1 string
---@param handle_2 handle
function PrecacheModel(string_1, handle_2) end

---Manually precache a single resource
---Server only.
---@param string_1 string
---@param string_2 string
---@param handle_3 handle
function PrecacheResource(string_1, string_2, handle_3) end

---Asynchronously precaches a DOTA unit by its dota_npc_units.txt name, provides a callback when it's finished.
---Server only.
---@param string_1 string
---@param handle_2 handle
---@param int_3 integer
function PrecacheUnitByNameAsync(string_1, handle_2, int_3) end

---Precaches a DOTA unit by its dota_npc_units.txt name
---Server only.
---@param string_1 string
---@param handle_2 handle
---@param int_3 integer
function PrecacheUnitByNameSync(string_1, handle_2, int_3) end

---Precaches a DOTA unit from a table of entity key values.
---Server only.
---@param handle_1 handle
---@param handle_2 handle
function PrecacheUnitFromTableAsync(handle_1, handle_2) end

---Precaches a DOTA unit from a table of entity key values.
---Server only.
---@param handle_1 handle
---@param handle_2 handle
function PrecacheUnitFromTableSync(handle_1, handle_2) end

---Get a random float within a range
---Server only.
---@param float_1 number
---@param float_2 number
---@return number
function RandomFloat(float_1, float_2) end

---Get a random 2D vector of the given length.
---Server only.
---@param float_1 number
---@return Vector
function RandomVector(float_1) end

---Record in player resources that a new neutral item has been created, if it hasn't already been, and show a toast.
---Server only.
---@param handle_1 handle
---@param handle_2 handle
---@param int_3 integer
function RecordNeutralItemEarned(handle_1, handle_2, int_3) end

---Register a custom animation script to run when a model loads
---Server only.
---@param string_1 string
---@param string_2 string
function RegisterCustomAnimationScriptForModel(string_1, string_2) end

---Remove temporary vision for a given team ( nTeamID, nViewerID )
---Server only.
---@param int_1 integer
---@param int_2 integer
function RemoveFOWViewer(int_1, int_2) end

---Check and fix units that have been assigned a position inside collision radius of other NPCs.
---Server only.
---@param unknown_1 any
---@param float_2 number
function ResolveNPCPositions(unknown_1, float_2) end

---(int nPct)
---Server only.
---@param int_1 integer
---@return boolean
function RollPercentage(int_1) end

---( chance, pseudo random id, unit.
---Server only.
---@param unsigned_1 integer
---@param int_2 integer
---@param handle_3 handle
---@return boolean
function RollPseudoRandomPercentage(unsigned_1, int_2, handle_3) end

---Have Entity say string, and teamOnly or not
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param bool_3 boolean
function Say(handle_1, string_2, bool_3) end

---RemapValClamped
---Server only.
---@param float_1 number
---@param float_2 number
---@param float_3 number
---@param float_4 number
---@param float_5 number
---@return number
function Script_RemapValClamped(float_1, float_2, float_3, float_4, float_5) end

---( DOTAPlayer sendToPlayer, int iMessageType, Entity targetEntity, int iValue, DOTAPlayer sourcePlayer ) - sendToPlayer and sourcePlayer can be nil - iMessageType is one of OVERHEAD_ALERT_*
---Server only.
---@param handle_1 handle
---@param int_2 integer
---@param handle_3 handle
---@param int_4 integer
---@param handle_5 handle
function SendOverheadEventMessage(handle_1, int_2, handle_3, int_4, handle_5) end

---Send a string to the console as a server command
---Server only.
---@param string_1 string
function SendToServerConsole(string_1) end

---( teamNumber, r, g, b )
---Server only.
---@param int_1 integer
---@param int_2 integer
---@param int_3 integer
---@param int_4 integer
function SetTeamCustomHealthbarColor(int_1, int_2, int_3, int_4) end

---( const char *pszMessage, PlayerID_t nPlayerID, int nValue, float flTime ) - Supports localized strings - %s1 = PlayerName, %s2 = Value, %s3 = TeamName
---Server only.
---@param string_1 string
---@param int_2 integer
---@param int_3 integer
---@param float_4 number
function ShowCustomHeaderMessage(string_1, int_2, int_3, float_4) end

---Show a generic popup dialog for all players.
---Server only.
---@param string_1 string
---@param string_2 string
---@param string_3 string
---@param string_4 string
---@param int_5 integer
function ShowGenericPopup(string_1, string_2, string_3, string_4, int_5) end

---Show a generic popup dialog to a specific player.
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param string_3 string
---@param string_4 string
---@param string_5 string
---@param int_6 integer
function ShowGenericPopupToPlayer(handle_1, string_2, string_3, string_4, string_5, int_6) end

---Print a hud message on all clients
---Server only.
---@param string_1 string
function ShowMessage(string_1) end

---(VectorWS vOrigin, float flRadius )
---Server only.
---@param unknown_1 any
---@param float_2 number
---@return handle
function SpawnDOTAShopTriggerRadiusApproximate(unknown_1, float_2) end

---Spawn an effigy of the target unit.
---Server only.
---@param string_1 string
---@param int_2 integer
---@param unknown_3 any
---@param Vector_4 Vector
---@param float_5 number
---@param float_6 number
---@param int_7 integer
---@return handle
function SpawnEffigyOfUnitOrModel(string_1, int_2, unknown_3, Vector_4, float_5, float_6, int_7) end

---Spawn a mango tree ( vPos, nTeam, flDuration, flMangoInterval, nInitialMangoes )
---Server only.
---@param unknown_1 any
---@param int_2 integer
---@param float_3 number
---@param float_4 number
---@param int_5 integer
---@return handle
function SpawnMangoTree(unknown_1, int_2, float_3, float_4, int_5) end

---Stop named sound for all players
---Server only.
---@param string_1 string
function StopGlobalSound(string_1) end

---Sends colored text to one client.
---Server only.
---@param int_1 integer
---@param string_2 string
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
---@param int_6 integer
function UTIL_MessageText(int_1, string_2, int_3, int_4, int_5, int_6) end

---Sends colored text to all clients.
---Server only.
---@param string_1 string
---@param int_2 integer
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
function UTIL_MessageTextAll(string_1, int_2, int_3, int_4, int_5) end

---Sends colored text to all clients. (Valid context keys: player_id, value, team_id)
---Server only.
---@param string_1 string
---@param int_2 integer
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
---@param handle_6 handle
function UTIL_MessageTextAll_WithContext(string_1, int_2, int_3, int_4, int_5, handle_6) end

---Sends colored text to one client. (Valid context keys: player_id, value, team_id)
---Server only.
---@param int_1 integer
---@param string_2 string
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
---@param int_6 integer
---@param handle_7 handle
function UTIL_MessageText_WithContext(int_1, string_2, int_3, int_4, int_5, int_6, handle_7) end

---Clear all message text on one client.
---Server only.
---@param int_1 integer
function UTIL_ResetMessageText(int_1) end

---Clear all message text from all clients.
---Server only.
function UTIL_ResetMessageTextAll() end

---( hEventPointData )
---Server only.
---@param handle_1 handle
function UpdateEventPoints(handle_1) end

---Server only.
---@param Vector_1 Vector
---@return QAngle
function VectorAngles(Vector_1) end
