---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
DOTA_CONNECTION_STATE_ABANDONED = 4

---Server only.
DOTA_CONNECTION_STATE_CONNECTED = 2

---Server only.
DOTA_CONNECTION_STATE_DISCONNECTED = 3

---Server only.
DOTA_CONNECTION_STATE_FAILED = 6

---Server only.
DOTA_CONNECTION_STATE_LOADING = 5

---Server only.
DOTA_CONNECTION_STATE_NOT_YET_CONNECTED = 1

---Server only.
DOTA_CONNECTION_STATE_UNKNOWN = 0

---Server only.
DOTA_GC_TEAM_BAD_GUYS = 1

---Server only.
DOTA_GC_TEAM_BROADCASTER = 2

---Server only.
DOTA_GC_TEAM_CUSTOM_1 = 6

---Server only.
DOTA_GC_TEAM_CUSTOM_2 = 7

---Server only.
DOTA_GC_TEAM_CUSTOM_3 = 8

---Server only.
DOTA_GC_TEAM_CUSTOM_4 = 9

---Server only.
DOTA_GC_TEAM_CUSTOM_5 = 10

---Server only.
DOTA_GC_TEAM_CUSTOM_6 = 11

---Server only.
DOTA_GC_TEAM_CUSTOM_7 = 12

---Server only.
DOTA_GC_TEAM_CUSTOM_8 = 13

---Server only.
DOTA_GC_TEAM_GOOD_GUYS = 0

---Server only.
DOTA_GC_TEAM_NEUTRALS = 14

---Server only.
DOTA_GC_TEAM_NOTEAM = 5

---Server only.
DOTA_GC_TEAM_PLAYER_POOL = 4

---Server only.
DOTA_GC_TEAM_SPECTATOR = 3

---Server only.
DOTA_ITEM_INVENTORY_SIZE = 9

---Server only.
DOTA_ITEM_MAX = 25

---Server only.
DOTA_ITEM_NEUTRAL_ACTIVE_SLOT = 16

---Server only.
DOTA_ITEM_NEUTRAL_PASSIVE_SLOT = 17

---Server only.
DOTA_ITEM_STASH_MAX = 15

---Server only.
DOTA_ITEM_STASH_MIN = 9

---Server only.
DOTA_ITEM_STASH_SIZE = 6

---Server only.
DOTA_ITEM_TP_SCROLL = 15

---Server only.
DOTA_ITEM_TRANSIENT_CAST_ITEM = 26

---Server only.
DOTA_ITEM_TRANSIENT_ITEM = 23

---Server only.
DOTA_ITEM_TRANSIENT_RECIPE = 24

---Server only.
DOTA_RUNE_STATUS_AVAILABLE = 1

---Server only.
DOTA_RUNE_STATUS_MISSING = 2

---Server only.
DOTA_RUNE_STATUS_UNKNOWN = 0

---Server only.
DOTA_SHOWGENERICPOPUP_SHOW_NO_OTHER_DIALOGS = 2

---Server only.
DOTA_SHOWGENERICPOPUP_TINT_SCREEN = 1

---Server only.
DOTA_UNIT_ORDER_ATTACK_MOVE = 3

---Server only.
DOTA_UNIT_ORDER_ATTACK_TARGET = 4

---Server only.
DOTA_UNIT_ORDER_BUYBACK = 23

---Server only.
DOTA_UNIT_ORDER_CAST_NO_TARGET = 8

---Server only.
DOTA_UNIT_ORDER_CAST_POSITION = 5

---Server only.
DOTA_UNIT_ORDER_CAST_RIVER_PAINT = 35

---Server only.
DOTA_UNIT_ORDER_CAST_RUNE = 26

---Server only.
DOTA_UNIT_ORDER_CAST_TARGET = 6

---Server only.
DOTA_UNIT_ORDER_CAST_TARGET_TREE = 7

---Server only.
DOTA_UNIT_ORDER_CAST_TOGGLE = 9

---Server only.
DOTA_UNIT_ORDER_CAST_TOGGLE_ALT = 40

---Server only.
DOTA_UNIT_ORDER_CAST_TOGGLE_AUTO = 20

---Server only.
DOTA_UNIT_ORDER_CONSUME_ITEM = 41

---Server only.
DOTA_UNIT_ORDER_CONTINUE = 33

---Server only.
DOTA_UNIT_ORDER_DISASSEMBLE_ITEM = 18

---Server only.
DOTA_UNIT_ORDER_DROP_ITEM = 12

---Server only.
DOTA_UNIT_ORDER_DROP_ITEM_AT_FOUNTAIN = 37

---Server only.
DOTA_UNIT_ORDER_EJECT_ITEM_FROM_STASH = 25

---Server only.
DOTA_UNIT_ORDER_GIVE_ITEM = 13

---Server only.
DOTA_UNIT_ORDER_GLYPH = 24

---Server only.
DOTA_UNIT_ORDER_HOLD_POSITION = 10

---Server only.
DOTA_UNIT_ORDER_MOVE_ITEM = 19

---Server only.
DOTA_UNIT_ORDER_MOVE_RELATIVE = 39

---Server only.
DOTA_UNIT_ORDER_MOVE_TO_DIRECTION = 28

---Server only.
DOTA_UNIT_ORDER_MOVE_TO_POSITION = 1

---Server only.
DOTA_UNIT_ORDER_MOVE_TO_TARGET = 2

---Server only.
DOTA_UNIT_ORDER_NONE = 0

---Server only.
DOTA_UNIT_ORDER_PATROL = 29

---Server only.
DOTA_UNIT_ORDER_PICKUP_ITEM = 14

---Server only.
DOTA_UNIT_ORDER_PICKUP_RUNE = 15

---Server only.
DOTA_UNIT_ORDER_PING_ABILITY = 27

---Server only.
DOTA_UNIT_ORDER_PREGAME_ADJUST_ITEM_ASSIGNMENT = 36

---Server only.
DOTA_UNIT_ORDER_PURCHASE_ITEM = 16

---Server only.
DOTA_UNIT_ORDER_RADAR = 31

---Server only.
DOTA_UNIT_ORDER_SELL_ITEM = 17

---Server only.
DOTA_UNIT_ORDER_SET_ITEM_COMBINE_LOCK = 32

---Server only.
DOTA_UNIT_ORDER_SET_ITEM_MARK_FOR_SELL = 42

---Server only.
DOTA_UNIT_ORDER_STOP = 21

---Server only.
DOTA_UNIT_ORDER_TAKE_ITEM_FROM_NEUTRAL_ITEM_STASH = 38

---Server only.
DOTA_UNIT_ORDER_TAUNT = 22

---Server only.
DOTA_UNIT_ORDER_TRAIN_ABILITY = 11

---Server only.
DOTA_UNIT_ORDER_VECTOR_TARGET_CANCELED = 34

---Server only.
DOTA_UNIT_ORDER_VECTOR_TARGET_POSITION = 30

---Server only.
EF_NODRAW = 32

---Server only.
OVERHEAD_ALERT_AEGIS = 26

---Server only.
OVERHEAD_ALERT_BLOCK = 8

---Server only.
OVERHEAD_ALERT_BLOCKED = 21

---Server only.
OVERHEAD_ALERT_BONUS_POISON_DAMAGE = 9

---Server only.
OVERHEAD_ALERT_BONUS_PURE_DAMAGE = 28

---Server only.
OVERHEAD_ALERT_BONUS_SPELL_DAMAGE = 4

---Server only.
OVERHEAD_ALERT_CRITICAL = 2

---Server only.
OVERHEAD_ALERT_DAMAGE = 6

---Server only.
OVERHEAD_ALERT_DEADLY_BLOW = 24

---Server only.
OVERHEAD_ALERT_DEATH = 20

---Server only.
OVERHEAD_ALERT_DENY = 1

---Server only.
OVERHEAD_ALERT_DISABLE_RESIST = 19

---Server only.
OVERHEAD_ALERT_DISPEL = 27

---Server only.
OVERHEAD_ALERT_EVADE = 7

---Server only.
OVERHEAD_ALERT_FORCE_MISS = 25

---Server only.
OVERHEAD_ALERT_GOLD = 0

---Server only.
OVERHEAD_ALERT_HEAL = 10

---Server only.
OVERHEAD_ALERT_INCOMING_DAMAGE = 17

---Server only.
OVERHEAD_ALERT_ITEM_RECEIVED = 22

---Server only.
OVERHEAD_ALERT_MAGICAL_BLOCK = 16

---Server only.
OVERHEAD_ALERT_MANA_ADD = 11

---Server only.
OVERHEAD_ALERT_MANA_LOSS = 12

---Server only.
OVERHEAD_ALERT_MISS = 5

---Server only.
OVERHEAD_ALERT_OUTGOING_DAMAGE = 18

---Server only.
OVERHEAD_ALERT_SHARD = 23

---Server only.
OVERHEAD_ALERT_XP = 3

---Server only.
function PrecacheUnitByNameAsync_Engine(...) end

---Server only.
function PrecacheUnitByNameSync_Engine(...) end

---Server only.
SERVER_DLL = 1
