---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@type CCustomGameEventManager
CustomGameEventManager = nil

---Server only.
---@type CDOTA_CustomUIManager
CustomUI = nil

---Server only.
---@type CScriptHeroList
HeroList = nil

---Server only.
---@type CDOTA_PlayerResource
PlayerResource = nil

---Server only.
---@type CDOTATutorial
Tutorial = nil

---Server only.
---@type CDOTAVoteSystem
VoteSystem = nil
