---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CBaseCombatCharacter : CBaseAnimatingOverlay
CBaseCombatCharacter = {}

---Server only.
function CBaseCombatCharacter:IsNull(...) end
