---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CBasePlayerController : CBaseEntity
CBasePlayerController = {}

---GetPawn() : Returns the pawn for this controller
---Server only.
---@return handle
function CBasePlayerController:GetPawn() end

---Server only.
function CBasePlayerController:IsNull(...) end
