---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CBaseEntity : CEntityInstance
CBaseEntity = {}

---AddEffects( int ): Adds the render effect flag.
---Server only.
---@param nFlags integer
function CBaseEntity:AddEffects(nFlags) end

---Apply a Velocity Impulse
---Server only.
---@param vecImpulse Vector
function CBaseEntity:ApplyAbsVelocityImpulse(vecImpulse) end

---Apply an Ang Velocity Impulse
---Server only.
---@param angImpulse Vector
function CBaseEntity:ApplyLocalAngularVelocityImpulse(angImpulse) end

---Get float value for an entity attribute.
---Server only.
---@param pName string
---@param flDefault number
---@return number
function CBaseEntity:Attribute_GetFloatValue(pName, flDefault) end

---Get int value for an entity attribute.
---Server only.
---@param pName string
---@param nDefault integer
---@return integer
function CBaseEntity:Attribute_GetIntValue(pName, nDefault) end

---Set float value for an entity attribute.
---Server only.
---@param pName string
---@param flValue number
function CBaseEntity:Attribute_SetFloatValue(pName, flValue) end

---Set int value for an entity attribute.
---Server only.
---@param pName string
---@param nValue integer
function CBaseEntity:Attribute_SetIntValue(pName, nValue) end

---Delete an entity attribute.
---Server only.
---@param pName string
function CBaseEntity:DeleteAttribute(pName) end

---Plays a sound from this entity.
---Server only.
---@param soundname string
function CBaseEntity:EmitSound(soundname) end

---Plays/modifies a sound from this entity. changes sound if nPitch and/or flVol or flSoundTime is > 0.
---Server only.
---@param soundname string
---@param nPitch integer
---@param flVolume number
---@param flDelay number
function CBaseEntity:EmitSoundParams(soundname, nPitch, flVolume, flDelay) end

---Get the qangles that this entity is looking at.
---Server only.
---@return QAngle
function CBaseEntity:EyeAngles() end

---Get vector to eye position - absolute coords.
---Server only.
---@return any
function CBaseEntity:EyePosition() end

---Server only.
---@return handle
function CBaseEntity:FirstMoveChild() end

---hEntity to follow, bool bBoneMerge
---Server only.
---@param hEnt handle
---@param bBoneMerge boolean
function CBaseEntity:FollowEntity(hEnt, bBoneMerge) end

---hEntity to follow, string BoneOrAttachName
---Server only.
---@param hEnt handle
---@param pszBoneOrAttachName string
function CBaseEntity:FollowEntityMerge(hEnt, pszBoneOrAttachName) end

---Returns a table containing the criteria that would be used for response queries on this entity. This is the same as the table that is passed to response rule script function callbacks.
---Server only.
---@param hResult handle
function CBaseEntity:GatherCriteria(hResult) end

---Server only.
---@return any
function CBaseEntity:GetAbsOrigin() end

---Server only.
function CBaseEntity:GetAbsOrigin_Engine(...) end

---Server only.
---@return number
function CBaseEntity:GetAbsScale() end

---Server only.
---@return QAngle
function CBaseEntity:GetAngles() end

---Get entity pitch, yaw, roll as a vector.
---Server only.
---@return Vector
function CBaseEntity:GetAnglesAsVector() end

---Get the local angular velocity - returns a vector of pitch,yaw,roll
---Server only.
---@return Vector
function CBaseEntity:GetAngularVelocity() end

---Get Base? velocity.
---Server only.
---@return Vector
function CBaseEntity:GetBaseVelocity() end

---Get a vector containing max bounds, centered on object.
---Server only.
---@return Vector
function CBaseEntity:GetBoundingMaxs() end

---Get a vector containing min bounds, centered on object.
---Server only.
---@return Vector
function CBaseEntity:GetBoundingMins() end

---Get a table containing the 'Mins' & 'Maxs' vector bounds, centered on object.
---Server only.
---@return table
function CBaseEntity:GetBounds() end

---Get vector to center of object - absolute coords
---Server only.
---@return any
function CBaseEntity:GetCenter() end

---Get the entities parented to this entity.
---Server only.
---@return handle
function CBaseEntity:GetChildren() end

---GetContext( name ): looks up a context and returns it if available. May return string, float, or null (if the context isn't found).
---Server only.
---@param name string
---@return table
function CBaseEntity:GetContext(name) end

---Get the forward vector of the entity.
---Server only.
---@return Vector
function CBaseEntity:GetForwardVector() end

---Get the health of this entity.
---Server only.
---@return integer
function CBaseEntity:GetHealth() end

---Get the left vector of the entity.
---Server only.
---@return Vector
function CBaseEntity:GetLeftVector() end

---Get entity local pitch, yaw, roll as a QAngle
---Server only.
---@return QAngle
function CBaseEntity:GetLocalAngles() end

---Maybe local angvel
---Server only.
---@return QAngle
function CBaseEntity:GetLocalAngularVelocity() end

---Get entity local origin as a Vector
---Server only.
---@return Vector
function CBaseEntity:GetLocalOrigin() end

---Server only.
---@return number
function CBaseEntity:GetLocalScale() end

---Get Entity relative velocity.
---Server only.
---@return Vector
function CBaseEntity:GetLocalVelocity() end

---Get the mass of an entity. (returns 0 if it doesn't have a physics object)
---Server only.
---@return number
function CBaseEntity:GetMass() end

---Get the maximum health of this entity.
---Server only.
---@return integer
function CBaseEntity:GetMaxHealth() end

---Returns the name of the model.
---Server only.
---@return string
function CBaseEntity:GetModelName() end

---If in hierarchy, retrieves the entity's parent.
---Server only.
---@return handle
function CBaseEntity:GetMoveParent() end

---Server only.
---@return any
function CBaseEntity:GetOrigin() end

---Gets this entity's owner
---Server only.
---@return handle
function CBaseEntity:GetOwner() end

---Get the owner entity, if there is one
---Server only.
---@return handle
function CBaseEntity:GetOwnerEntity() end

---Get the right vector of the entity. WARNING: This produces a left-handed coordinate system. Use GetLeftVector instead (which is aligned with the y axis of the entity).
---Server only.
---@return Vector
function CBaseEntity:GetRightVector() end

---If in hierarchy, walks up the hierarchy to find the root parent.
---Server only.
---@return handle
function CBaseEntity:GetRootMoveParent() end

---Returns float duration of the sound. Takes soundname and optional actormodelname.
---Server only.
---@param soundname string
---@param actormodel string
---@return number
function CBaseEntity:GetSoundDuration(soundname, actormodel) end

---Returns the spawn group handle of this entity
---Server only.
---@return integer
function CBaseEntity:GetSpawnGroupHandle() end

---Get the team number of this entity.
---Server only.
---@return integer
function CBaseEntity:GetTeam() end

---Get the team number of this entity.
---Server only.
---@return integer
function CBaseEntity:GetTeamNumber() end

---Get the up vector of the entity.
---Server only.
---@return Vector
function CBaseEntity:GetUpVector() end

---Server only.
---@return Vector
function CBaseEntity:GetVelocity() end

---See if an entity has a particular attribute.
---Server only.
---@param pName string
---@return boolean
function CBaseEntity:HasAttribute(pName) end

---Is this entity alive?
---Server only.
---@return boolean
function CBaseEntity:IsAlive() end

---Defined in scripts/vscripts/game/gameinit.lua:61.
---Server only.
function CBaseEntity:IsBaseNPC() end

---Is this entity a Dota NPC?
---Server only.
---@return boolean
function CBaseEntity:IsDOTANPC() end

---Defined in scripts/vscripts/utils/vscriptinit.lua:708.
---Server only.
function CBaseEntity:IsInstance(classOrClassName) end

---Is this entity an CAI_BaseNPC?
---Server only.
---@return boolean
function CBaseEntity:IsNPC() end

---Server only.
function CBaseEntity:IsNull(...) end

---Back compat: Is this entity a player pawn *or* controller?
---Server only.
---@return boolean
function CBaseEntity:IsPlayer() end

---Is this entity a player controller?
---Server only.
---@return boolean
function CBaseEntity:IsPlayerController() end

---Is this entity a player pawn?
---Server only.
---@return boolean
function CBaseEntity:IsPlayerPawn() end

---Server only.
function CBaseEntity:Kill() end

---Server only.
---@return handle
function CBaseEntity:NextMovePeer() end

---Precache a sound for later playing.
---Server only.
---@param soundname string
function CBaseEntity:PrecacheScriptSound(soundname) end

---RemoveEffects( int ): Removes the render effect flag.
---Server only.
---@param nFlags integer
function CBaseEntity:RemoveEffects(nFlags) end

---Set entity pitch, yaw, roll by component.
---Server only.
---@param fPitch number
---@param fYaw number
---@param fRoll number
function CBaseEntity:SetAbsAngles(fPitch, fYaw, fRoll) end

---Server only.
---@param origin any
function CBaseEntity:SetAbsOrigin(origin) end

---Server only.
function CBaseEntity:SetAbsOrigin_Engine(...) end

---Server only.
---@param flScale number
function CBaseEntity:SetAbsScale(flScale) end

---Set entity pitch, yaw, roll by component.
---Server only.
---@param fPitch number
---@param fYaw number
---@param fRoll number
function CBaseEntity:SetAngles(fPitch, fYaw, fRoll) end

---Set the local angular velocity - takes float pitch,yaw,roll velocities
---Server only.
---@param pitchVel number
---@param yawVel number
---@param rollVel number
function CBaseEntity:SetAngularVelocity(pitchVel, yawVel, rollVel) end

---Set the position of the constraint.
---Server only.
---@param vPos Vector
function CBaseEntity:SetConstraint(vPos) end

---SetContext( name , value, duration ): store any key/value pair in this entity's dialog contexts. Value must be a string. Will last for duration (set 0 to mean 'forever').
---Server only.
---@param pName string
---@param pValue string
---@param duration number
function CBaseEntity:SetContext(pName, pValue, duration) end

---SetContextNum( name , value, duration ): store any key/value pair in this entity's dialog contexts. Value must be a number (int or float). Will last for duration (set 0 to mean 'forever').
---Server only.
---@param pName string
---@param fValue number
---@param duration number
function CBaseEntity:SetContextNum(pName, fValue, duration) end

---Set a think function on this entity.
---Server only.
---@param pszContextName string
---@param hThinkFunc handle
---@param flInterval number
function CBaseEntity:SetContextThink(pszContextName, hThinkFunc, flInterval) end

---Set the name of an entity.
---Server only.
---@param pName string
function CBaseEntity:SetEntityName(pName) end

---Set the orientation of the entity to have this forward vector.
---Server only.
---@param v Vector
function CBaseEntity:SetForwardVector(v) end

---Set PLAYER friction, ignored for objects.
---Server only.
---@param flFriction number
function CBaseEntity:SetFriction(flFriction) end

---Set PLAYER gravity, ignored for objects.
---Server only.
---@param flGravity number
function CBaseEntity:SetGravity(flGravity) end

---Set the health of this entity.
---Server only.
---@param nHealth integer
function CBaseEntity:SetHealth(nHealth) end

---Set entity local pitch, yaw, roll by component
---Server only.
---@param fPitch number
---@param fYaw number
---@param fRoll number
function CBaseEntity:SetLocalAngles(fPitch, fYaw, fRoll) end

---Set entity local origin from a Vector
---Server only.
---@param origin Vector
function CBaseEntity:SetLocalOrigin(origin) end

---Server only.
---@param flScale number
function CBaseEntity:SetLocalScale(flScale) end

---Set the mass of an entity. (does nothing if it doesn't have a physics object)
---Server only.
---@param flMass number
function CBaseEntity:SetMass(flMass) end

---Set the maximum health of this entity.
---Server only.
---@param amt integer
function CBaseEntity:SetMaxHealth(amt) end

---Server only.
---@param v Vector
function CBaseEntity:SetOrigin(v) end

---Sets this entity's owner
---Server only.
---@param pOwner handle
function CBaseEntity:SetOwner(pOwner) end

---Set the parent for this entity.
---Server only.
---@param hParent handle
---@param pAttachmentname string
function CBaseEntity:SetParent(hParent, pAttachmentname) end

---Server only.
---@param iTeamNum integer
function CBaseEntity:SetTeam(iTeamNum) end

---Defined in scripts/vscripts/utils/vscriptinit.lua:654.
---Server only.
function CBaseEntity:SetThink(fnname, ...) end

---Server only.
---@param vecVelocity Vector
function CBaseEntity:SetVelocity(vecVelocity) end

---Stops a named sound playing from this entity.
---Server only.
---@param soundname string
function CBaseEntity:StopSound(soundname) end

---Defined in scripts/vscripts/utils/vscriptinit.lua:704.
---Server only.
function CBaseEntity:StopThink(contextName) end

---Apply damage to this entity. Use CreateDamageInfo() to create a damageinfo object.
---Server only.
---@param hInfo handle
---@return integer
function CBaseEntity:TakeDamage(hInfo) end

---Returns the input Vector transformed from entity to world space
---Server only.
---@param vPoint Vector
---@return any
function CBaseEntity:TransformPointEntityToWorld(vPoint) end

---Returns the input Vector transformed from world to entity space
---Server only.
---@param vPoint any
---@return Vector
function CBaseEntity:TransformPointWorldToEntity(vPoint) end

---Fires off this entity's OnTrigger responses.
---Server only.
function CBaseEntity:Trigger() end

---Validates the private script scope and creates it if one doesn't exist.
---Server only.
function CBaseEntity:ValidatePrivateScriptScope() end
