---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CBaseAnimatingActivity
CBaseAnimatingActivity = CBaseAnimatingActivity

---Returns the duration in seconds of the active sequence.
---Server only.
---@return number
function CBaseAnimatingActivity:ActiveSequenceDuration() end

---Get the cycle of the animation.
---Server only.
---@return number
function CBaseAnimatingActivity:GetCycle() end

---Returns the name of the active sequence.
---Server only.
---@return string
function CBaseAnimatingActivity:GetSequence() end

---Ask whether the main sequence is done playing.
---Server only.
---@return boolean
function CBaseAnimatingActivity:IsSequenceFinished() end

---Sets the active sequence by name, resetting the current cycle.
---Server only.
---@param pSequenceName string
function CBaseAnimatingActivity:ResetSequence(pSequenceName) end

---Returns the duration in seconds of the given sequence name.
---Server only.
---@param pSequenceName string
---@return number
function CBaseAnimatingActivity:SequenceDuration(pSequenceName) end

---Set the cycle of the animation.
---Server only.
---@param flCycle number
function CBaseAnimatingActivity:SetCycle(flCycle) end

---Set the specified pose parameter to the specified value.
---Server only.
---@param szName string
---@param fValue number
---@return number
function CBaseAnimatingActivity:SetPoseParameter(szName, fValue) end

---Sets the active sequence by name, keeping the current cycle.
---Server only.
---@param pSequenceName string
function CBaseAnimatingActivity:SetSequence(pSequenceName) end

---Stop the current animation by setting playback rate to 0.0.
---Server only.
function CBaseAnimatingActivity:StopAnimation() end
