---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CBasePlayerPawn : CBaseCombatCharacter
CBasePlayerPawn = {}

---GetController() : Returns the controller for this pawn
---Server only.
---@return handle
function CBasePlayerPawn:GetController() end

---GetEquippedWeapons() : Returns an array of all the equipped weapons
---Server only.
---@return table
function CBasePlayerPawn:GetEquippedWeapons() end

---GetWeaponCount() : Gets the number of weapons currently equipped
---Server only.
---@return integer
function CBasePlayerPawn:GetWeaponCount() end

---Returns true if the player is in noclip mode.
---Server only.
---@return boolean
function CBasePlayerPawn:IsNoclipping() end

---Server only.
function CBasePlayerPawn:IsNull(...) end
