---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CBaseModelEntity : CBaseEntity
CBaseModelEntity = {}

---Get the attachment id's angles as a p,y,r vector.
---Server only.
---@param iAttachment integer
---@return Vector
function CBaseModelEntity:GetAttachmentAngles(iAttachment) end

---Get the attachment id's forward vector.
---Server only.
---@param iAttachment integer
---@return Vector
function CBaseModelEntity:GetAttachmentForward(iAttachment) end

---Get the attachment id's origin vector.
---Server only.
---@param iAttachment integer
---@return any
function CBaseModelEntity:GetAttachmentOrigin(iAttachment) end

---GetMaterialGroupHash(): Get the material group hash of this entity.
---Server only.
---@return integer
function CBaseModelEntity:GetMaterialGroupHash() end

---GetMaterialGroupMask(): Get the mesh group mask of this entity.
---Server only.
---@return any
function CBaseModelEntity:GetMaterialGroupMask() end

---Get scale of entity's model.
---Server only.
---@return number
function CBaseModelEntity:GetModelScale() end

---GetRenderAlpha(): Get the alpha modulation of this entity.
---Server only.
---@return integer
function CBaseModelEntity:GetRenderAlpha() end

---GetRenderColor(): Get the render color of the entity.
---Server only.
---@return Vector
function CBaseModelEntity:GetRenderColor() end

---Server only.
function CBaseModelEntity:IsNull(...) end

---Get the named attachment id.
---Server only.
---@param pAttachmentName string
---@return integer
function CBaseModelEntity:ScriptLookupAttachment(pAttachmentName) end

---Sets a bodygroup.
---Server only.
---@param nBodyGroup integer
---@param nChoice integer
function CBaseModelEntity:SetBodygroup(nBodyGroup, nChoice) end

---Sets a bodygroup by name.
---Server only.
---@param pName string
---@param iValue integer
function CBaseModelEntity:SetBodygroupByName(pName, iValue) end

---SetMaterialGroup( string ): Set the material group of this entity.
---Server only.
---@param pMaterialGroup string
function CBaseModelEntity:SetMaterialGroup(pMaterialGroup) end

---SetMaterialGroupHash( uint32 ): Set the material group hash of this entity.
---Server only.
---@param nHash integer
function CBaseModelEntity:SetMaterialGroupHash(nHash) end

---SetMaterialGroupMask( uint64 ): Set the mesh group mask of this entity.
---Server only.
---@param nMeshGroupMask any
function CBaseModelEntity:SetMaterialGroupMask(nMeshGroupMask) end

---Server only.
---@param pModelName string
function CBaseModelEntity:SetModel(pModelName) end

---Set scale of entity's model.
---Server only.
---@param flScale number
function CBaseModelEntity:SetModelScale(flScale) end

---SetRenderAlpha( int ): Set the alpha modulation of this entity.
---Server only.
---@param nAlpha integer
function CBaseModelEntity:SetRenderAlpha(nAlpha) end

---SetRenderColor( r, g, b ): Sets the render color of the entity.
---Server only.
---@param r integer
---@param g integer
---@param b integer
function CBaseModelEntity:SetRenderColor(r, g, b) end

---SetRenderMode( int ): Sets the render mode of the entity.
---Server only.
---@param nMode integer
function CBaseModelEntity:SetRenderMode(nMode) end

---SetSingleMeshGroup( string ): Set a single mesh group for this entity.
---Server only.
---@param pMeshGroupName string
function CBaseModelEntity:SetSingleMeshGroup(pMeshGroupName) end

---Server only.
---@param mins Vector
---@param maxs Vector
function CBaseModelEntity:SetSize(mins, maxs) end

---Set skin (int).
---Server only.
---@param iSkin integer
function CBaseModelEntity:SetSkin(iSkin) end
