---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CBaseAnimatingOverlay : CBaseAnimatingActivity
CBaseAnimatingOverlay = {}

---Server only.
function CBaseAnimatingOverlay:IsNull(...) end
