---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CBaseTrigger : CBaseEntity
CBaseTrigger = {}

---Disable's the trigger
---Server only.
function CBaseTrigger:Disable() end

---Enable the trigger
---Server only.
function CBaseTrigger:Enable() end

---Server only.
function CBaseTrigger:IsNull(...) end

---Checks whether the passed entity is touching the trigger.
---Server only.
---@param hEnt handle
---@return boolean
function CBaseTrigger:IsTouching(hEnt) end
