---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CCustomNetTableManager
CCustomNetTableManager = CCustomNetTableManager

---( string TableName, string KeyName, script_table Value )
---Server only.
---@param string_1 string
---@param string_2 string
---@param handle_3 handle
---@return boolean
function CCustomNetTableManager:SetTableValue(string_1, string_2, handle_3) end
