---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CCustomGameEventManager
CCustomGameEventManager = {}

---Server only.
function CCustomGameEventManager:IsNull(...) end

---( string EventName, func CallbackFunction ) - Register a callback to be called when a particular custom event arrives. Returns a listener ID that can be used to unregister later.
---Server only.
---@param string_1 string
---@param handle_2 handle
---@return integer
function CCustomGameEventManager:RegisterListener(string_1, handle_2) end

---( string EventName, table EventData )
---Server only.
---@param string_1 string
---@param handle_2 handle
function CCustomGameEventManager:Send_ServerToAllClients(string_1, handle_2) end

---( Entity Player, string EventName, table EventData )
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param handle_3 handle
function CCustomGameEventManager:Send_ServerToPlayer(handle_1, string_2, handle_3) end

---( int TeamNumber, string EventName, table EventData )
---Server only.
---@param int_1 integer
---@param string_2 string
---@param handle_3 handle
function CCustomGameEventManager:Send_ServerToTeam(int_1, string_2, handle_3) end

---( int ListnerID ) - Unregister a specific listener
---Server only.
---@param int_1 integer
function CCustomGameEventManager:UnregisterListener(int_1) end
