---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDotaQuest : CBaseEntity
CDotaQuest = {}

---Add a subquest to this quest
---Server only.
---@param hSubquest handle
function CDotaQuest:AddSubquest(hSubquest) end

---Mark this quest complete
---Server only.
function CDotaQuest:CompleteQuest() end

---Finds a subquest from this quest by index
---Server only.
---@param nIndex integer
---@return handle
function CDotaQuest:GetSubquest(nIndex) end

---Finds a subquest from this quest by name
---Server only.
---@param pszName string
---@return handle
function CDotaQuest:GetSubquestByName(pszName) end

---Server only.
function CDotaQuest:IsNull(...) end

---Remove a subquest from this quest
---Server only.
---@param hSubquest handle
function CDotaQuest:RemoveSubquest(hSubquest) end

---Set the text replace string for this quest
---Server only.
---@param pszString string
function CDotaQuest:SetTextReplaceString(pszString) end

---Set a quest value
---Server only.
---@param valueSlot integer
---@param value integer
function CDotaQuest:SetTextReplaceValue(valueSlot, value) end
