---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Unit_CustomGameAnnouncerAghanim : CDOTA_BaseNPC
CDOTA_Unit_CustomGameAnnouncerAghanim = {}

---Server only.
function CDOTA_Unit_CustomGameAnnouncerAghanim:IsNull(...) end

---Set the animation sequence for this entity.
---Server only.
---@param pAnimation string
function CDOTA_Unit_CustomGameAnnouncerAghanim:SetAnimation(pAnimation) end

---Determines whether response criteria is matched on server or client
---Server only.
---@param bIsServerAuthoritative boolean
function CDOTA_Unit_CustomGameAnnouncerAghanim:SetServerAuthoritative(bIsServerAuthoritative) end
