---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC : CBaseAnimatingOverlay
CDOTA_BaseNPC = {}

---Add an ability to this unit by name.
---Server only.
---@param pszAbilityName string
---@return handle
function CDOTA_BaseNPC:AddAbility(pszAbilityName) end

---Add an activity modifier that affects future StartGesture calls
---Server only.
---@param szName string
function CDOTA_BaseNPC:AddActivityModifier(szName) end

---Add an item to this unit's inventory.
---Server only.
---@param hItem handle
---@return handle
function CDOTA_BaseNPC:AddItem(hItem) end

---Add an item to this unit's inventory.
---Server only.
---@param pszItemName string
---@return handle
function CDOTA_BaseNPC:AddItemByName(pszItemName) end

---Add a modifier to this unit.
---Server only.
---@param hCaster handle
---@param hAbility handle
---@param pszScriptName string
---@param hModifierTable handle
---@return handle
function CDOTA_BaseNPC:AddNewModifier(hCaster, hAbility, pszScriptName, hModifierTable) end

---Adds the no draw flag.
---Server only.
function CDOTA_BaseNPC:AddNoDraw() end

---Add a speech bubble(1-4 live at a time) to this NPC.
---Server only.
---@param iBubble integer
---@param pszSpeech string
---@param flDuration number
---@param unOffsetX integer
---@param unOffsetY integer
function CDOTA_BaseNPC:AddSpeechBubble(iBubble, pszSpeech, flDuration, unOffsetX, unOffsetY) end

---Server only.
---@param hAttacker handle
---@param hAbility handle
function CDOTA_BaseNPC:AlertNearbyUnits(hAttacker, hAbility) end

---Server only.
function CDOTA_BaseNPC:AngerNearbyUnits() end

---Server only.
---@param flTime number
---@param flTimeDisparityTolerance number
function CDOTA_BaseNPC:AttackNoEarlierThan(flTime, flTimeDisparityTolerance) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:AttackReady() end

---Server only.
---@return number
function CDOTA_BaseNPC:BoundingRadius2D() end

---Server only.
function CDOTA_BaseNPC:CalculateGenericBonuses() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:CanBeSeenByAnyOpposingTeam() end

---Check FoW to see if an entity is visible.
---Server only.
---@param hEntity handle
---@return boolean
function CDOTA_BaseNPC:CanEntityBeSeenByMyTeam(hEntity) end

---Query if this unit can sell items.
---Server only.
---@return boolean
function CDOTA_BaseNPC:CanSellItems() end

---Cast an ability immediately.
---Server only.
---@param hAbility handle
---@param iPlayerIndex integer
function CDOTA_BaseNPC:CastAbilityImmediately(hAbility, iPlayerIndex) end

---Cast an ability with no target.
---Server only.
---@param hAbility handle
---@param iPlayerIndex integer
function CDOTA_BaseNPC:CastAbilityNoTarget(hAbility, iPlayerIndex) end

---Cast an ability on a position.
---Server only.
---@param vPosition any
---@param hAbility handle
---@param iPlayerIndex integer
function CDOTA_BaseNPC:CastAbilityOnPosition(vPosition, hAbility, iPlayerIndex) end

---Cast an ability on a target entity.
---Server only.
---@param hTarget handle
---@param hAbility handle
---@param iPlayerIndex integer
function CDOTA_BaseNPC:CastAbilityOnTarget(hTarget, hAbility, iPlayerIndex) end

---Toggle an ability.
---Server only.
---@param hAbility handle
---@param iPlayerIndex integer
function CDOTA_BaseNPC:CastAbilityToggle(hAbility, iPlayerIndex) end

---Server only.
---@param iTeamNum integer
function CDOTA_BaseNPC:ChangeTeam(iTeamNum) end

---Clear Activity modifiers
---Server only.
function CDOTA_BaseNPC:ClearActivityModifiers() end

---Consume the item, deleting it from the inventory and granting the hero the specified bonuses.
---Server only.
---@param hItem handle
function CDOTA_BaseNPC:ConsumeItem(hItem) end

---Server only.
function CDOTA_BaseNPC:DestroyAllSpeechBubbles() end

---Disassemble the passed item in this unit's inventory.
---Server only.
---@param hItem handle
function CDOTA_BaseNPC:DisassembleItem(hItem) end

---Drop an item at a given point.
---Server only.
---@param vDest any
---@param hItem handle
function CDOTA_BaseNPC:DropItemAtPosition(vDest, hItem) end

---Immediately drop a carried item at a given position.
---Server only.
---@param hItem handle
---@param vPosition any
function CDOTA_BaseNPC:DropItemAtPositionImmediate(hItem, vPosition) end

---Drops the selected item out of this unit's stash.
---Server only.
---@param hItem handle
function CDOTA_BaseNPC:EjectItemFromStash(hItem) end

---This unit will be set to face the target point.
---Server only.
---@param vTarget any
function CDOTA_BaseNPC:FaceTowards(vTarget) end

---Fade and remove the given gesture activity.
---Server only.
---@param nActivity integer
function CDOTA_BaseNPC:FadeGesture(nActivity) end

---Retrieve an ability by name from the unit.
---Server only.
---@param pAbilityName string
---@return handle
function CDOTA_BaseNPC:FindAbilityByName(pAbilityName) end

---Returns a table of all of the modifiers on the NPC.
---Server only.
---@return table
function CDOTA_BaseNPC:FindAllModifiers() end

---Returns a table of all of the modifiers on the NPC with the passed name (modifierName)
---Server only.
---@param pszScriptName string
---@return table
function CDOTA_BaseNPC:FindAllModifiersByName(pszScriptName) end

---Get handle to first item in inventory, else nil.
---Server only.
---@param pszItemName string
---@return handle
function CDOTA_BaseNPC:FindItemInInventory(pszItemName) end

---Return a handle to the modifier of the given name if found, else nil (string Name )
---Server only.
---@param pszScriptName string
---@return handle
function CDOTA_BaseNPC:FindModifierByName(pszScriptName) end

---Return a handle to the modifier of the given name from the passed caster if found, else nil ( string Name, hCaster )
---Server only.
---@param pszScriptName string
---@param hCaster handle
---@return handle
function CDOTA_BaseNPC:FindModifierByNameAndCaster(pszScriptName, hCaster) end

---Kill this unit immediately.
---Server only.
---@param bReincarnate boolean
function CDOTA_BaseNPC:ForceKill(bReincarnate) end

---Play an activity once, and then go back to idle.
---Server only.
---@param nActivity integer
function CDOTA_BaseNPC:ForcePlayActivityOnce(nActivity) end

---Retrieve an ability by index from the unit.
---Server only.
---@param iIndex integer
---@return handle
function CDOTA_BaseNPC:GetAbilityByIndex(iIndex) end

---Server only.
---@return integer
function CDOTA_BaseNPC:GetAbilityCount() end

---Gets the range at which this unit will auto-acquire.
---Server only.
---@return number
function CDOTA_BaseNPC:GetAcquisitionRange() end

---Combat involving this creature will have this weight added to the music calcuations.
---Server only.
---@return number
function CDOTA_BaseNPC:GetAdditionalBattleMusicWeight() end

---Returns this unit's aggro target.
---Server only.
---@return handle
function CDOTA_BaseNPC:GetAggroTarget() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetAttackAnimationPoint() end

---Server only.
---@return integer
function CDOTA_BaseNPC:GetAttackCapability() end

---Returns a random integer between the minimum and maximum base damage of the unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetAttackDamage() end

---Gets the attack range buffer.
---Server only.
---@return number
function CDOTA_BaseNPC:GetAttackRangeBuffer() end

---Server only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function CDOTA_BaseNPC:GetAttackSpeed(bIgnoreTempAttackSpeed) end

---Server only.
---@return handle
function CDOTA_BaseNPC:GetAttackTarget() end

---Server only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function CDOTA_BaseNPC:GetAttacksPerSecond(bIgnoreTempAttackSpeed) end

---Returns the average value of the minimum and maximum damage values.
---Server only.
---@param hTarget handle
---@return integer
function CDOTA_BaseNPC:GetAverageTrueAttackDamage(hTarget) end

---Server only.
---@return integer
function CDOTA_BaseNPC:GetBaseAttackRange() end

---Server only.
---@param bIgnoreModifiers boolean
---@return number
function CDOTA_BaseNPC:GetBaseAttackTime(bIgnoreModifiers) end

---Get the maximum attack damage of this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetBaseDamageMax() end

---Get the minimum attack damage of this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetBaseDamageMin() end

---Returns the vision range before modifiers.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetBaseDayTimeVisionRange() end

---Server only.
---@return integer
function CDOTA_BaseNPC:GetBaseHealthBarOffset() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetBaseHealthRegen() end

---Returns base magical armor value.
---Server only.
---@return number
function CDOTA_BaseNPC:GetBaseMagicalResistanceValue() end

---Gets the base max health value.
---Server only.
---@return number
function CDOTA_BaseNPC:GetBaseMaxHealth() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetBaseMoveSpeed() end

---Returns the vision range after modifiers.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetBaseNightTimeVisionRange() end

---This Mana regen is derived from constant bonuses like Basilius.
---Server only.
---@return number
function CDOTA_BaseNPC:GetBonusManaRegen() end

---Server only.
---@param bAttack boolean
---@return number
function CDOTA_BaseNPC:GetCastPoint(bAttack) end

---Server only.
---@return number
function CDOTA_BaseNPC:GetCastRangeBonus() end

---Get clone source (Meepo Prime, if this is a Meepo)
---Server only.
---@return handle
function CDOTA_BaseNPC:GetCloneSource() end

---Returns the size of the collision padding around the hull.
---Server only.
---@return number
function CDOTA_BaseNPC:GetCollisionPadding() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetCooldownReduction() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetCreationTime() end

---Get the ability this unit is currently casting.
---Server only.
---@return handle
function CDOTA_BaseNPC:GetCurrentActiveAbility() end

---Gets the current vision range.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetCurrentVisionRange() end

---Server only.
---@return handle
function CDOTA_BaseNPC:GetCursorCastTarget() end

---Server only.
---@return any
function CDOTA_BaseNPC:GetCursorPosition() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:GetCursorTargetingNothing() end

---Get the maximum attack damage of this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetDamageMax() end

---Get the minimum attack damage of this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetDamageMin() end

---Returns the vision range after modifiers.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetDayTimeVisionRange() end

---Get the XP bounty on this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetDeathXP() end

---Attack speed expressed as constant value
---Server only.
---@return number
function CDOTA_BaseNPC:GetDisplayAttackSpeed() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetEvasion() end

---Server only.
---@return handle
function CDOTA_BaseNPC:GetForceAttackTarget() end

---Get the gold bounty on this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetGoldBounty() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetHasteFactor() end

---Returns integer amount of health missing from max.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetHealthDeficit() end

---Get the current health percent of the unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetHealthPercent() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetHealthRegen() end

---Get the collision hull radius of this NPC.
---Server only.
---@return number
function CDOTA_BaseNPC:GetHullRadius() end

---Returns speed after all modifiers.
---Server only.
---@return number
function CDOTA_BaseNPC:GetIdealSpeed() end

---Returns speed after all modifiers, but excluding those that reduce speed.
---Server only.
---@return number
function CDOTA_BaseNPC:GetIdealSpeedNoSlows() end

---Server only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function CDOTA_BaseNPC:GetIncreasedAttackSpeed(bIgnoreTempAttackSpeed) end

---Returns the initial waypoint goal for this NPC.
---Server only.
---@return handle
function CDOTA_BaseNPC:GetInitialGoalEntity() end

---Get waypoint position for this NPC.
---Server only.
---@return any
function CDOTA_BaseNPC:GetInitialGoalPosition() end

---Returns nth item in inventory slot (index is zero based).
---Server only.
---@param i integer
---@return handle
function CDOTA_BaseNPC:GetItemInSlot(i) end

---Server only.
---@return number
function CDOTA_BaseNPC:GetLastAttackTime() end

---Get the last time this NPC took damage
---Server only.
---@return number
function CDOTA_BaseNPC:GetLastDamageTime() end

---Get the last game time that this unit switched to/from idle state.
---Server only.
---@return number
function CDOTA_BaseNPC:GetLastIdleChangeTime() end

---Returns the level of this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetLevel() end

---Returns the player ID of the controlling player.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetMainControllingPlayer() end

---Get the mana on this unit.
---Server only.
---@return number
function CDOTA_BaseNPC:GetMana() end

---Get the percent of mana remaining.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetManaPercent() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetManaRegen() end

---Get the maximum mana of this unit.
---Server only.
---@return number
function CDOTA_BaseNPC:GetMaxMana() end

---Get the maximum gold bounty for this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetMaximumGoldBounty() end

---Get the minimum gold bounty for this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetMinimumGoldBounty() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetModelRadius() end

---How many modifiers does this unit have?
---Server only.
---@return integer
function CDOTA_BaseNPC:GetModifierCount() end

---Get a modifier name by index.
---Server only.
---@param nIndex integer
---@return string
function CDOTA_BaseNPC:GetModifierNameByIndex(nIndex) end

---Gets the stack count of a given modifier.
---Server only.
---@param pszScriptName string
---@param hCaster handle
---@return integer
function CDOTA_BaseNPC:GetModifierStackCount(pszScriptName, hCaster) end

---Server only.
---@param flBaseSpeed number
---@param bReturnUnslowed boolean
---@return number
function CDOTA_BaseNPC:GetMoveSpeedModifier(flBaseSpeed, bReturnUnslowed) end

---Set whether this NPC is required to reach each goal entity, rather than being allowed to unkink their path.
---Server only.
---@return boolean
function CDOTA_BaseNPC:GetMustReachEachGoalEntity() end

---Get the name of this camp's neutral spawner.
---Server only.
---@return string
function CDOTA_BaseNPC:GetNeutralSpawnerName() end

---If set to true, we will never attempt to move this unit to clear space, even when it unphases.
---Server only.
---@return boolean
function CDOTA_BaseNPC:GetNeverMoveToClearSpace() end

---Returns the vision range after modifiers.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetNightTimeVisionRange() end

---Server only.
---@return integer
function CDOTA_BaseNPC:GetOpposingTeamNumber() end

---Get the collision hull radius (including padding) of this NPC.
---Server only.
---@return number
function CDOTA_BaseNPC:GetPaddedCollisionRadius() end

---Returns base physical armor value.
---Server only.
---@return number
function CDOTA_BaseNPC:GetPhysicalArmorBaseValue() end

---Returns current physical armor value.
---Server only.
---@param bIgnoreBase boolean
---@return number
function CDOTA_BaseNPC:GetPhysicalArmorValue(bIgnoreBase) end

---Returns the player that owns this unit.
---Server only.
---@return handle
function CDOTA_BaseNPC:GetPlayerOwner() end

---Get the owner player ID for this unit.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetPlayerOwnerID() end

---Server only.
---@return integer
function CDOTA_BaseNPC:GetProjectileSpeed() end

---Server only.
---@param hNPC handle
---@return number
function CDOTA_BaseNPC:GetRangeToUnit(hNPC) end

---Server only.
---@return string
function CDOTA_BaseNPC:GetRangedProjectileName() end

---Server only.
---@return number
function CDOTA_BaseNPC:GetRemainingPathLength() end

---Server only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function CDOTA_BaseNPC:GetSecondsPerAttack(bIgnoreTempAttackSpeed) end

---Server only.
---@param bBaseOnly boolean
---@return number
function CDOTA_BaseNPC:GetSpellAmplification(bBaseOnly) end

---Server only.
---@return number
function CDOTA_BaseNPC:GetStatusResistance() end

---Get how much gold has been spent on ability upgrades.
---Server only.
---@return integer
function CDOTA_BaseNPC:GetTotalPurchasedUpgradeGoldCost() end

---Server only.
---@return string
function CDOTA_BaseNPC:GetUnitLabel() end

---Get the name of this unit.
---Server only.
---@return string
function CDOTA_BaseNPC:GetUnitName() end

---Give mana to this unit, this can be used for mana gained by abilities or item usage.
---Server only.
---@param flMana number
function CDOTA_BaseNPC:GiveMana(flMana) end

---See whether this unit has an ability by name.
---Server only.
---@param pszAbilityName string
---@return boolean
function CDOTA_BaseNPC:HasAbility(pszAbilityName) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:HasAnyActiveAbilities() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:HasAttackCapability() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:HasFlyMovementCapability() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:HasFlyingVision() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:HasGroundMovementCapability() end

---Does this unit have an inventory.
---Server only.
---@return boolean
function CDOTA_BaseNPC:HasInventory() end

---See whether this unit has an item by name.
---Server only.
---@param pItemName string
---@return boolean
function CDOTA_BaseNPC:HasItemInInventory(pItemName) end

---Sees if this unit has a given modifier.
---Server only.
---@param pszScriptName string
---@return boolean
function CDOTA_BaseNPC:HasModifier(pszScriptName) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:HasMovementCapability() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:HasScepter() end

---Heal this unit.
---Server only.
---@param flAmount number
---@param hInflictor handle
function CDOTA_BaseNPC:Heal(flAmount, hInflictor) end

---Heal this unit (with more parameters)
---Server only.
---@param flAmount number
---@param hInflictor handle
---@param bLifesteal boolean
---@param bAmplify boolean
---@param hSource handle
---@param bSpellLifesteal boolean
function CDOTA_BaseNPC:HealWithParams(flAmount, hInflictor, bLifesteal, bAmplify, hSource, bSpellLifesteal) end

---Hold position.
---Server only.
function CDOTA_BaseNPC:Hold() end

---Server only.
function CDOTA_BaseNPC:Interrupt() end

---Server only.
function CDOTA_BaseNPC:InterruptChannel() end

---Server only.
---@param bFindClearSpace boolean
function CDOTA_BaseNPC:InterruptMotionControllers(bFindClearSpace) end

---Is this unit alive?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsAlive() end

---Is this unit an Ancient?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsAncient() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsAttackImmune() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsAttacking() end

---Server only.
---@param hEntity handle
---@return boolean
function CDOTA_BaseNPC:IsAttackingEntity(hEntity) end

---Is this unit a Barracks?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsBarracks() end

---Defined in scripts/vscripts/game/gameinit.lua:80.
---Server only.
function CDOTA_BaseNPC:IsBaseNPC() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsBlind() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsBlockDisabled() end

---Is this unit a boss?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsBoss() end

---Is this unit a Boss Creature? (used by custom games)
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsBossCreature() end

---Is this unit a building?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsBuilding() end

---Is this unit currently channeling a spell?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsChanneling() end

---Is this unit a clone? (Meepo)
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsClone() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsCommandRestricted() end

---Is this unit a considered a hero for targeting purposes?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsConsideredHero() end

---Is this unit controlled by any non-bot player?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsControllableByAnyPlayer() end

---Is this unit a courier?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsCourier() end

---Is this a Creature type NPC?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsCreature() end

---Is this unit a creep?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsCreep() end

---Is this unit a creep hero?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsCreepHero() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsCurrentlyHorizontalMotionControlled() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsCurrentlyVerticalMotionControlled() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsDebuffImmune() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsDisarmed() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsDominated() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsEvadeDisabled() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsFeared() end

---Is this unit an Ancient?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsFort() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsFrozen() end

---Defined in scripts/vscripts/game/gameinit.lua:72.
---Server only.
function CDOTA_BaseNPC:IsHardDisarmed() end

---Is this a hero or hero illusion?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsHero() end

---Is this a Hero Ward?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsHeroWard() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsHexed() end

---Is this creature currently idle?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsIdle() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsIllusion() end

---Ask whether this unit is in range of the specified shop ( DOTA_SHOP_TYPE shop, bool bMustBePhysicallyNear
---Server only.
---@param nShopType integer
---@param bPhysical boolean
---@return boolean
function CDOTA_BaseNPC:IsInRangeOfShop(nShopType, bPhysical) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsInvisible() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsInvulnerable() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsLowAttackPriority() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsMagicImmune() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsMovementImpaired() end

---Is this unit moving?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsMoving() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsMuted() end

---Is this a neutral?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsNeutralUnitType() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsNightmared() end

---Server only.
function CDOTA_BaseNPC:IsNull(...) end

---Server only.
---@param nTeam integer
---@return boolean
function CDOTA_BaseNPC:IsOpposingTeam(nTeam) end

---Is this unit a ward-type unit?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsOther() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsOutOfGame() end

---Is this unit owned by any non-bot player?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsOwnedByAnyPlayer() end

---Is this a phantom unit?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsPhantom() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsPhantomBlocker() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsPhased() end

---Server only.
---@param vPosition any
---@param flRange number
---@return boolean
function CDOTA_BaseNPC:IsPositionInRange(vPosition, flRange) end

---Is this unit a ranged attacker?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsRangedAttacker() end

---Is this a real hero?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsRealHero() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsReincarnating() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsRooted() end

---Is this a shrine?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsShrine() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsSilenced() end

---Defined in scripts/vscripts/game/gameinit.lua:76.
---Server only.
function CDOTA_BaseNPC:IsSoftDisarmed() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsSpeciallyDeniable() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsSpeciallyUndeniable() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsStrongIllusion() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsStunned() end

---Is this unit summoned?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsSummoned() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsTaunted() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsTempestDouble() end

---Is this a tower?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsTower() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsUnableToMiss() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:IsUnselectable() end

---Server only.
---@param pTargettingSource handle
---@return boolean
function CDOTA_BaseNPC:IsUntargetableFrom(pTargettingSource) end

---Is this a Ward?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsWard() end

---Is this entity an Undying Zombie?
---Server only.
---@return boolean
function CDOTA_BaseNPC:IsZombie() end

---Kills this NPC, with the params Ability and Attacker.
---Server only.
---@param hAbility handle
---@param hAttacker handle
function CDOTA_BaseNPC:Kill(hAbility, hAttacker) end

---Server only.
function CDOTA_BaseNPC:MakeIllusion() end

---Server only.
function CDOTA_BaseNPC:MakePhantomBlocker() end

---Server only.
---@param iTeam integer
---@param flRadius number
function CDOTA_BaseNPC:MakeVisibleDueToAttack(iTeam, flRadius) end

---Server only.
---@param iTeam integer
---@param flDuration number
function CDOTA_BaseNPC:MakeVisibleToTeam(iTeam, flDuration) end

---Server only.
function CDOTA_BaseNPC:ManageModelChanges() end

---Sets the health to a specific value, with optional flags or inflictors.
---Server only.
---@param iDesiredHealthValue integer
---@param hAbility handle
---@param bLethal boolean
---@param iAdditionalFlags integer
function CDOTA_BaseNPC:ModifyHealth(iDesiredHealthValue, hAbility, bLethal, iAdditionalFlags) end

---Move to follow a unit.
---Server only.
---@param hNPC handle
function CDOTA_BaseNPC:MoveToNPC(hNPC) end

---Give an item to another unit.
---Server only.
---@param hNPC handle
---@param hItem handle
function CDOTA_BaseNPC:MoveToNPCToGiveItem(hNPC, hItem) end

---Issue a Move-To command.
---Server only.
---@param vDest any
function CDOTA_BaseNPC:MoveToPosition(vDest) end

---Issue an Attack-Move-To command.
---Server only.
---@param vDest any
function CDOTA_BaseNPC:MoveToPositionAggressive(vDest) end

---Move to a target to attack.
---Server only.
---@param hTarget handle
function CDOTA_BaseNPC:MoveToTargetToAttack(hTarget) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:NoHealthBar() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:NoTeamMoveTo() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:NoTeamSelect() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:NoUnitCollision() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:NotOnMinimap() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:NotOnMinimapForEnemies() end

---Server only.
---@param bOriginalModel boolean
function CDOTA_BaseNPC:NotifyWearablesOfModelChange(bOriginalModel) end

---Tells the underlying AI to move in the given direction, skipping Dota orders
---Server only.
---@param vPos any
function CDOTA_BaseNPC:OnCommandMoveToDirection(vPos) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:PassivesDisabled() end

---Issue a Patrol-To command.
---Server only.
---@param vDest any
function CDOTA_BaseNPC:PatrolToPosition(vDest) end

---Performs an attack on a target.
---Server only.
---@param hTarget handle
---@param bUseCastAttackOrb boolean
---@param bProcessProcs boolean
---@param bSkipCooldown boolean
---@param bIgnoreInvis boolean
---@param bUseProjectile boolean
---@param bFakeAttack boolean
---@param bNeverMiss boolean
---@return number
function CDOTA_BaseNPC:PerformAttack(hTarget, bUseCastAttackOrb, bProcessProcs, bSkipCooldown, bIgnoreInvis, bUseProjectile, bFakeAttack, bNeverMiss) end

---Pick up a dropped item.
---Server only.
---@param hItem handle
function CDOTA_BaseNPC:PickupDroppedItem(hItem) end

---Pick up a rune.
---Server only.
---@param hItem handle
function CDOTA_BaseNPC:PickupRune(hItem) end

---Play a VCD on the NPC.
---Server only.
---@param pVCD string
function CDOTA_BaseNPC:PlayVCD(pVCD) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:ProvidesVision() end

---(bool RemovePositiveBuffs, bool RemoveDebuffs, bool BuffsCreatedThisFrameOnly, bool RemoveStuns, bool RemoveExceptions)
---Server only.
---@param bRemovePositiveBuffs boolean
---@param bRemoveDebuffs boolean
---@param bFrameOnly boolean
---@param bRemoveStuns boolean
---@param bRemoveExceptions boolean
function CDOTA_BaseNPC:Purge(bRemovePositiveBuffs, bRemoveDebuffs, bFrameOnly, bRemoveStuns, bRemoveExceptions) end

---Queue a response system concept with the TLK_DOTA_CUSTOM concept, after a delay.
---Server only.
---@param flDelay number
---@param hCriteriaTable handle
---@param hCompletionCallbackFn handle
---@param hContext handle
---@param hCallbackInfo handle
function CDOTA_BaseNPC:QueueConcept(flDelay, hCriteriaTable, hCompletionCallbackFn, hContext, hCallbackInfo) end

---Queue a response system concept with the TLK_DOTA_CUSTOM concept, after a delay, for the same team this speaker is on.
---Server only.
---@param flDelay number
---@param hCriteriaTable handle
---@param hCompletionCallbackFn handle
---@param hContext handle
---@param hCallbackInfo handle
function CDOTA_BaseNPC:QueueTeamConcept(flDelay, hCriteriaTable, hCompletionCallbackFn, hContext, hCallbackInfo) end

---Queue a response system concept with the TLK_DOTA_CUSTOM concept, after a delay, for the same team this speaker is on. Is not played for spectators.
---Server only.
---@param flDelay number
---@param hCriteriaTable handle
---@param hCompletionCallbackFn handle
---@param hContext handle
---@param hCallbackInfo handle
function CDOTA_BaseNPC:QueueTeamConceptNoSpectators(flDelay, hCriteriaTable, hCompletionCallbackFn, hContext, hCallbackInfo) end

---Remove an ability from this unit by name.
---Server only.
---@param pszAbilityName string
function CDOTA_BaseNPC:RemoveAbility(pszAbilityName) end

---Remove the passed ability from this unit.
---Server only.
---@param hAbility handle
function CDOTA_BaseNPC:RemoveAbilityByHandle(hAbility) end

---Server only.
---@param pszAbilityName string
function CDOTA_BaseNPC:RemoveAbilityFromIndexByName(pszAbilityName) end

---(int targets [0=all, 1=enemy, 2=ally], bool bNow, bool bPermanent, bool bDeath)
---Server only.
---@param targets integer
---@param bNow boolean
---@param bPermanent boolean
---@param bDeath boolean
function CDOTA_BaseNPC:RemoveAllModifiers(targets, bNow, bPermanent, bDeath) end

---Removes all copies of a modifier.
---Server only.
---@param pszScriptName string
function CDOTA_BaseNPC:RemoveAllModifiersOfName(pszScriptName) end

---Remove the given gesture activity.
---Server only.
---@param nActivity integer
function CDOTA_BaseNPC:RemoveGesture(nActivity) end

---Server only.
---@param hBuff handle
function CDOTA_BaseNPC:RemoveHorizontalMotionController(hBuff) end

---Removes the passed item from this unit's inventory and deletes it.
---Server only.
---@param hItem handle
function CDOTA_BaseNPC:RemoveItem(hItem) end

---Removes a modifier.
---Server only.
---@param pszScriptName string
function CDOTA_BaseNPC:RemoveModifierByName(pszScriptName) end

---Removes a modifier that was cast by the given caster.
---Server only.
---@param pszScriptName string
---@param hCaster handle
function CDOTA_BaseNPC:RemoveModifierByNameAndCaster(pszScriptName, hCaster) end

---Remove the no draw flag.
---Server only.
function CDOTA_BaseNPC:RemoveNoDraw() end

---Server only.
---@param hBuff handle
function CDOTA_BaseNPC:RemoveVerticalMotionController(hBuff) end

---Respawns the target unit if it can be respawned.
---Server only.
function CDOTA_BaseNPC:RespawnUnit() end

---Gets this unit's attack range after all modifiers.
---Server only.
---@return number
function CDOTA_BaseNPC:Script_GetAttackRange() end

---Returns current magical armor value.
---Server only.
---@param inflictor handle
---@return number
function CDOTA_BaseNPC:Script_GetMagicalArmorValue(inflictor) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:Script_IsDeniable() end

---Remove mana from this unit, this can be used for involuntary mana loss, not for mana that is spent.
---Server only.
---@param flMana number
---@param hAbility handle
---@return number
function CDOTA_BaseNPC:Script_ReduceMana(flMana, hAbility) end

---Sells the passed item in this unit's inventory.
---Server only.
---@param hItem handle
function CDOTA_BaseNPC:SellItem(hItem) end

---Set the ability by index.
---Server only.
---@param hAbility handle
---@param iIndex integer
function CDOTA_BaseNPC:SetAbilityByIndex(hAbility, iIndex) end

---Server only.
---@param nRange integer
function CDOTA_BaseNPC:SetAcquisitionRange(nRange) end

---Combat involving this creature will have this weight added to the music calcuations.
---Server only.
---@param flWeight number
function CDOTA_BaseNPC:SetAdditionalBattleMusicWeight(flWeight) end

---Set this unit's aggro target to a specified unit.
---Server only.
---@param hAggroTarget handle
function CDOTA_BaseNPC:SetAggroTarget(hAggroTarget) end

---Server only.
---@param iAttackCapabilities integer
function CDOTA_BaseNPC:SetAttackCapability(iAttackCapabilities) end

---Server only.
---@param hAttackTarget handle
function CDOTA_BaseNPC:SetAttacking(hAttackTarget) end

---Server only.
---@param flBaseAttackTime number
function CDOTA_BaseNPC:SetBaseAttackTime(flBaseAttackTime) end

---Sets the maximum base damage.
---Server only.
---@param nMax integer
function CDOTA_BaseNPC:SetBaseDamageMax(nMax) end

---Sets the minimum base damage.
---Server only.
---@param nMin integer
function CDOTA_BaseNPC:SetBaseDamageMin(nMin) end

---Server only.
---@param flHealthRegen number
function CDOTA_BaseNPC:SetBaseHealthRegen(flHealthRegen) end

---Sets base magical armor value.
---Server only.
---@param flMagicalResistanceValue number
function CDOTA_BaseNPC:SetBaseMagicalResistanceValue(flMagicalResistanceValue) end

---Server only.
---@param flManaRegen number
function CDOTA_BaseNPC:SetBaseManaRegen(flManaRegen) end

---Set a new base max health value.
---Server only.
---@param flBaseMaxHealth number
function CDOTA_BaseNPC:SetBaseMaxHealth(flBaseMaxHealth) end

---Server only.
---@param iMoveSpeed integer
function CDOTA_BaseNPC:SetBaseMoveSpeed(iMoveSpeed) end

---Set whether or not this unit is allowed to sell items (bCanSellItems)
---Server only.
---@param bCanSell boolean
function CDOTA_BaseNPC:SetCanSellItems(bCanSell) end

---Set this unit controllable by all players.
---Server only.
---@param bControllableByAllPlayers boolean
function CDOTA_BaseNPC:SetControllableByAllPlayers(bControllableByAllPlayers) end

---Set this unit controllable by the player with the passed ID.
---Server only.
---@param nPlayerID integer
---@param bSkipAdjustingPosition boolean
function CDOTA_BaseNPC:SetControllableByPlayer(nPlayerID, bSkipAdjustingPosition) end

---Server only.
---@param hEntity handle
function CDOTA_BaseNPC:SetCursorCastTarget(hEntity) end

---Server only.
---@param vLocation any
function CDOTA_BaseNPC:SetCursorPosition(vLocation) end

---Server only.
---@param bTargetingNothing boolean
function CDOTA_BaseNPC:SetCursorTargetingNothing(bTargetingNothing) end

---Server only.
---@param pLabel string
---@param r integer
---@param g integer
---@param b integer
function CDOTA_BaseNPC:SetCustomHealthLabel(pLabel, r, g, b) end

---Set the base vision range.
---Server only.
---@param iRange integer
function CDOTA_BaseNPC:SetDayTimeVisionRange(iRange) end

---Set the XP bounty on this unit.
---Server only.
---@param iXPBounty integer
function CDOTA_BaseNPC:SetDeathXP(iXPBounty) end

---Server only.
---@param flFollowRange number
function CDOTA_BaseNPC:SetFollowRange(flFollowRange) end

---Server only.
---@param hNPC handle
function CDOTA_BaseNPC:SetForceAttackTarget(hNPC) end

---Server only.
---@param hNPC handle
function CDOTA_BaseNPC:SetForceAttackTargetAlly(hNPC) end

---Set if this unit has an inventory.
---Server only.
---@param bHasInventory boolean
function CDOTA_BaseNPC:SetHasInventory(bHasInventory) end

---Server only.
---@param nOffset integer
function CDOTA_BaseNPC:SetHealthBarOffsetOverride(nOffset) end

---Set the collision hull radius of this NPC.
---Server only.
---@param flHullRadius number
function CDOTA_BaseNPC:SetHullRadius(flHullRadius) end

---Server only.
---@param bIdleAcquire boolean
function CDOTA_BaseNPC:SetIdleAcquire(bIdleAcquire) end

---Sets the initial waypoint goal for this NPC.
---Server only.
---@param hGoal handle
function CDOTA_BaseNPC:SetInitialGoalEntity(hGoal) end

---Set waypoint position for this NPC.
---Server only.
---@param vPosition any
function CDOTA_BaseNPC:SetInitialGoalPosition(vPosition) end

---Set the mana on this unit.
---Server only.
---@param flMana number
function CDOTA_BaseNPC:SetMana(flMana) end

---Set the maximum mana of this unit.
---Server only.
---@param flMaxMana number
function CDOTA_BaseNPC:SetMaxMana(flMaxMana) end

---Set the maximum gold bounty for this unit.
---Server only.
---@param iGoldBountyMax integer
function CDOTA_BaseNPC:SetMaximumGoldBounty(iGoldBountyMax) end

---Set the minimum gold bounty for this unit.
---Server only.
---@param iGoldBountyMin integer
function CDOTA_BaseNPC:SetMinimumGoldBounty(iGoldBountyMin) end

---Sets the stack count of a given modifier.
---Server only.
---@param pszScriptName string
---@param hCaster handle
---@param nStackCount integer
function CDOTA_BaseNPC:SetModifierStackCount(pszScriptName, hCaster, nStackCount) end

---Server only.
---@param iMoveCapabilities integer
function CDOTA_BaseNPC:SetMoveCapability(iMoveCapabilities) end

---Set whether this NPC is required to reach each goal entity, rather than being allowed to unkink their path.
---Server only.
---@param must boolean
function CDOTA_BaseNPC:SetMustReachEachGoalEntity(must) end

---If set to true, we will never attempt to move this unit to clear space, even when it unphases.
---Server only.
---@param neverMoveToClearSpace boolean
function CDOTA_BaseNPC:SetNeverMoveToClearSpace(neverMoveToClearSpace) end

---Returns the vision range after modifiers.
---Server only.
---@param iRange integer
function CDOTA_BaseNPC:SetNightTimeVisionRange(iRange) end

---Set the unit's origin.
---Server only.
---@param vLocation any
function CDOTA_BaseNPC:SetOrigin(vLocation) end

---Sets the original model of this entity, which it will tend to fall back to anytime its state changes.
---Server only.
---@param pszModelName string
function CDOTA_BaseNPC:SetOriginalModel(pszModelName) end

---Sets base physical armor value.
---Server only.
---@param flPhysicalArmorValue number
function CDOTA_BaseNPC:SetPhysicalArmorBaseValue(flPhysicalArmorValue) end

---Server only.
---@param pProjectileName string
function CDOTA_BaseNPC:SetRangedProjectileName(pProjectileName) end

---sets the client side map reveal radius for this unit
---Server only.
---@param revealRadius number
function CDOTA_BaseNPC:SetRevealRadius(revealRadius) end

---Server only.
---@param bCompute boolean
function CDOTA_BaseNPC:SetShouldComputeRemainingPathLength(bCompute) end

---Server only.
---@param bShouldVisuallyFly boolean
function CDOTA_BaseNPC:SetShouldDoFlyHeightVisual(bShouldVisuallyFly) end

---Server only.
---@param bStolenScepter boolean
function CDOTA_BaseNPC:SetStolenScepter(bStolenScepter) end

---Server only.
---@param bCanRespawn boolean
function CDOTA_BaseNPC:SetUnitCanRespawn(bCanRespawn) end

---Server only.
---@param pName string
function CDOTA_BaseNPC:SetUnitName(pName) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:ShouldIdleAcquire() end

---Speak a response system concept with the TLK_DOTA_CUSTOM concept.
---Server only.
---@param hCriteriaTable handle
function CDOTA_BaseNPC:SpeakConcept(hCriteriaTable) end

---Spend mana from this unit, this can be used for spending mana from abilities or item usage.
---Server only.
---@param flManaSpent number
---@param hAbility handle
function CDOTA_BaseNPC:SpendMana(flManaSpent, hAbility) end

---Add the given gesture activity.
---Server only.
---@param nActivity integer
function CDOTA_BaseNPC:StartGesture(nActivity) end

---Add the given gesture activity faded according to its sequence settings.
---Server only.
---@param nActivity integer
function CDOTA_BaseNPC:StartGestureFadeWithSequenceSettings(nActivity) end

---Add the given gesture activity faded according to to the parameters.
---Server only.
---@param nActivity integer
---@param fFadeIn number
---@param fFadeOut number
function CDOTA_BaseNPC:StartGestureWithFade(nActivity, fFadeIn, fFadeOut) end

---Add the given gesture activity faded according to to the parameters and with a playback rate override.
---Server only.
---@param nActivity integer
---@param fFadeIn number
---@param fFadeOut number
---@param flRate number
function CDOTA_BaseNPC:StartGestureWithFadeAndPlaybackRate(nActivity, fFadeIn, fFadeOut, flRate) end

---Add the given gesture activity with a playback rate override.
---Server only.
---@param nActivity integer
---@param flRate number
function CDOTA_BaseNPC:StartGestureWithPlaybackRate(nActivity, flRate) end

---Stop the current order.
---Server only.
function CDOTA_BaseNPC:Stop() end

---Server only.
function CDOTA_BaseNPC:StopFacing() end

---Swaps the slots of the two passed abilities and sets them enabled/disabled.
---Server only.
---@param pAbilityName1 string
---@param pAbilityName2 string
---@param bEnable1 boolean
---@param bEnable2 boolean
function CDOTA_BaseNPC:SwapAbilities(pAbilityName1, pAbilityName2, bEnable1, bEnable2) end

---Swap the contents of two item slots (slot1, slot2)
---Server only.
---@param nSlot1 integer
---@param nSlot2 integer
function CDOTA_BaseNPC:SwapItems(nSlot1, nSlot2) end

---Removed the passed item from this unit's inventory.
---Server only.
---@param hItem handle
---@return handle
function CDOTA_BaseNPC:TakeItem(hItem) end

---Server only.
---@return number
function CDOTA_BaseNPC:TimeUntilNextAttack() end

---Server only.
---@param hAbility handle
---@param hBuff handle
---@return boolean
function CDOTA_BaseNPC:TriggerModifierDodge(hAbility, hBuff) end

---Server only.
---@param hAbility handle
---@return boolean
function CDOTA_BaseNPC:TriggerSpellAbsorb(hAbility) end

---Trigger the Lotus Orb-like effect.(hAbility)
---Server only.
---@param hAbility handle
function CDOTA_BaseNPC:TriggerSpellReflect(hAbility) end

---Makes the first ability unhidden, and puts it where second ability currently is. Will do nothing if the first ability is already unhidden and in a valid slot.
---Server only.
---@param pszAbilityName string
---@param pszReplacedAbilityName string
function CDOTA_BaseNPC:UnHideAbilityToSlot(pszAbilityName, pszReplacedAbilityName) end

---Server only.
---@return boolean
function CDOTA_BaseNPC:UnitCanRespawn() end

---Server only.
---@return boolean
function CDOTA_BaseNPC:WasKilledPassively() end
