---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTABaseAbility : CBaseEntity
CDOTABaseAbility = {}

---Server only.
---@return any
function CDOTABaseAbility:CanAbilityBeUpgraded() end

---Server only.
---@return boolean
function CDOTABaseAbility:CastAbility() end

---Server only.
---@return boolean
function CDOTABaseAbility:ContinueCasting() end

---Server only.
---@param vLocation any
---@param fRadius number
---@param fDuration number
function CDOTABaseAbility:CreateVisibilityNode(vLocation, fRadius, fDuration) end

---Server only.
function CDOTABaseAbility:DecrementModifierRefCount() end

---Server only.
---@param hAbility handle
---@param pszTalentName string
function CDOTABaseAbility:EnableAbilityChargesOnTalentUpgrade(hAbility, pszTalentName) end

---Server only.
---@param bInterrupted boolean
function CDOTABaseAbility:EndChannel(bInterrupted) end

---Clear the cooldown remaining on this ability.
---Server only.
function CDOTABaseAbility:EndCooldown() end

---Server only.
---@param nValue integer
function CDOTABaseAbility:ForceSetFrozenCooldown(nValue) end

---Server only.
---@return number
function CDOTABaseAbility:GetAOERadius() end

---Server only.
---@param iLevel integer
---@return number
function CDOTABaseAbility:GetAbilityChargeRestoreTime(iLevel) end

---Server only.
---@return integer
function CDOTABaseAbility:GetAbilityDamage() end

---Server only.
---@return any
function CDOTABaseAbility:GetAbilityDamageType() end

---Server only.
---@return integer
function CDOTABaseAbility:GetAbilityIndex() end

---Gets the key values definition for this ability.
---Server only.
---@return table
function CDOTABaseAbility:GetAbilityKeyValues() end

---Returns the name of this ability.
---Server only.
---@return string
function CDOTABaseAbility:GetAbilityName() end

---Server only.
---@return integer
function CDOTABaseAbility:GetAbilityTargetFlags() end

---Server only.
---@return integer
function CDOTABaseAbility:GetAbilityTargetTeam() end

---Server only.
---@return integer
function CDOTABaseAbility:GetAbilityTargetType() end

---Server only.
---@return integer
function CDOTABaseAbility:GetAbilityType() end

---Gets the current Alt Cast State
---Server only.
---@return boolean
function CDOTABaseAbility:GetAltCastState() end

---Server only.
---@return boolean
function CDOTABaseAbility:GetAnimationIgnoresModelScale() end

---Server only.
---@return string
function CDOTABaseAbility:GetAssociatedPrimaryAbilities() end

---Server only.
---@return string
function CDOTABaseAbility:GetAssociatedSecondaryAbilities() end

---Server only.
---@return boolean
function CDOTABaseAbility:GetAutoCastState() end

---Server only.
---@return number
function CDOTABaseAbility:GetBackswingTime() end

---Server only.
---@return number
function CDOTABaseAbility:GetBehavior() end

---Get ability behavior flags as an int for compatability.
---Server only.
---@return integer
function CDOTABaseAbility:GetBehaviorInt() end

---Server only.
---@return number
function CDOTABaseAbility:GetCastPoint() end

---Server only.
---@return number
function CDOTABaseAbility:GetCastPointModifier() end

---Gets the cast range of the ability.
---Server only.
---@param vLocation any
---@param hTarget handle
---@return integer
function CDOTABaseAbility:GetCastRange(vLocation, hTarget) end

---Server only.
function CDOTABaseAbility:GetCastRange_Engine(...) end

---Server only.
---@return handle
function CDOTABaseAbility:GetCaster() end

---Server only.
---@return number
function CDOTABaseAbility:GetChannelStartTime() end

---Server only.
---@return number
function CDOTABaseAbility:GetChannelTime() end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetChannelledHealthCostPerSecond(iLevel) end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetChannelledManaCostPerSecond(iLevel) end

---Server only.
---@return handle
function CDOTABaseAbility:GetCloneSource() end

---Server only.
---@return integer
function CDOTABaseAbility:GetConceptRecipientType() end

---Get the cooldown duration for this ability at a given level, not the amount of cooldown actually left.
---Server only.
---@param iLevel integer
---@return number
function CDOTABaseAbility:GetCooldown(iLevel) end

---Server only.
---@return number
function CDOTABaseAbility:GetCooldownTime() end

---Server only.
---@return number
function CDOTABaseAbility:GetCooldownTimeRemaining() end

---Server only.
---@return integer
function CDOTABaseAbility:GetCurrentAbilityCharges() end

---Server only.
---@return any
function CDOTABaseAbility:GetCursorPosition() end

---Server only.
---@return handle
function CDOTABaseAbility:GetCursorTarget() end

---Server only.
---@return boolean
function CDOTABaseAbility:GetCursorTargetingNothing() end

---Server only.
---@return number
function CDOTABaseAbility:GetDuration() end

---Gets the cast range of the ability, taking modifiers into account.
---Server only.
---@param vLocation any
---@param hTarget handle
---@return integer
function CDOTABaseAbility:GetEffectiveCastRange(vLocation, hTarget) end

---Server only.
---@param iLevel integer
---@return number
function CDOTABaseAbility:GetEffectiveCooldown(iLevel) end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetEffectiveHealthCost(iLevel) end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetEffectiveManaCost(iLevel) end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetGoldCost(iLevel) end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetGoldCostForUpgrade(iLevel) end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetHealthCost(iLevel) end

---Server only.
---@return integer
function CDOTABaseAbility:GetHeroLevelRequiredToUpgrade() end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetInitialAbilityCharges(iLevel) end

---Server only.
---@return string
function CDOTABaseAbility:GetIntrinsicModifierName() end

---Get the current level of the ability.
---Server only.
---@return integer
function CDOTABaseAbility:GetLevel() end

---Server only.
---@param szName string
---@param nLevel integer
---@return table
function CDOTABaseAbility:GetLevelSpecialValueFor(szName, nLevel) end

---Server only.
---@param szName string
---@param nLevel integer
---@return table
function CDOTABaseAbility:GetLevelSpecialValueNoOverride(szName, nLevel) end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetManaCost(iLevel) end

---Server only.
---@param iLevel integer
---@return integer
function CDOTABaseAbility:GetMaxAbilityCharges(iLevel) end

---Server only.
---@return integer
function CDOTABaseAbility:GetMaxLevel() end

---Server only.
---@return number
function CDOTABaseAbility:GetModifierValue() end

---Server only.
---@return number
function CDOTABaseAbility:GetModifierValueBonus() end

---Server only.
---@return number
function CDOTABaseAbility:GetPlaybackRateOverride() end

---Server only.
---@return string
function CDOTABaseAbility:GetSharedCooldownName() end

---Gets a value from this ability's special value block for its current level.
---Server only.
---@param szName string
---@return table
function CDOTABaseAbility:GetSpecialValueFor(szName) end

---Server only.
---@return string
function CDOTABaseAbility:GetStolenActivityModifier() end

---Server only.
---@return boolean
function CDOTABaseAbility:GetToggleState() end

---Server only.
---@return boolean
function CDOTABaseAbility:GetUpgradeRecommended() end

---Server only.
---@param flXP number
---@return boolean
function CDOTABaseAbility:HeroXPChange(flXP) end

---Server only.
function CDOTABaseAbility:IncrementModifierRefCount() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsActivated() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsAttributeBonus() end

---Returns whether the ability is currently channeling.
---Server only.
---@return boolean
function CDOTABaseAbility:IsChanneling() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsCooldownReady() end

---Server only.
---@param hEntity handle
---@return boolean
function CDOTABaseAbility:IsCosmetic(hEntity) end

---Server only.
function CDOTABaseAbility:IsCosmetic_Engine(...) end

---Returns whether the ability can be cast.
---Server only.
---@return boolean
function CDOTABaseAbility:IsFullyCastable() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsHidden() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsHiddenAsSecondaryAbility() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsHiddenWhenStolen() end

---Returns whether the ability is currently casting.
---Server only.
---@return boolean
function CDOTABaseAbility:IsInAbilityPhase() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsItem() end

---Server only.
function CDOTABaseAbility:IsNull(...) end

---Server only.
---@param nIssuerPlayerID integer
---@return boolean
function CDOTABaseAbility:IsOwnersGoldEnough(nIssuerPlayerID) end

---Server only.
---@return boolean
function CDOTABaseAbility:IsOwnersGoldEnoughForUpgrade() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsOwnersManaEnough() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsPassive() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsRefreshable() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsSharedWithTeammates() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsStealable() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsStolen() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsToggle() end

---Server only.
---@return boolean
function CDOTABaseAbility:IsTrained() end

---Mark the ability button for this ability as needing a refresh.
---Server only.
function CDOTABaseAbility:MarkAbilityButtonDirty() end

---Server only.
---@return integer
function CDOTABaseAbility:NumModifiersUsingAbility() end

---Server only.
function CDOTABaseAbility:OnAbilityPhaseInterrupted() end

---Server only.
---@return boolean
function CDOTABaseAbility:OnAbilityPhaseStart() end

---Server only.
---@param nPlayerID integer
---@param bCtrlHeld boolean
function CDOTABaseAbility:OnAbilityPinged(nPlayerID, bCtrlHeld) end

---Server only.
---@param bInterrupted boolean
function CDOTABaseAbility:OnChannelFinish(bInterrupted) end

---Server only.
---@param flInterval number
function CDOTABaseAbility:OnChannelThink(flInterval) end

---Server only.
function CDOTABaseAbility:OnHeroCalculateStatBonus() end

---Server only.
function CDOTABaseAbility:OnHeroLevelUp() end

---Server only.
function CDOTABaseAbility:OnOwnerDied() end

---Server only.
function CDOTABaseAbility:OnOwnerSpawned() end

---Server only.
function CDOTABaseAbility:OnSpellStart() end

---Server only.
function CDOTABaseAbility:OnToggle() end

---Server only.
function CDOTABaseAbility:OnUpgrade() end

---Server only.
function CDOTABaseAbility:PayGoldCost() end

---Server only.
function CDOTABaseAbility:PayGoldCostForUpgrade() end

---Server only.
function CDOTABaseAbility:PayHealthCost() end

---Server only.
function CDOTABaseAbility:PayManaCost() end

---Server only.
---@return boolean
function CDOTABaseAbility:PlaysDefaultAnimWhenStolen() end

---Server only.
---@return boolean
function CDOTABaseAbility:ProcsMagicStick() end

---Server only.
---@return boolean
function CDOTABaseAbility:RefCountsModifiers() end

---Server only.
function CDOTABaseAbility:RefreshAbilityValues() end

---Server only.
function CDOTABaseAbility:RefreshCharges() end

---Server only.
function CDOTABaseAbility:RefreshIntrinsicModifier() end

---Server only.
function CDOTABaseAbility:RefundHealthCost() end

---Server only.
function CDOTABaseAbility:RefundManaCost() end

---Server only.
---@return boolean
function CDOTABaseAbility:RequiresFacing() end

---Server only.
---@return boolean
function CDOTABaseAbility:ResetToggleOnRespawn() end

---Server only.
---@param iIndex integer
function CDOTABaseAbility:SetAbilityIndex(iIndex) end

---Server only.
---@param bActivated boolean
function CDOTABaseAbility:SetActivated(bActivated) end

---Set Alt Cast State to a specific value (true for on, false for off)
---Server only.
---@param bAltCastEnabled boolean
function CDOTABaseAbility:SetAltCastState(bAltCastEnabled) end

---Server only.
---@param bChanneling boolean
function CDOTABaseAbility:SetChanneling(bChanneling) end

---Server only.
---@param nCharges integer
function CDOTABaseAbility:SetCurrentAbilityCharges(nCharges) end

---Server only.
---@param bFrozenCooldown boolean
function CDOTABaseAbility:SetFrozenCooldown(bFrozenCooldown) end

---Server only.
---@param bHidden boolean
function CDOTABaseAbility:SetHidden(bHidden) end

---Server only.
---@param bInAbilityPhase boolean
function CDOTABaseAbility:SetInAbilityPhase(bInAbilityPhase) end

---Sets the level of this ability.
---Server only.
---@param iLevel integer
function CDOTABaseAbility:SetLevel(iLevel) end

---Server only.
---@param flCastPoint number
function CDOTABaseAbility:SetOverrideCastPoint(flCastPoint) end

---Server only.
---@param bRefCounts boolean
function CDOTABaseAbility:SetRefCountsModifiers(bRefCounts) end

---Server only.
---@param bStealable boolean
function CDOTABaseAbility:SetStealable(bStealable) end

---Server only.
---@param bStolen boolean
function CDOTABaseAbility:SetStolen(bStolen) end

---Server only.
---@param bUpgradeRecommended boolean
function CDOTABaseAbility:SetUpgradeRecommended(bUpgradeRecommended) end

---This is what the Alt Cast State of the ability was when it was initially cast. Updated during Execute Orders
---Server only.
---@return boolean
function CDOTABaseAbility:ShouldAltCast() end

---Server only.
---@return boolean
function CDOTABaseAbility:ShouldUseResources() end

---Server only.
---@param iConcept integer
function CDOTABaseAbility:SpeakAbilityConcept(iConcept) end

---Server only.
---@return any
function CDOTABaseAbility:SpeakTrigger() end

---Server only.
---@param flCooldown number
function CDOTABaseAbility:StartCooldown(flCooldown) end

---Server only.
function CDOTABaseAbility:ToggleAbility() end

---Toggle the Alt Cast State of an Ability
---Server only.
function CDOTABaseAbility:ToggleAltCast() end

---Server only.
function CDOTABaseAbility:ToggleAutoCast() end

---Server only.
---@param bSupressSpeech boolean
function CDOTABaseAbility:UpgradeAbility(bSupressSpeech) end

---Server only.
---@param bMana boolean
---@param bUseHealth boolean
---@param bGold boolean
---@param bCooldown boolean
function CDOTABaseAbility:UseResources(bMana, bUseHealth, bGold, bCooldown) end
