---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Unit_Scout : CDOTA_BaseNPC
CDOTA_Unit_Scout = {}

---Server only.
function CDOTA_Unit_Scout:IsNull(...) end
