---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Ability_Animation_TailSpin : CDOTABaseAbility
CDOTA_Ability_Animation_TailSpin = {}

---Server only.
function CDOTA_Ability_Animation_TailSpin:IsNull(...) end

---Override playbackrate
---Server only.
---@param flRate number
function CDOTA_Ability_Animation_TailSpin:SetPlaybackRate(flRate) end
