---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTAGameRules
CDOTAGameRules = CDOTAGameRules

---Spawn a bot player of the passed hero name, player name, and team.
---Server only.
---@param string_1 string
---@param string_2 string
---@param int_3 integer
---@param string_4 string
---@param bool_5 boolean
---@return handle
function CDOTAGameRules:AddBotPlayerWithEntityScript(string_1, string_2, int_3, string_4, bool_5) end

---Event-only ( string szNameSuffix, int nStars, int nMaxStars, int nExtraData1, int nExtraData2 )
---Server only.
---@param string_1 string
---@param unsigned_2 integer
---@param unsigned_3 integer
---@param unsigned_4 integer
---@param unsigned_5 integer
---@param unsigned_6 integer
---@param unsigned_7 integer
---@param unsigned_8 integer
---@param unsigned_9 integer
---@return boolean
function CDOTAGameRules:AddEventMetadataLeaderboardEntry(string_1, unsigned_2, unsigned_3, unsigned_4, unsigned_5, unsigned_6, unsigned_7, unsigned_8, unsigned_9) end

---Event-only ( string szNameSuffix, int nScore, int nExtraData1, int nExtraData2 )
---Server only.
---@param string_1 string
---@param unsigned_2 integer
---@param unsigned_3 integer
---@param unsigned_4 integer
---@param unsigned_5 integer
---@param unsigned_6 integer
---@param unsigned_7 integer
---@param unsigned_8 integer
---@return boolean
function CDOTAGameRules:AddEventMetadataLeaderboardEntryRawScore(string_1, unsigned_2, unsigned_3, unsigned_4, unsigned_5, unsigned_6, unsigned_7, unsigned_8) end

---Add the hero ID to the hero blacklist if it is not already present
---Server only.
---@param int_1 integer
function CDOTAGameRules:AddHeroIDToBlacklist(int_1) end

---Add the hero ID to the hero whitelist if it is not already present
---Server only.
---@param int_1 integer
function CDOTAGameRules:AddHeroIDToWhitelist(int_1) end

---Add the hero to the hero blacklist if it is not already present
---Server only.
---@param string_1 string
function CDOTAGameRules:AddHeroToBlacklist(string_1) end

---Adds hero of given ID to available heroes of player of given ID
---Server only.
---@param int_1 integer
---@param int_2 integer
function CDOTAGameRules:AddHeroToPlayerAvailability(int_1, int_2) end

---Add the hero to the hero whitelist if it is not already present
---Server only.
---@param string_1 string
function CDOTAGameRules:AddHeroToWhitelist(string_1) end

---Add an item to the whitelist
---Server only.
---@param string_1 string
function CDOTAGameRules:AddItemToWhiteList(string_1) end

---Add a point on the minimap.
---Server only.
---@param int_1 integer
---@param unknown_2 any
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
---@param int_6 integer
---@param float_7 number
function CDOTAGameRules:AddMinimapDebugPoint(int_1, unknown_2, int_3, int_4, int_5, int_6, float_7) end

---Add a point on the minimap for a specific team.
---Server only.
---@param int_1 integer
---@param unknown_2 any
---@param int_3 integer
---@param int_4 integer
---@param int_5 integer
---@param int_6 integer
---@param float_7 number
---@param int_8 integer
function CDOTAGameRules:AddMinimapDebugPointForTeam(int_1, unknown_2, int_3, int_4, int_5, int_6, float_7, int_8) end

---Begin night stalker night.
---Server only.
---@param float_1 number
function CDOTAGameRules:BeginNightstalkerNight(float_1) end

---Begin temporary night.
---Server only.
---@param float_1 number
---@param int_2 integer
function CDOTAGameRules:BeginTemporaryNight(float_1, int_2) end

---Fills all the teams with bots if cheat mode is enabled.
---Server only.
function CDOTAGameRules:BotPopulate() end

---Clears the hero blacklist
---Server only.
function CDOTAGameRules:ClearHeroBlacklist() end

---Clears the hero whitelist
---Server only.
function CDOTAGameRules:ClearHeroWhitelist() end

---Clears available heroes of player of given ID
---Server only.
---@param int_1 integer
function CDOTAGameRules:ClearPlayerHeroAvailability(int_1) end

---Clears the current river paint
---Server only.
function CDOTAGameRules:ClearRiverPaint() end

---Kills the ancient, etc.
---Server only.
function CDOTAGameRules:Defeated() end

---true when we have waited some time after end of the game and not received signout
---Server only.
---@return boolean
function CDOTAGameRules:DidMatchSignoutTimeOut() end

---Enabled (true) or disable (false) auto launch for custom game setup.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:EnableCustomGameSetupAutoLaunch(bool_1) end

---Sends a minimap ping to all players on the team
---Server only.
---@param int_1 integer
---@param float_2 number
---@param float_3 number
---@param handle_4 handle
---@param unsigned_5 integer
function CDOTAGameRules:ExecuteTeamPing(int_1, float_2, float_3, handle_4, unsigned_5) end

---Indicate that the custom game setup phase is complete, and advance to the game.
---Server only.
function CDOTAGameRules:FinishCustomGameSetup() end

---Spawn the next wave of creeps.
---Server only.
function CDOTAGameRules:ForceCreepSpawn() end

---Transition game state to DOTA_GAMERULES_STATE_GAME_IN_PROGRESS
---Server only.
function CDOTAGameRules:ForceGameStart() end

---Get the announcer for a team
---Server only.
---@param int_1 integer
---@return handle
function CDOTAGameRules:GetAnnouncer(int_1) end

---Get whether a team is selectable during game setup
---Server only.
---@param int_1 integer
---@return integer
function CDOTAGameRules:GetCustomGameTeamMaxPlayers(int_1) end

---Gets the Xth dropped item
---Server only.
---@param int_1 integer
---@return handle
function CDOTAGameRules:GetDroppedItem(int_1) end

---Get the game mode entity
---Server only.
---@return handle
function CDOTAGameRules:GetGameModeEntity() end

---Get a string value from the game session config (map options)
---Server only.
---@param string_1 string
---@param string_2 string
---@return string
function CDOTAGameRules:GetGameSessionConfigValue(string_1, string_2) end

---Have we received the post match signout message that includes reward information
---Server only.
---@return boolean
function CDOTAGameRules:GetMatchSignoutComplete() end

---Gets next bounty rune spawn time
---Server only.
---@return number
function CDOTAGameRules:GetNextBountyRuneSpawnTime() end

---Gets next rune spawn time
---Server only.
---@return number
function CDOTAGameRules:GetNextRuneSpawnTime() end

---For New Bloom, get total damage taken by the Nian / Year Beast
---Server only.
---@return integer
function CDOTAGameRules:GetNianTotalDamageTaken() end

---(Preview/Unreleased) Gets the player's custom game account record, as it looked at the start of this session
---Server only.
---@param int_1 integer
---@return table
function CDOTAGameRules:GetPlayerCustomGameAccountRecord(int_1) end

---Get time remaining between state changes.
---Server only.
---@return number
function CDOTAGameRules:GetStateTransitionTime() end

---Get the time of day
---Server only.
---@return number
function CDOTAGameRules:GetTimeOfDay() end

---Increase an item's stock count, clamped to item max (nTeamNumber, szItemName, nCount, nPlayerID .
---Server only.
---@param int_1 integer
---@param string_2 string
---@param int_3 integer
---@param int_4 integer
function CDOTAGameRules:IncreaseItemStock(int_1, string_2, int_3, int_4) end

---Is it day time?
---Server only.
---@return boolean
function CDOTAGameRules:IsDaytime() end

---Returns whether the game is paused.
---Server only.
---@return boolean
function CDOTAGameRules:IsGamePaused() end

---Returns whether hero respawn is enabled.
---Server only.
---@return boolean
function CDOTAGameRules:IsHeroRespawnEnabled() end

---Are we in the ban phase of hero pick?
---Server only.
---@return boolean
function CDOTAGameRules:IsInBanPhase() end

---Query an item in the whitelist
---Server only.
---@param string_1 string
---@return boolean
function CDOTAGameRules:IsItemInWhiteList(string_1) end

---Is it night stalker night-time?
---Server only.
---@return boolean
function CDOTAGameRules:IsNightstalkerNight() end

---Returns whether Dota Plus ability suggestions are enabled or disabled
---Server only.
---@return boolean
function CDOTAGameRules:IsSuggestAbilitiesEnabled() end

---Returns whether Dota Plus item suggestions are enabled or disabled
---Server only.
---@return boolean
function CDOTAGameRules:IsSuggestItemsEnabled() end

---Is it temporarily night-time?
---Server only.
---@return boolean
function CDOTAGameRules:IsTemporaryNight() end

---Lock (true) or unlock (false) team assignemnt. If team assignment is locked players cannot change teams.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:LockCustomGameSetupTeamAssignment(bool_1) end

---Makes the specified team lose
---Server only.
---@param int_1 integer
function CDOTAGameRules:MakeTeamLose(int_1) end

---Like ModifyGold, but will use the gold filter if SetFilterMoreGold has been set true
---Server only.
---@param int_1 integer
---@param int_2 integer
---@param bool_3 boolean
---@param int_4 integer
---@return integer
function CDOTAGameRules:ModifyGoldFiltered(int_1, int_2, bool_3, int_4) end

---Returns the number of items currently dropped on the ground
---Server only.
---@return integer
function CDOTAGameRules:NumDroppedItems() end

---Whether a player has custom game host privileges (shuffle teams, etc.)
---Server only.
---@param handle_1 handle
---@return boolean
function CDOTAGameRules:PlayerHasCustomGameHostPrivileges(handle_1) end

---Updates custom hero, unit and ability KeyValues in memory with the latest values from disk
---Server only.
function CDOTAGameRules:Playtesting_UpdateAddOnKeyValues() end

---Prepare Dota lane style spawners with a given interval
---Server only.
---@param float_1 number
function CDOTAGameRules:PrepareSpawners(float_1) end

---Removes a fake client
---Server only.
---@param int_1 integer
function CDOTAGameRules:RemoveFakeClient(int_1) end

---Remove the hero from the hero blacklist if present
---Server only.
---@param string_1 string
function CDOTAGameRules:RemoveHeroFromBlacklist(string_1) end

---Remove the hero from the hero whitelist if present
---Server only.
---@param string_1 string
function CDOTAGameRules:RemoveHeroFromWhitelist(string_1) end

---Remove the hero ID from the hero blacklist if present
---Server only.
---@param int_1 integer
function CDOTAGameRules:RemoveHeroIDFromBlacklist(int_1) end

---Remove the hero ID from the hero whitelist if present
---Server only.
---@param int_1 integer
function CDOTAGameRules:RemoveHeroIDFromWhitelist(int_1) end

---Remove an item from the whitelist
---Server only.
---@param string_1 string
function CDOTAGameRules:RemoveItemFromWhiteList(string_1) end

---Restart after killing the ancient, etc.
---Server only.
function CDOTAGameRules:ResetDefeated() end

---Restart gametime from 0
---Server only.
function CDOTAGameRules:ResetGameTime() end

---Resets the player of a given ID.
---Server only.
---@param int_1 integer
function CDOTAGameRules:ResetPlayer(int_1) end

---Restart at custom game setup.
---Server only.
function CDOTAGameRules:ResetToCustomGameSetup() end

---Restart the game at hero selection
---Server only.
function CDOTAGameRules:ResetToHeroSelection() end

---Get the MatchID for this game.
---Server only.
---@return any
function CDOTAGameRules:Script_GetMatchID() end

---Sends a message on behalf of a player.
---Server only.
---@param string_1 string
---@param int_2 integer
---@param int_3 integer
function CDOTAGameRules:SendCustomMessage(string_1, int_2, int_3) end

---Sends a message on behalf of a player to the specified team.
---Server only.
---@param string_1 string
---@param int_2 integer
---@param int_3 integer
---@param int_4 integer
function CDOTAGameRules:SendCustomMessageToTeam(string_1, int_2, int_3, int_4) end

---Allow Outposts granting XP
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetAllowOutpostBonuses(bool_1) end

---(flMinimapCreepIconScale) - Scale the creep icons on the minimap.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetCreepMinimapIconScale(float_1) end

---Sets whether the regular Dota creeps spawn.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetCreepSpawningEnabled(bool_1) end

---(Preview/Unreleased) Sets a callback to handle saving custom game account records (callback is passed a Player ID and should return a flat simple table)
---Server only.
---@param handle_1 handle
---@param handle_2 handle
function CDOTAGameRules:SetCustomGameAccountRecordSaveFunction(handle_1, handle_2) end

---Sets a flag to enable/disable the default music handling code for custom games
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetCustomGameAllowBattleMusic(bool_1) end

---Sets a flag to enable/disable the default music handling code for custom games
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetCustomGameAllowHeroPickMusic(bool_1) end

---Sets a flag to enable/disable the default music handling code for custom games
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetCustomGameAllowMusicAtGameStart(bool_1) end

---Sets a flag to enable/disable the casting secondary abilities from units other than the player's own hero.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetCustomGameAllowSecondaryAbilitiesOnOtherUnits(bool_1) end

---Set number of hero bans each team gets
---Server only.
---@param int_1 integer
function CDOTAGameRules:SetCustomGameBansPerTeam(int_1) end

---Set the difficulty level of the custom game mode
---Server only.
---@param int_1 integer
function CDOTAGameRules:SetCustomGameDifficulty(int_1) end

---Sets the game end delay.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetCustomGameEndDelay(float_1) end

---Set the amount of time to wait for auto launch.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetCustomGameSetupAutoLaunchDelay(float_1) end

---Set the amount of remaining time, in seconds, for custom game setup. 0 = finish immediately, -1 = wait forever
---Server only.
---@param float_1 number
function CDOTAGameRules:SetCustomGameSetupRemainingTime(float_1) end

---Setup (pre-gameplay) phase timeout. 0 = instant, -1 = forever (until FinishCustomGameSetup is called)
---Server only.
---@param float_1 number
function CDOTAGameRules:SetCustomGameSetupTimeout(float_1) end

---Set whether a team is selectable during game setup
---Server only.
---@param int_1 integer
---@param int_2 integer
function CDOTAGameRules:SetCustomGameTeamMaxPlayers(int_1, int_2) end

---Sets the victory message.
---Server only.
---@param string_1 string
function CDOTAGameRules:SetCustomVictoryMessage(string_1) end

---Sets the victory message duration.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetCustomVictoryMessageDuration(float_1) end

---Allow alternate hero grids to be used (DOTA+, etc).  True by default.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetEnableAlternateHeroGrids(bool_1) end

---Event-only ( table hMetadataTable )
---Server only.
---@param handle_1 handle
---@return boolean
function CDOTAGameRules:SetEventMetadataCustomTable(handle_1) end

---Event-only ( table hMetadataTable )
---Server only.
---@param handle_1 handle
---@return boolean
function CDOTAGameRules:SetEventSignoutCustomTable(handle_1) end

---Sets whether to filter more gold events than normal
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetFilterMoreGold(bool_1) end

---Sets whether First Blood has been triggered.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetFirstBloodActive(bool_1) end

---Makes the specified team win
---Server only.
---@param int_1 integer
function CDOTAGameRules:SetGameWinner(int_1) end

---Set Glyph cooldown for team
---Server only.
---@param int_1 integer
---@param float_2 number
function CDOTAGameRules:SetGlyphCooldown(int_1, float_2) end

---Set the auto gold increase per timed interval.
---Server only.
---@param int_1 integer
function CDOTAGameRules:SetGoldPerTick(int_1) end

---Set the time interval between auto gold increases.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetGoldTickTime(float_1) end

---(flMinimapHeroIconScale) - Scale the hero minimap icons on the minimap.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetHeroMinimapIconScale(float_1) end

---Control if the normal DOTA hero respawn rules apply.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetHeroRespawnEnabled(bool_1) end

---Sets amount of penalty time before randoming a hero
---Server only.
---@param float_1 number
function CDOTAGameRules:SetHeroSelectPenaltyTime(float_1) end

---Sets the amount of time players have to pick their hero.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetHeroSelectionTime(float_1) end

---Should blacklisted heroes be hidden, or just dimmed, in hero picking?
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetHideBlacklistedHeroes(bool_1) end

---Sets whether the multikill, streak, and first-blood banners appear at the top of the screen.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetHideKillMessageHeaders(bool_1) end

---Set whether custom and event games should ignore Lobby teams when assigning players to teams. Defaults to true.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetIgnoreLobbyTeamsInCustomGame(bool_1) end

---Set the stock count of the item
---Server only.
---@param int_1 integer
---@param int_2 integer
---@param string_3 string
---@param int_4 integer
function CDOTAGameRules:SetItemStockCount(int_1, int_2, string_3, int_4) end

---Sets the extra offset to initial neutral creep spawn delay
---Server only.
---@param float_1 number
function CDOTAGameRules:SetNeutralInitialSpawnOffset(float_1) end

---Sets next bounty rune spawn time
---Server only.
---@param float_1 number
function CDOTAGameRules:SetNextBountyRuneSpawnTime(float_1) end

---Sets next rune spawn time
---Server only.
---@param float_1 number
function CDOTAGameRules:SetNextRuneSpawnTime(float_1) end

---Show this unit's health on the overlay health bar
---Server only.
---@param handle_1 handle
---@param int_2 integer
function CDOTAGameRules:SetOverlayHealthBarUnit(handle_1, int_2) end

---Set columns to show in post game
---Server only.
---@param handle_1 handle
---@return boolean
function CDOTAGameRules:SetPostGameColumns(handle_1) end

---Configure post game to be single or double column layout
---Server only.
---@param int_1 integer
function CDOTAGameRules:SetPostGameLayout(int_1) end

---Set score value for each team. First element is for DOTA_TEAM_GOODGUYS.
---Server only.
---@param handle_1 handle
---@return boolean
function CDOTAGameRules:SetPostGameTeamScores(handle_1) end

---Sets the amount of time players have between the game ending and the server disconnecting them.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetPostGameTime(float_1) end

---Sets the amount of time players have between picking their hero and game start.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetPreGameTime(float_1) end

---Paints the river for a duration
---Server only.
---@param int_1 integer
---@param float_2 number
function CDOTAGameRules:SetRiverPaint(int_1, float_2) end

---(flMinimapRuneIconScale) - Scale the rune icons on the minimap.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetRuneMinimapIconScale(float_1) end

---Sets the amount of time between rune spawns.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetRuneSpawnTime(float_1) end

---(bSafeToLeave) - Mark this game as safe to leave.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetSafeToLeave(bool_1) end

---When true, players can repeatedly pick the same hero.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetSameHeroSelectionEnabled(bool_1) end

---Sets the amount of time players have between the strategy phase and entering the pre-game phase.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetShowcaseTime(float_1) end

---Set whether to speak a Spawn concept instead of a Respawn concept on respawn.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetSpeechUseSpawnInsteadOfRespawnConcept(bool_1) end

---Set the starting gold amount.
---Server only.
---@param int_1 integer
function CDOTAGameRules:SetStartingGold(int_1) end

---Sets the amount of time players have between the hero selection and entering the showcase phase.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetStrategyTime(float_1) end

---Sets Dota Plus ability suggestions enabled or disabled
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetSuggestAbilitiesEnabled(bool_1) end

---Sets Dota Plus ability item enabled or disabled
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetSuggestItemsEnabled(bool_1) end

---Set the time of day.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetTimeOfDay(float_1) end

---Sets the tree regrow time in seconds.
---Server only.
---@param float_1 number
function CDOTAGameRules:SetTreeRegrowTime(float_1) end

---Heroes will use the basic NPC functionality for determining their bounty, rather than DOTA specific formulas.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetUseBaseGoldBountyOnHeroes(bool_1) end

---Allows heroes in the map to give a specific amount of XP (this value must be set).
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetUseCustomHeroXPValues(bool_1) end

---When true, all items are available at as long as any shop is in range.
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetUseUniversalShopMode(bool_1) end

---Set Weather Wind Direction Vector
---Server only.
---@param Vector_1 Vector
function CDOTAGameRules:SetWeatherWindDirection(Vector_1) end

---Item whitelist functionality enable/disable
---Server only.
---@param bool_1 boolean
function CDOTAGameRules:SetWhiteListEnabled(bool_1) end

---Spawn and release the next creep wave from Dota lane style spawners.
---Server only.
function CDOTAGameRules:SpawnAndReleaseCreeps() end

---Spawn and release the next set of neutral camps.
---Server only.
function CDOTAGameRules:SpawnNeutralCreeps() end
