---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC_Watch_Tower : CDOTA_BaseNPC_Building
CDOTA_BaseNPC_Watch_Tower = {}

---The name of the ability used when triggering interaction on the outpost.
---Server only.
---@return string
function CDOTA_BaseNPC_Watch_Tower:GetInteractAbilityName() end

---Server only.
function CDOTA_BaseNPC_Watch_Tower:IsNull(...) end

---The name of the ability used when triggering interaction on the outpost.
---Server only.
---@param pszInteractAbilityName string
function CDOTA_BaseNPC_Watch_Tower:SetInteractAbilityName(pszInteractAbilityName) end
