---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC_NeutralItemStash : CDOTA_BaseNPC_Building
CDOTA_BaseNPC_NeutralItemStash = {}

---Server only.
function CDOTA_BaseNPC_NeutralItemStash:IsNull(...) end
