---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC_Trap_Ward : CDOTA_BaseNPC_Creature
CDOTA_BaseNPC_Trap_Ward = {}

---Get the trap target for this entity.
---Server only.
---@return any
function CDOTA_BaseNPC_Trap_Ward:GetTrapTarget() end

---Server only.
function CDOTA_BaseNPC_Trap_Ward:IsNull(...) end

---Set the animation sequence for this entity.
---Server only.
---@param pAnimation string
function CDOTA_BaseNPC_Trap_Ward:SetAnimation(pAnimation) end
