---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC_Creature : CDOTA_BaseNPC
CDOTA_BaseNPC_Creature = {}

---Add the specified item drop to this creature.
---Server only.
---@param hDropData handle
function CDOTA_BaseNPC_Creature:AddItemDrop(hDropData) end

---Level the creature up by the specified number of levels
---Server only.
---@param iLevels integer
function CDOTA_BaseNPC_Creature:CreatureLevelUp(iLevels) end

---Set creature's current disable resistance
---Server only.
---@return number
function CDOTA_BaseNPC_Creature:GetDisableResistance() end

---Set creature's current disable resistance from ultimates
---Server only.
---@return number
function CDOTA_BaseNPC_Creature:GetUltimateDisableResistance() end

---Is this unit a champion?
---Server only.
---@return boolean
function CDOTA_BaseNPC_Creature:IsChampion() end

---Server only.
function CDOTA_BaseNPC_Creature:IsNull(...) end

---Is this creature respawning?
---Server only.
---@return boolean
function CDOTA_BaseNPC_Creature:IsReincarnating() end

---Remove all item drops from this creature.
---Server only.
function CDOTA_BaseNPC_Creature:RemoveAllItemDrops() end

---Does this creature aggro on the owner of the attacking unit when taking damage?
---Server only.
---@param bAggro boolean
function CDOTA_BaseNPC_Creature:SetAggroOnOwnerOnDamage(bAggro) end

---Set the armor gained per level on this creature.
---Server only.
---@param flArmorGain number
function CDOTA_BaseNPC_Creature:SetArmorGain(flArmorGain) end

---Set the attack time gained per level on this creature.
---Server only.
---@param flAttackTimeGain number
function CDOTA_BaseNPC_Creature:SetAttackTimeGain(flAttackTimeGain) end

---Set the bounty gold gained per level on this creature.
---Server only.
---@param nBountyGain integer
function CDOTA_BaseNPC_Creature:SetBountyGain(nBountyGain) end

---Flag this unit as a champion creature.
---Server only.
---@param bIsChampion boolean
function CDOTA_BaseNPC_Creature:SetChampion(bIsChampion) end

---Set the damage gained per level on this creature.
---Server only.
---@param nDamageGain integer
function CDOTA_BaseNPC_Creature:SetDamageGain(nDamageGain) end

---Set creature's current disable resistance
---Server only.
---@param flDisableResistance number
function CDOTA_BaseNPC_Creature:SetDisableResistance(flDisableResistance) end

---Set the disable resistance gained per level on this creature.
---Server only.
---@param flDisableResistanceGain number
function CDOTA_BaseNPC_Creature:SetDisableResistanceGain(flDisableResistanceGain) end

---Switches visible econ item group.
---Server only.
---@param nGroup integer
function CDOTA_BaseNPC_Creature:SetEconItemGroup(nGroup) end

---Set the hit points gained per level on this creature.
---Server only.
---@param nHPGain integer
function CDOTA_BaseNPC_Creature:SetHPGain(nHPGain) end

---Set the hit points regen gained per level on this creature.
---Server only.
---@param flHPRegenGain number
function CDOTA_BaseNPC_Creature:SetHPRegenGain(flHPRegenGain) end

---Set the magic resistance gained per level on this creature.
---Server only.
---@param flMagicResistanceGain number
function CDOTA_BaseNPC_Creature:SetMagicResistanceGain(flMagicResistanceGain) end

---Set the mana points gained per level on this creature.
---Server only.
---@param nManaGain integer
function CDOTA_BaseNPC_Creature:SetManaGain(nManaGain) end

---Set the mana points regen gained per level on this creature.
---Server only.
---@param flManaRegenGain number
function CDOTA_BaseNPC_Creature:SetManaRegenGain(flManaRegenGain) end

---Set the move speed gained per level on this creature.
---Server only.
---@param nMoveSpeedGain integer
function CDOTA_BaseNPC_Creature:SetMoveSpeedGain(nMoveSpeedGain) end

---Set whether creatures require reaching their end path before becoming idle
---Server only.
---@param bRequiresReachingEndPath boolean
function CDOTA_BaseNPC_Creature:SetRequiresReachingEndPath(bRequiresReachingEndPath) end

---Set creature's current disable resistance from ultimates
---Server only.
---@param flUltDisableResistance number
function CDOTA_BaseNPC_Creature:SetUltimateDisableResistance(flUltDisableResistance) end

---Set the XP gained per level on this creature.
---Server only.
---@param nXPGain integer
function CDOTA_BaseNPC_Creature:SetXPGain(nXPGain) end
