---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Item : CDOTABaseAbility
CDOTA_Item = {}

---Server only.
---@return boolean
function CDOTA_Item:CanBeUsedOutOfInventory() end

---Get the container for this item.
---Server only.
---@return handle
function CDOTA_Item:GetContainer() end

---Server only.
---@return integer
function CDOTA_Item:GetCost() end

---Get the number of charges this item currently has.
---Server only.
---@return integer
function CDOTA_Item:GetCurrentCharges() end

---Get the initial number of charges this item has.
---Server only.
---@return integer
function CDOTA_Item:GetInitialCharges() end

---Server only.
---@return integer
function CDOTA_Item:GetItemSlot() end

---Gets whether item is unequipped or ready.
---Server only.
---@return integer
function CDOTA_Item:GetItemState() end

---Get the parent for this item.
---Server only.
---@return handle
function CDOTA_Item:GetParent() end

---Get the purchase time of this item
---Server only.
---@return number
function CDOTA_Item:GetPurchaseTime() end

---Get the purchaser for this item.
---Server only.
---@return handle
function CDOTA_Item:GetPurchaser() end

---Get the number of secondary charges this item currently has.
---Server only.
---@return integer
function CDOTA_Item:GetSecondaryCharges() end

---Server only.
---@return integer
function CDOTA_Item:GetShareability() end

---Get the number of valueless charges this item currently has.
---Server only.
---@return integer
function CDOTA_Item:GetValuelessCharges() end

---Server only.
---@return boolean
function CDOTA_Item:IsActiveNeutral() end

---Server only.
---@return boolean
function CDOTA_Item:IsAlertableItem() end

---Server only.
---@return boolean
function CDOTA_Item:IsCastOnPickup() end

---Server only.
---@return boolean
function CDOTA_Item:IsCombinable() end

---Server only.
---@return boolean
function CDOTA_Item:IsCombineLocked() end

---Server only.
---@return boolean
function CDOTA_Item:IsDisassemblable() end

---Server only.
---@return boolean
function CDOTA_Item:IsDroppable() end

---Server only.
---@return boolean
function CDOTA_Item:IsInBackpack() end

---Server only.
---@return boolean
function CDOTA_Item:IsInStash() end

---Server only.
---@return boolean
function CDOTA_Item:IsItem() end

---Server only.
---@return boolean
function CDOTA_Item:IsKillable() end

---Server only.
---@return boolean
function CDOTA_Item:IsMuted() end

---Server only.
function CDOTA_Item:IsNull(...) end

---Is this a permanent item?
---Server only.
---@return boolean
function CDOTA_Item:IsPermanent() end

---Server only.
---@return boolean
function CDOTA_Item:IsPurchasable() end

---Server only.
---@return boolean
function CDOTA_Item:IsRecipe() end

---Server only.
---@return boolean
function CDOTA_Item:IsRecipeGenerated() end

---Server only.
---@return boolean
function CDOTA_Item:IsSellable() end

---Server only.
---@return boolean
function CDOTA_Item:IsStackable() end

---Server only.
---@param bAutoUse boolean
---@param flHeight number
---@param flDuration number
---@param vEndPoint any
---@param hTeleportOwner handle
function CDOTA_Item:LaunchLoot(bAutoUse, flHeight, flDuration, vEndPoint, hTeleportOwner) end

---Server only.
---@param bAutoUse boolean
---@param flInitialHeight number
---@param flLaunchHeight number
---@param flDuration number
---@param vEndPoint any
function CDOTA_Item:LaunchLootInitialHeight(bAutoUse, flInitialHeight, flLaunchHeight, flDuration, vEndPoint) end

---Server only.
---@param bAutoUse boolean
---@param flRequiredHeight number
---@param flHeight number
---@param flDuration number
---@param vEndPoint any
function CDOTA_Item:LaunchLootRequiredHeight(bAutoUse, flRequiredHeight, flHeight, flDuration, vEndPoint) end

---Modifies the number of valueless charges on this item
---Server only.
---@param iCharges integer
function CDOTA_Item:ModifyNumValuelessCharges(iCharges) end

---Server only.
function CDOTA_Item:OnEquip() end

---Server only.
function CDOTA_Item:OnUnequip() end

---Server only.
---@return boolean
function CDOTA_Item:RequiresCharges() end

---Server only.
---@param bValue boolean
function CDOTA_Item:SetCanBeUsedOutOfInventory(bValue) end

---Server only.
---@param bCastOnPickUp boolean
function CDOTA_Item:SetCastOnPickup(bCastOnPickUp) end

---Server only.
---@param bCombineLocked boolean
function CDOTA_Item:SetCombineLocked(bCombineLocked) end

---Set the number of charges on this item
---Server only.
---@param iCharges integer
function CDOTA_Item:SetCurrentCharges(iCharges) end

---Server only.
---@param bDroppable boolean
function CDOTA_Item:SetDroppable(bDroppable) end

---Sets whether item is unequipped or ready.
---Server only.
---@param iState integer
function CDOTA_Item:SetItemState(iState) end

---Server only.
---@param bOnlyPlayerHero boolean
function CDOTA_Item:SetOnlyPlayerHeroPickup(bOnlyPlayerHero) end

---Set the purchase time of this item
---Server only.
---@param flTime number
function CDOTA_Item:SetPurchaseTime(flTime) end

---Set the purchaser of record for this item.
---Server only.
---@param hPurchaser handle
function CDOTA_Item:SetPurchaser(hPurchaser) end

---Set the number of secondary charges on this item
---Server only.
---@param iCharges integer
function CDOTA_Item:SetSecondaryCharges(iCharges) end

---Server only.
---@param bSellable boolean
function CDOTA_Item:SetSellable(bSellable) end

---Server only.
---@param iShareability integer
function CDOTA_Item:SetShareability(iShareability) end

---Server only.
---@param bStacksWithOtherOwners boolean
function CDOTA_Item:SetStacksWithOtherOwners(bStacksWithOtherOwners) end

---Server only.
---@param flDelayRemove number
function CDOTA_Item:SpendCharge(flDelayRemove) end

---Server only.
---@return boolean
function CDOTA_Item:StacksWithOtherOwners() end

---Think this item
---Server only.
function CDOTA_Item:Think() end
