---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Item_Physical : CBaseAnimatingActivity
CDOTA_Item_Physical = {}

---Returned the contained item.
---Server only.
---@return handle
function CDOTA_Item_Physical:GetContainedItem() end

---Returns the game time when this item was created in the world
---Server only.
---@return number
function CDOTA_Item_Physical:GetCreationTime() end

---Is this drop flagged as a loot drop?
---Server only.
---@return boolean
function CDOTA_Item_Physical:IsLoot() end

---Server only.
function CDOTA_Item_Physical:IsNull(...) end

---Set the contained item.
---Server only.
---@param hItem handle
function CDOTA_Item_Physical:SetContainedItem(hItem) end

---Set if this drop is flagged as a loot drop
---Server only.
---@param bIsLoot boolean
function CDOTA_Item_Physical:SetIsLoot(bIsLoot) end
