---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Unit_Courier : CDOTA_BaseNPC
CDOTA_Unit_Courier = {}

---Server only.
function CDOTA_Unit_Courier:IsNull(...) end

---Respawn the courier.
---Server only.
function CDOTA_Unit_Courier:RespawnCourier() end

---Upgrade the courier ( int param ) times.
---Server only.
---@param iLevel integer
function CDOTA_Unit_Courier:UpgradeCourier(iLevel) end
