---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTA_Buff
CDOTA_Buff = CDOTA_Buff

---Server only.
function CDOTA_Buff:SendBuffRefreshToClients() end
