---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_ItemSpawner : CBaseEntity
CDOTA_ItemSpawner = {}

---Returns the item name
---Server only.
---@return string
function CDOTA_ItemSpawner:GetItemName() end

---Server only.
function CDOTA_ItemSpawner:IsNull(...) end
