---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC_Shop : CDOTA_BaseNPC_Building
CDOTA_BaseNPC_Shop = {}

---Get the DOTA_SHOP_TYPE
---Server only.
---@return integer
function CDOTA_BaseNPC_Shop:GetShopType() end

---Server only.
function CDOTA_BaseNPC_Shop:IsNull(...) end

---Set the DOTA_SHOP_TYPE.
---Server only.
---@param eShopType integer
function CDOTA_BaseNPC_Shop:SetShopType(eShopType) end
