---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Ability_Nian_Dive : CDOTABaseAbility
CDOTA_Ability_Nian_Dive = {}

---Server only.
function CDOTA_Ability_Nian_Dive:IsNull(...) end

---Override playbackrate
---Server only.
---@param flRate number
function CDOTA_Ability_Nian_Dive:SetPlaybackRate(flRate) end
