---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Ability_Lua : CDOTABaseAbility
CDOTA_Ability_Lua = {}

---Determine whether an issued command with no target is valid.
---Server only.
---@return integer
function CDOTA_Ability_Lua:CastFilterResult() end

---(VectorWS vLocation) Determine whether an issued command on a location is valid.
---Server only.
---@param vLocation any
---@return integer
function CDOTA_Ability_Lua:CastFilterResultLocation(vLocation) end

---(HSCRIPT hTarget) Determine whether an issued command on a target is valid.
---Server only.
---@param hTarget handle
---@return integer
function CDOTA_Ability_Lua:CastFilterResultTarget(hTarget) end

---Server only.
function CDOTA_Ability_Lua:CastFilterResult_Engine(...) end

---Controls the size of the AOE casting cursor.
---Server only.
---@return number
function CDOTA_Ability_Lua:GetAOERadius() end

---Server only.
---@param iLevel integer
---@return number
function CDOTA_Ability_Lua:GetAbilityChargeRestoreTime(iLevel) end

---Returns abilities that are stolen simultaneously, or otherwise related in functionality.
---Server only.
---@return string
function CDOTA_Ability_Lua:GetAssociatedPrimaryAbilities() end

---Returns other abilities that are stolen simultaneously, or otherwise related in functionality.  Generally hidden abilities.
---Server only.
---@return string
function CDOTA_Ability_Lua:GetAssociatedSecondaryAbilities() end

---Return cast behavior type of this ability.
---Server only.
---@return any
function CDOTA_Ability_Lua:GetBehavior() end

---Return casting animation of this ability.
---Server only.
---@return integer
function CDOTA_Ability_Lua:GetCastAnimation() end

---Return cast point of this ability.
---Server only.
---@return number
function CDOTA_Ability_Lua:GetCastPoint() end

---Return cast range of this ability.
---Server only.
---@param vLocation any
---@param hTarget handle
---@return integer
function CDOTA_Ability_Lua:GetCastRange(vLocation, hTarget) end

---Server only.
---@param hTarget handle
---@param iPseudoCastRange integer
---@return integer
function CDOTA_Ability_Lua:GetCastRangeBonus(hTarget, iPseudoCastRange) end

---Return channel animation of this ability.
---Server only.
---@return integer
function CDOTA_Ability_Lua:GetChannelAnimation() end

---Return the channel start time of this ability.
---Server only.
---@return number
function CDOTA_Ability_Lua:GetChannelStartTime() end

---Return the channel time of this ability.
---Server only.
---@return number
function CDOTA_Ability_Lua:GetChannelTime() end

---Return health cost per second of channeling at the given level (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Ability_Lua:GetChannelledHealthCostPerSecond(iLevel) end

---Return mana cost at the given level per second while channeling (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Ability_Lua:GetChannelledManaCostPerSecond(iLevel) end

---Return who hears speech when this spell is cast.
---Server only.
---@return integer
function CDOTA_Ability_Lua:GetConceptRecipientType() end

---Return cooldown of this ability.
---Server only.
---@param iLevel integer
---@return number
function CDOTA_Ability_Lua:GetCooldown(iLevel) end

---Return the error string of a failed command with no target.
---Server only.
---@return string
function CDOTA_Ability_Lua:GetCustomCastError() end

---(VectorWS vLocation) Return the error string of a failed command on a location.
---Server only.
---@param vLocation any
---@return string
function CDOTA_Ability_Lua:GetCustomCastErrorLocation(vLocation) end

---(HSCRIPT hTarget) Return the error string of a failed command on a target.
---Server only.
---@param hTarget handle
---@return string
function CDOTA_Ability_Lua:GetCustomCastErrorTarget(hTarget) end

---Server only.
function CDOTA_Ability_Lua:GetCustomCastError_Engine(...) end

---(DOTA_INVALID_ORDERS nReason) Return the error string of a failed order.
---Server only.
---@param nReason integer
---@return string
function CDOTA_Ability_Lua:GetCustomHudErrorMessage(nReason) end

---Return cast range of this ability, accounting for modifiers.
---Server only.
---@param vLocation any
---@param hTarget handle
---@return integer
function CDOTA_Ability_Lua:GetEffectiveCastRange(vLocation, hTarget) end

---Return gold cost at the given level (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Ability_Lua:GetGoldCost(iLevel) end

---Return health cost at the given level (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Ability_Lua:GetHealthCost(iLevel) end

---Returns the name of the modifier applied passively by this ability.
---Server only.
---@return string
function CDOTA_Ability_Lua:GetIntrinsicModifierName() end

---Return mana cost at the given level (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Ability_Lua:GetManaCost(iLevel) end

---Return the animation rate of the cast animation.
---Server only.
---@return number
function CDOTA_Ability_Lua:GetPlaybackRateOverride() end

---Is this ability an Attribute Bonus.
---Server only.
---@return boolean
function CDOTA_Ability_Lua:IsAttributeBonus() end

---Is this a cosmetic only ability?
---Server only.
---@param hEntity handle
---@return boolean
function CDOTA_Ability_Lua:IsCosmetic(hEntity) end

---Returns true if this ability can be used when not on the action panel.
---Server only.
---@return boolean
function CDOTA_Ability_Lua:IsHiddenAbilityCastable() end

---Returns true if this ability is hidden when stolen by Spell Steal.
---Server only.
---@return boolean
function CDOTA_Ability_Lua:IsHiddenWhenStolen() end

---Server only.
function CDOTA_Ability_Lua:IsNull(...) end

---Returns true if this ability is refreshed by Refresher Orb.
---Server only.
---@return boolean
function CDOTA_Ability_Lua:IsRefreshable() end

---Returns true if this ability can be stolen by Spell Steal.
---Server only.
---@return boolean
function CDOTA_Ability_Lua:IsStealable() end

---Cast time did not complete successfully.
---Server only.
function CDOTA_Ability_Lua:OnAbilityPhaseInterrupted() end

---Cast time begins (return true for successful cast).
---Server only.
---@return boolean
function CDOTA_Ability_Lua:OnAbilityPhaseStart() end

---The ability was pinged (nPlayerID, bCtrlHeld).
---Server only.
---@param nPlayerID integer
---@param bCtrlHeld boolean
function CDOTA_Ability_Lua:OnAbilityPinged(nPlayerID, bCtrlHeld) end

---Server only.
---@param hUpgradeAbility handle
function CDOTA_Ability_Lua:OnAbilityUpgrade(hUpgradeAbility) end

---(bool bInterrupted) Channel finished.
---Server only.
---@param bInterrupted boolean
function CDOTA_Ability_Lua:OnChannelFinish(bInterrupted) end

---(float flInterval) Channeling is taking place.
---Server only.
---@param flInterval number
function CDOTA_Ability_Lua:OnChannelThink(flInterval) end

---Caster (hero only) gained a level, skilled an ability, or received a new stat bonus.
---Server only.
function CDOTA_Ability_Lua:OnHeroCalculateStatBonus() end

---A hero has died in the vicinity (ie Urn), takes table of params.
---Server only.
---@param unit handle
---@param attacker handle
---@param table handle
function CDOTA_Ability_Lua:OnHeroDiedNearby(unit, attacker, table) end

---Caster gained a level.
---Server only.
function CDOTA_Ability_Lua:OnHeroLevelUp() end

---Caster inventory changed.
---Server only.
function CDOTA_Ability_Lua:OnInventoryContentsChanged() end

---( HSCRIPT hItem ) Caster equipped item.
---Server only.
---@param hItem handle
function CDOTA_Ability_Lua:OnItemEquipped(hItem) end

---Other ability gained a level.
---Server only.
function CDOTA_Ability_Lua:OnOtherAbilityUpgraded() end

---Caster died.
---Server only.
function CDOTA_Ability_Lua:OnOwnerDied() end

---Caster respawned or spawned for the first time.
---Server only.
function CDOTA_Ability_Lua:OnOwnerSpawned() end

---(HSCRIPT hTarget, VectorWS vLocation) Projectile has collided with a given target or reached its destination (target is invalid).
---Server only.
---@param hTarget handle
---@param vLocation any
---@return boolean
function CDOTA_Ability_Lua:OnProjectileHit(hTarget, vLocation) end

---(HSCRIPT hTarget, VectorWS vLocation, int nHandle) Projectile has collided with a given target or reached its destination (target is invalid).
---Server only.
---@param hTarget handle
---@param vLocation any
---@param iProjectileHandle integer
---@return boolean
function CDOTA_Ability_Lua:OnProjectileHitHandle(hTarget, vLocation, iProjectileHandle) end

---(HSCRIPT hTarget, VectorWS vLocation, table kv) Projectile has collided with a given target or reached its destination (target is invalid).
---Server only.
---@param hTarget handle
---@param vLocation any
---@param table handle
---@return boolean
function CDOTA_Ability_Lua:OnProjectileHit_ExtraData(hTarget, vLocation, table) end

---(VectorWS vLocation) Projectile is actively moving.
---Server only.
---@param vLocation any
function CDOTA_Ability_Lua:OnProjectileThink(vLocation) end

---(int nProjectileHandle) Projectile is actively moving.
---Server only.
---@param iProjectileHandle integer
function CDOTA_Ability_Lua:OnProjectileThinkHandle(iProjectileHandle) end

---(VectorWS vLocation, table kv ) Projectile is actively moving.
---Server only.
---@param vLocation any
---@param table handle
function CDOTA_Ability_Lua:OnProjectileThink_ExtraData(vLocation, table) end

---Cast time finished, spell effects begin.
---Server only.
function CDOTA_Ability_Lua:OnSpellStart() end

---( HSCRIPT hAbility ) Special behavior when stolen by Spell Steal.
---Server only.
---@param hSourceAbility handle
function CDOTA_Ability_Lua:OnStolen(hSourceAbility) end

---Ability is toggled on/off.
---Server only.
function CDOTA_Ability_Lua:OnToggle() end

---Special behavior when lost by Spell Steal.
---Server only.
function CDOTA_Ability_Lua:OnUnStolen() end

---Ability gained a level.
---Server only.
function CDOTA_Ability_Lua:OnUpgrade() end

---Server only.
---@return boolean
function CDOTA_Ability_Lua:OtherAbilitiesAlwaysInterruptChanneling() end

---Return if an ability and its modifiers should pierce debuff immunity.
---Server only.
---@return boolean
function CDOTA_Ability_Lua:PiercesDebuffImmunity() end

---Returns true if this ability will generate magic stick charges for nearby enemies.
---Server only.
---@return boolean
function CDOTA_Ability_Lua:ProcsMagicStick() end

---Refreshes ability values, if any
---Server only.
function CDOTA_Ability_Lua:RefreshAbilityValues() end

---Does this ability need the caster to face the target before executing?
---Server only.
---@return boolean
function CDOTA_Ability_Lua:RequiresFacing() end

---Returns true if this ability should return to the default toggle state when its parent respawns.
---Server only.
---@return boolean
function CDOTA_Ability_Lua:ResetToggleOnRespawn() end

---Return the type of speech used.
---Server only.
---@return integer
function CDOTA_Ability_Lua:SpeakTrigger() end
