---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Ability_Animation_Attack : CDOTABaseAbility
CDOTA_Ability_Animation_Attack = {}

---Server only.
function CDOTA_Ability_Animation_Attack:IsNull(...) end

---Override playbackrate
---Server only.
---@param flRate number
function CDOTA_Ability_Animation_Attack:SetPlaybackRate(flRate) end
