---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Unit_CustomGameAnnouncer : CDOTA_BaseNPC
CDOTA_Unit_CustomGameAnnouncer = {}

---Server only.
function CDOTA_Unit_CustomGameAnnouncer:IsNull(...) end

---Determines whether response criteria is matched on server or client
---Server only.
---@param bIsServerAuthoritative boolean
function CDOTA_Unit_CustomGameAnnouncer:SetServerAuthoritative(bIsServerAuthoritative) end
