---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_SimpleObstruction : CBaseEntity
CDOTA_SimpleObstruction = {}

---Returns whether the obstruction is currently active
---Server only.
---@return boolean
function CDOTA_SimpleObstruction:IsEnabled() end

---Server only.
function CDOTA_SimpleObstruction:IsNull(...) end

---Enable or disable the obstruction
---Server only.
---@param bEnabled boolean
---@param bForce boolean
function CDOTA_SimpleObstruction:SetEnabled(bEnabled, bForce) end
