---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Ability_Nian_Leap : CDOTABaseAbility
CDOTA_Ability_Nian_Leap = {}

---Server only.
function CDOTA_Ability_Nian_Leap:IsNull(...) end

---Override playbackrate
---Server only.
---@param flRate number
function CDOTA_Ability_Nian_Leap:SetPlaybackRate(flRate) end
