---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Ability_DataDriven : CDOTABaseAbility
CDOTA_Ability_DataDriven = {}

---Applies a data driven modifier to the target
---Server only.
---@param hCaster handle
---@param hTarget handle
---@param pszModifierName string
---@param hModifierTable handle
---@return handle
function CDOTA_Ability_DataDriven:ApplyDataDrivenModifier(hCaster, hTarget, pszModifierName, hModifierTable) end

---Applies a data driven thinker at the location
---Server only.
---@param hCaster handle
---@param vLocation any
---@param pszModifierName string
---@param hModifierTable handle
---@return handle
function CDOTA_Ability_DataDriven:ApplyDataDrivenThinker(hCaster, vLocation, pszModifierName, hModifierTable) end

---Server only.
function CDOTA_Ability_DataDriven:IsNull(...) end
