---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Ability_Aghanim_Spear : CDOTABaseAbility
CDOTA_Ability_Aghanim_Spear = {}

---Server only.
function CDOTA_Ability_Aghanim_Spear:IsNull(...) end

---Launch Spear to a target position from a source position
---Server only.
---@param vTarget any
---@param vStart any
function CDOTA_Ability_Aghanim_Spear:LaunchSpear(vTarget, vStart) end
