---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Item_EmptyBottle : CDOTA_Item
CDOTA_Item_EmptyBottle = {}

---Clear the stored rune.
---Server only.
function CDOTA_Item_EmptyBottle:ClearStoredRune() end

---Server only.
function CDOTA_Item_EmptyBottle:IsNull(...) end

---Place a rune in the bottle.
---Server only.
---@param iRuneType integer
---@return boolean
function CDOTA_Item_EmptyBottle:OnRune(iRuneType) end

---Set the stored rune.
---Server only.
---@param iRuneType integer
function CDOTA_Item_EmptyBottle:SetStoredRune(iRuneType) end
