---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDotaSubquestBase : CBaseEntity
CDotaSubquestBase = {}

---Mark this subquest complete
---Server only.
function CDotaSubquestBase:CompleteSubquest() end

---Server only.
function CDotaSubquestBase:IsNull(...) end

---Set the text replace string for this subquest
---Server only.
---@param pszString string
function CDotaSubquestBase:SetTextReplaceString(pszString) end

---Set a subquest value
---Server only.
---@param valueSlot integer
---@param value integer
function CDotaSubquestBase:SetTextReplaceValue(valueSlot, value) end
