---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Item_Lua : CDOTA_Item
CDOTA_Item_Lua = {}

---Returns true if this item can be picked up by the target unit.
---Server only.
---@param hUnit handle
---@return boolean
function CDOTA_Item_Lua:CanUnitPickUp(hUnit) end

---Determine whether an issued command with no target is valid.
---Server only.
---@return integer
function CDOTA_Item_Lua:CastFilterResult() end

---(VectorWS vLocation) Determine whether an issued command on a location is valid.
---Server only.
---@param vLocation any
---@return integer
function CDOTA_Item_Lua:CastFilterResultLocation(vLocation) end

---(HSCRIPT hTarget) Determine whether an issued command on a target is valid.
---Server only.
---@param hTarget handle
---@return integer
function CDOTA_Item_Lua:CastFilterResultTarget(hTarget) end

---Returns abilities that are stolen simultaneously, or otherwise related in functionality.
---Server only.
---@return string
function CDOTA_Item_Lua:GetAssociatedPrimaryAbilities() end

---Returns other abilities that are stolen simultaneously, or otherwise related in functionality.  Generally hidden abilities.
---Server only.
---@return string
function CDOTA_Item_Lua:GetAssociatedSecondaryAbilities() end

---Return cast behavior type of this ability.
---Server only.
---@return number
function CDOTA_Item_Lua:GetBehavior() end

---Return cast range of this ability.
---Server only.
---@param vLocation any
---@param hTarget handle
---@return integer
function CDOTA_Item_Lua:GetCastRange(vLocation, hTarget) end

---Return the channel start time of this ability.
---Server only.
---@return number
function CDOTA_Item_Lua:GetChannelStartTime() end

---Return the channel time of this ability.
---Server only.
---@return number
function CDOTA_Item_Lua:GetChannelTime() end

---Return health cost per second of channeling at the given level (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Item_Lua:GetChannelledHealthCostPerSecond(iLevel) end

---Return mana cost at the given level per second while channeling (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Item_Lua:GetChannelledManaCostPerSecond(iLevel) end

---Return who hears speech when this spell is cast.
---Server only.
---@return integer
function CDOTA_Item_Lua:GetConceptRecipientType() end

---Return cooldown of this ability.
---Server only.
---@param iLevel integer
---@return number
function CDOTA_Item_Lua:GetCooldown(iLevel) end

---Return the error string of a failed command with no target.
---Server only.
---@return string
function CDOTA_Item_Lua:GetCustomCastError() end

---(VectorWS vLocation) Return the error string of a failed command on a location.
---Server only.
---@param vLocation any
---@return string
function CDOTA_Item_Lua:GetCustomCastErrorLocation(vLocation) end

---(HSCRIPT hTarget) Return the error string of a failed command on a target.
---Server only.
---@param hTarget handle
---@return string
function CDOTA_Item_Lua:GetCustomCastErrorTarget(hTarget) end

---(DOTA_INVALID_ORDERS nReason) Return the error string of a failed order.
---Server only.
---@param nReason integer
---@return string
function CDOTA_Item_Lua:GetCustomHudErrorMessage(nReason) end

---Return cast range of this ability, taking modifiers into account.
---Server only.
---@param vLocation any
---@param hTarget handle
---@return integer
function CDOTA_Item_Lua:GetEffectiveCastRange(vLocation, hTarget) end

---Return gold cost at the given level (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Item_Lua:GetGoldCost(iLevel) end

---Return health cost at the given level (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Item_Lua:GetHealthCost(iLevel) end

---Returns the name of the modifier applied passively by this ability.
---Server only.
---@return string
function CDOTA_Item_Lua:GetIntrinsicModifierName() end

---Return mana cost at the given level (-1 is current).
---Server only.
---@param iLevel integer
---@return integer
function CDOTA_Item_Lua:GetManaCost(iLevel) end

---Return the animation rate of the cast animation.
---Server only.
---@return number
function CDOTA_Item_Lua:GetPlaybackRateOverride() end

---Returns true if this ability can be used when not on the action panel.
---Server only.
---@return boolean
function CDOTA_Item_Lua:IsHiddenAbilityCastable() end

---Returns true if this ability is hidden when stolen by Spell Steal.
---Server only.
---@return boolean
function CDOTA_Item_Lua:IsHiddenWhenStolen() end

---Returns whether this item is muted or not.
---Server only.
---@return boolean
function CDOTA_Item_Lua:IsMuted() end

---Server only.
function CDOTA_Item_Lua:IsNull(...) end

---Returns true if this ability is refreshed by Refresher Orb.
---Server only.
---@return boolean
function CDOTA_Item_Lua:IsRefreshable() end

---Returns true if this ability can be stolen by Spell Steal.
---Server only.
---@return boolean
function CDOTA_Item_Lua:IsStealable() end

---Cast time did not complete successfully.
---Server only.
function CDOTA_Item_Lua:OnAbilityPhaseInterrupted() end

---Cast time begins (return true for successful cast).
---Server only.
---@return boolean
function CDOTA_Item_Lua:OnAbilityPhaseStart() end

---(bool bInterrupted) Channel finished.
---Server only.
---@param bInterrupted boolean
function CDOTA_Item_Lua:OnChannelFinish(bInterrupted) end

---(float flInterval) Channeling is taking place.
---Server only.
---@param flInterval number
function CDOTA_Item_Lua:OnChannelThink(flInterval) end

---(bool bSpent) Runs when item's charge count changes. bSpent is true when the charge count change is coming from SpendCharge.
---Server only.
---@param bSpent boolean
function CDOTA_Item_Lua:OnChargeCountChanged(bSpent) end

---Caster (hero only) gained a level, skilled an ability, or received a new stat bonus.
---Server only.
function CDOTA_Item_Lua:OnHeroCalculateStatBonus() end

---A hero has died in the vicinity (ie Urn), takes table of params.
---Server only.
---@param unit handle
---@param attacker handle
---@param table handle
function CDOTA_Item_Lua:OnHeroDiedNearby(unit, attacker, table) end

---Caster gained a level.
---Server only.
function CDOTA_Item_Lua:OnHeroLevelUp() end

---Caster inventory changed.
---Server only.
function CDOTA_Item_Lua:OnInventoryContentsChanged() end

---( HSCRIPT hItem ) Caster equipped item.
---Server only.
---@param hItem handle
function CDOTA_Item_Lua:OnItemEquipped(hItem) end

---Other ability gained a level.
---Server only.
function CDOTA_Item_Lua:OnOtherAbilityUpgraded() end

---Caster died.
---Server only.
function CDOTA_Item_Lua:OnOwnerDied() end

---Caster respawned or spawned for the first time.
---Server only.
function CDOTA_Item_Lua:OnOwnerSpawned() end

---(HSCRIPT hTarget, VectorWS vLocation) Projectile has collided with a given target or reached its destination (target is invalid).
---Server only.
---@param hTarget handle
---@param vLocation any
---@return boolean
function CDOTA_Item_Lua:OnProjectileHit(hTarget, vLocation) end

---(VectorWS vLocation) Projectile is actively moving.
---Server only.
---@param vLocation any
function CDOTA_Item_Lua:OnProjectileThink(vLocation) end

---Cast time finished, spell effects begin.
---Server only.
function CDOTA_Item_Lua:OnSpellStart() end

---( HSCRIPT hAbility ) Special behavior when stolen by Spell Steal.
---Server only.
---@param hSourceAbility handle
function CDOTA_Item_Lua:OnStolen(hSourceAbility) end

---Ability is toggled on/off.
---Server only.
function CDOTA_Item_Lua:OnToggle() end

---Special behavior when lost by Spell Steal.
---Server only.
function CDOTA_Item_Lua:OnUnStolen() end

---Ability gained a level.
---Server only.
function CDOTA_Item_Lua:OnUpgrade() end

---Returns true if this ability will generate magic stick charges for nearby enemies.
---Server only.
---@return boolean
function CDOTA_Item_Lua:ProcsMagicStick() end

---Refreshes ability values, if any
---Server only.
function CDOTA_Item_Lua:RefreshAbilityValues() end

---Return the type of speech used.
---Server only.
---@return integer
function CDOTA_Item_Lua:SpeakTrigger() end
