---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC_Building : CDOTA_BaseNPC
CDOTA_BaseNPC_Building = {}

---Get the invulnerability count for a building.
---Server only.
---@return integer
function CDOTA_BaseNPC_Building:GetInvulnCount() end

---Server only.
function CDOTA_BaseNPC_Building:IsNull(...) end

---Set the invulnerability counter of this building.
---Server only.
---@param nInvulnCount integer
function CDOTA_BaseNPC_Building:SetInvulnCount(nInvulnCount) end
