---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC_LotusPool : CDOTA_BaseNPC_Building
CDOTA_BaseNPC_LotusPool = {}

---Server only.
function CDOTA_BaseNPC_LotusPool:IsNull(...) end
