---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTA_Modifier_Lua_Horizontal_Motion
CDOTA_Modifier_Lua_Horizontal_Motion = CDOTA_Modifier_Lua_Horizontal_Motion

---Starts the horizontal motion controller effects for this buff.  Returns true if successful.
---Server only.
---@return boolean
function CDOTA_Modifier_Lua_Horizontal_Motion:ApplyHorizontalMotionController() end

---Get the priority
---Server only.
---@return integer
function CDOTA_Modifier_Lua_Horizontal_Motion:GetPriority() end

---Called when the motion gets interrupted.
---Server only.
function CDOTA_Modifier_Lua_Horizontal_Motion:OnHorizontalMotionInterrupted() end

---Set the priority
---Server only.
---@param nMotionPriority integer
function CDOTA_Modifier_Lua_Horizontal_Motion:SetPriority(nMotionPriority) end

---Perform any motion from the given interval on the NPC.
---Server only.
---@param me handle
---@param dt number
function CDOTA_Modifier_Lua_Horizontal_Motion:UpdateHorizontalMotion(me, dt) end
