---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_BaseNPC_Hero : CDOTA_BaseNPC
CDOTA_BaseNPC_Hero = {}

---Params: Float XP, Bool applyBotDifficultyScaling, Bool IncrementalTotal (default true, unused), Int CloneCount (default 0)
---Server only.
---@param flXP number
---@param nReason integer
---@param bApplyBotDifficultyScaling boolean
---@param bIncrementTotal boolean
---@param nCloneCount integer
---@return boolean
function CDOTA_BaseNPC_Hero:AddExperience(flXP, nReason, bApplyBotDifficultyScaling, bIncrementTotal, nCloneCount) end

---Server only.
function CDOTA_BaseNPC_Hero:AddExperience_Engine(...) end

---Spend the gold and buyback with this hero.
---Server only.
function CDOTA_BaseNPC_Hero:Buyback() end

---Recalculate all stats after the hero gains stats.
---Server only.
---@param bForce boolean
function CDOTA_BaseNPC_Hero:CalculateStatBonus(bForce) end

---Returns boolean value result of buyback gold limit time less than game time.
---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:CanEarnGold() end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:ClearLastHitMultikill() end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:ClearLastHitStreak() end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:ClearStreak() end

---Gets the current unspent ability points.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetAbilityPoints() end

---Server only.
---@return table
function CDOTA_BaseNPC_Hero:GetAdditionalOwnedUnits() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetAgility() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetAgilityGain() end

---Value is stored in PlayerResource.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetAssists() end

---Server only.
---@param nIndex integer
---@return integer
function CDOTA_BaseNPC_Hero:GetAttacker(nIndex) end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetBaseAgility() end

---Hero damage is also affected by attributes.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetBaseDamageMax() end

---Hero damage is also affected by attributes.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetBaseDamageMin() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetBaseIntellect() end

---Returns the base mana regen.
---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetBaseManaRegen() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetBaseStrength() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetBonusDamageFromPrimaryStat() end

---Return float value for the amount of time left on cooldown for this hero's buyback.
---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetBuybackCooldownTime() end

---Return integer value for the gold cost of a buyback.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetBuybackCost() end

---Returns the amount of time gold gain is limited after buying back.
---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetBuybackGoldLimitTime() end

---Returns the amount of XP
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetCurrentXP() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetDeathGoldCost() end

---Value is stored in PlayerResource.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetDeaths() end

---Value is stored in PlayerResource.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetDenies() end

---Returns gold amount for the player owning this hero
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetGold() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetGoldBounty() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetHeroFacetID() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetHeroID() end

---Hero attack speed is also affected by agility.
---Server only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function CDOTA_BaseNPC_Hero:GetIncreasedAttackSpeed(bIgnoreTempAttackSpeed) end

---Server only.
---@param bSkipNoConsume boolean
---@return number
function CDOTA_BaseNPC_Hero:GetIntellect(bSkipNoConsume) end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetIntellectGain() end

---Value is stored in PlayerResource.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetKills() end

---Value is stored in PlayerResource.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetLastHits() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetMostRecentDamageTime() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetMultipleKillCount() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetNumAttackers() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetNumItemsInInventory() end

---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetNumItemsInStash() end

---Hero armor is affected by attributes.
---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetPhysicalArmorBaseValue() end

---Returns player ID of the player owning this hero
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetPlayerID() end

---0 = strength, 1 = agility, 2 = intelligence.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetPrimaryAttribute() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetPrimaryStatValue() end

---Server only.
---@return handle
function CDOTA_BaseNPC_Hero:GetReplicatingOtherHero() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetRespawnTime() end

---Is this hero prevented from respawning?
---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:GetRespawnsDisabled() end

---Value is stored in PlayerResource.
---Server only.
---@return integer
function CDOTA_BaseNPC_Hero:GetStreak() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetStrength() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetStrengthGain() end

---Server only.
---@return number
function CDOTA_BaseNPC_Hero:GetTimeUntilRespawn() end

---Get wearable entity in slot (slot)
---Server only.
---@param nSlotType integer
---@return handle
function CDOTA_BaseNPC_Hero:GetTogglableWearable(nSlotType) end

---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:HasAnyAvailableInventorySpace() end

---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:HasFlyingVision() end

---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:HasOwnerAbandoned() end

---Args: const char* pItemName, bool bIncludeStashCombines, bool bAllowSelling
---Server only.
---@param pItemName string
---@param bIncludeStashCombines boolean
---@param bAllowSelling boolean
---@return integer
function CDOTA_BaseNPC_Hero:HasRoomForItem(pItemName, bIncludeStashCombines, bAllowSelling) end

---Levels up the hero, true or false to play effects.
---Server only.
---@param bPlayEffects boolean
function CDOTA_BaseNPC_Hero:HeroLevelUp(bPlayEffects) end

---Value is stored in PlayerResource.
---Server only.
---@param iKillerID integer
function CDOTA_BaseNPC_Hero:IncrementAssists(iKillerID) end

---Value is stored in PlayerResource.
---Server only.
---@param iKillerID integer
function CDOTA_BaseNPC_Hero:IncrementDeaths(iKillerID) end

---Server only.
function CDOTA_BaseNPC_Hero:IncrementDeaths_Engine(...) end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:IncrementDenies() end

---Passed ID is for the victim, killer ID is ID of the current hero.  Value is stored in PlayerResource.
---Server only.
---@param iVictimID integer
function CDOTA_BaseNPC_Hero:IncrementKills(iVictimID) end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:IncrementLastHitMultikill() end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:IncrementLastHitStreak() end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:IncrementLastHits() end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:IncrementNearbyCreepDeaths() end

---Value is stored in PlayerResource.
---Server only.
function CDOTA_BaseNPC_Hero:IncrementStreak() end

---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:IsBuybackDisabledByDevilsBargain() end

---Server only.
function CDOTA_BaseNPC_Hero:IsNull(...) end

---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:IsReincarnating() end

---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:IsStashEnabled() end

---Args: Hero, Inflictor
---Server only.
---@param hHero handle
---@param hInflictor handle
function CDOTA_BaseNPC_Hero:KilledHero(hHero, hInflictor) end

---Adds passed value to base attribute value, then calls CalculateStatBonus.
---Server only.
---@param flNewAgility number
function CDOTA_BaseNPC_Hero:ModifyAgility(flNewAgility) end

---Gives this hero some gold.  Args: int nGoldChange, bool bReliable, int reason
---Server only.
---@param iGoldChange integer
---@param bReliable boolean
---@param iReason integer
---@return integer
function CDOTA_BaseNPC_Hero:ModifyGold(iGoldChange, bReliable, iReason) end

---Gives this hero some gold, using the gold filter if extra filtering is on.  Args: int nGoldChange, bool bReliable, int reason
---Server only.
---@param iGoldChange integer
---@param bReliabe boolean
---@param iReason integer
---@return integer
function CDOTA_BaseNPC_Hero:ModifyGoldFiltered(iGoldChange, bReliabe, iReason) end

---Adds passed value to base attribute value, then calls CalculateStatBonus.
---Server only.
---@param flNewIntellect number
function CDOTA_BaseNPC_Hero:ModifyIntellect(flNewIntellect) end

---Adds passed value to base attribute value, then calls CalculateStatBonus.
---Server only.
---@param flNewStrength number
function CDOTA_BaseNPC_Hero:ModifyStrength(flNewStrength) end

---Server only.
function CDOTA_BaseNPC_Hero:PerformTaunt() end

---Server only.
function CDOTA_BaseNPC_Hero:RecordLastHit() end

---Respawn this hero.
---Server only.
---@param bBuyBack boolean
---@param bRespawnPenalty boolean
function CDOTA_BaseNPC_Hero:RespawnHero(bBuyBack, bRespawnPenalty) end

---Sets the current unspent ability points.
---Server only.
---@param iPoints integer
function CDOTA_BaseNPC_Hero:SetAbilityPoints(iPoints) end

---Server only.
---@param flAgility number
function CDOTA_BaseNPC_Hero:SetBaseAgility(flAgility) end

---Server only.
---@param flIntellect number
function CDOTA_BaseNPC_Hero:SetBaseIntellect(flIntellect) end

---Server only.
---@param flStrength number
function CDOTA_BaseNPC_Hero:SetBaseStrength(flStrength) end

---Server only.
---@param nDifficulty integer
function CDOTA_BaseNPC_Hero:SetBotDifficulty(nDifficulty) end

---Server only.
---@param bBuybackDisabled boolean
function CDOTA_BaseNPC_Hero:SetBuyBackDisabledByDevilsBargain(bBuybackDisabled) end

---Sets the buyback cooldown time.
---Server only.
---@param flTime number
function CDOTA_BaseNPC_Hero:SetBuybackCooldownTime(flTime) end

---Set the amount of time gold gain is limited after buying back.
---Server only.
---@param flTime number
function CDOTA_BaseNPC_Hero:SetBuybackGoldLimitTime(flTime) end

---Sets a custom experience value for this hero.  Note, GameRules boolean must be set for this to work!
---Server only.
---@param iValue integer
function CDOTA_BaseNPC_Hero:SetCustomDeathXP(iValue) end

---Sets the gold amount for the player owning this hero
---Server only.
---@param iGold integer
---@param bReliable boolean
function CDOTA_BaseNPC_Hero:SetGold(iGold, bReliable) end

---Server only.
---@param iPlayerID integer
function CDOTA_BaseNPC_Hero:SetPlayerID(iPlayerID) end

---Set this hero's primary attribute value.
---Server only.
---@param nPrimaryAttribute integer
function CDOTA_BaseNPC_Hero:SetPrimaryAttribute(nPrimaryAttribute) end

---Server only.
---@param vOrigin any
function CDOTA_BaseNPC_Hero:SetRespawnPosition(vOrigin) end

---Prevent this hero from respawning.
---Server only.
---@param bDisableRespawns boolean
function CDOTA_BaseNPC_Hero:SetRespawnsDisabled(bDisableRespawns) end

---Server only.
---@param bEnabled boolean
function CDOTA_BaseNPC_Hero:SetStashEnabled(bEnabled) end

---Server only.
---@param time number
function CDOTA_BaseNPC_Hero:SetTimeUntilRespawn(time) end

---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:ShouldDoFlyHeightVisual() end

---Args: int nGold, int nReason
---Server only.
---@param iCost integer
---@param iReason integer
function CDOTA_BaseNPC_Hero:SpendGold(iCost, iReason) end

---This upgrades the passed ability if it exists and the hero has enough ability points.
---Server only.
---@param hAbility handle
function CDOTA_BaseNPC_Hero:UpgradeAbility(hAbility) end

---Server only.
---@return boolean
function CDOTA_BaseNPC_Hero:WillReincarnate() end
