---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Unit_Nian : CDOTA_BaseNPC_Creature
CDOTA_Unit_Nian = {}

---Is the Nian horn?
---Server only.
---@return handle
function CDOTA_Unit_Nian:GetHorn() end

---Is the Nian's tail broken?
---Server only.
---@return handle
function CDOTA_Unit_Nian:GetTail() end

---Is the Nian's horn broken?
---Server only.
---@return boolean
function CDOTA_Unit_Nian:IsHornAlive() end

---Server only.
function CDOTA_Unit_Nian:IsNull(...) end

---Is the Nian's tail broken?
---Server only.
---@return boolean
function CDOTA_Unit_Nian:IsTailAlive() end
