---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTA_Modifier_Lua_Vertical_Motion
CDOTA_Modifier_Lua_Vertical_Motion = CDOTA_Modifier_Lua_Vertical_Motion

---Starts the vertical motion controller effects for this buff.  Returns true if successful.
---Server only.
---@return boolean
function CDOTA_Modifier_Lua_Vertical_Motion:ApplyVerticalMotionController() end

---Get the priority
---Server only.
---@return integer
function CDOTA_Modifier_Lua_Vertical_Motion:GetMotionPriority() end

---Called when the motion gets interrupted.
---Server only.
function CDOTA_Modifier_Lua_Vertical_Motion:OnVerticalMotionInterrupted() end

---Set the priority
---Server only.
---@param nMotionPriority integer
function CDOTA_Modifier_Lua_Vertical_Motion:SetMotionPriority(nMotionPriority) end

---Perform any motion from the given interval on the NPC.
---Server only.
---@param me handle
---@param dt number
function CDOTA_Modifier_Lua_Vertical_Motion:UpdateVerticalMotion(me, dt) end
