---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTAPlayerController : CBaseAnimatingActivity
CDOTAPlayerController = {}

---Attempt to spawn the appropriate couriers for this mode.
---Server only.
---@param hHero handle
---@return handle
function CDOTAPlayerController:CheckForCourierSpawning(hHero) end

---Get the player's hero.
---Server only.
---@return handle
function CDOTAPlayerController:GetAssignedHero() end

---Get the player's official PlayerID; notably is -1 when the player isn't yet on a team.
---Server only.
---@return integer
function CDOTAPlayerController:GetPlayerID() end

---Server only.
function CDOTAPlayerController:IsNull(...) end

---Randoms this player's hero.
---Server only.
function CDOTAPlayerController:MakeRandomHeroSelection() end

---Sets this player's hero .
---Server only.
---@param hHero handle
function CDOTAPlayerController:SetAssignedHeroEntity(hHero) end

---Set the kill cam unit for this hero.
---Server only.
---@param hEntity handle
function CDOTAPlayerController:SetKillCamUnit(hEntity) end

---(nMusicStatus, flIntensity) - Set the music status for this player, note this will only really apply if dota_music_battle_enable is off.
---Server only.
---@param nMusicStatus integer
---@param flIntensity number
function CDOTAPlayerController:SetMusicStatus(nMusicStatus, flIntensity) end

---Sets this player's hero selection.
---Server only.
---@param pszHeroName string
function CDOTAPlayerController:SetSelectedHero(pszHeroName) end

---Spawn a courier for this player at the given position.
---Server only.
---@param vLocation any
---@return handle
function CDOTAPlayerController:SpawnCourierAtPosition(vLocation) end
