---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CDOTA_Modifier_Lua_Motion_Both
CDOTA_Modifier_Lua_Motion_Both = CDOTA_Modifier_Lua_Motion_Both

---Starts the horizontal motion controller effects for this buff.  Returns true if successful.
---Server only.
---@return boolean
function CDOTA_Modifier_Lua_Motion_Both:ApplyHorizontalMotionController() end

---Starts the vertical motion controller effects for this buff.  Returns true if successful.
---Server only.
---@return boolean
function CDOTA_Modifier_Lua_Motion_Both:ApplyVerticalMotionController() end

---Get the priority
---Server only.
---@return integer
function CDOTA_Modifier_Lua_Motion_Both:GetPriority() end

---Called when the motion gets interrupted.
---Server only.
function CDOTA_Modifier_Lua_Motion_Both:OnHorizontalMotionInterrupted() end

---Called when the motion gets interrupted.
---Server only.
function CDOTA_Modifier_Lua_Motion_Both:OnVerticalMotionInterrupted() end

---Set the priority
---Server only.
---@param nMotionPriority integer
function CDOTA_Modifier_Lua_Motion_Both:SetPriority(nMotionPriority) end

---Perform any motion from the given interval on the NPC.
---Server only.
---@param me handle
---@param dt number
function CDOTA_Modifier_Lua_Motion_Both:UpdateHorizontalMotion(me, dt) end

---Perform any motion from the given interval on the NPC.
---Server only.
---@param me handle
---@param dt number
function CDOTA_Modifier_Lua_Motion_Both:UpdateVerticalMotion(me, dt) end
