---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_MapTree : CBaseEntity
CDOTA_MapTree = {}

---Cuts down this tree. Parameters: int nTeamNumberKnownTo (-1 = invalid team)
---Server only.
---@param nTeamNumberKnownTo integer
function CDOTA_MapTree:CutDown(nTeamNumberKnownTo) end

---Cuts down this tree. Parameters: float flRegrowAfter (-1 = never regrow), int nTeamNumberKnownTo (-1 = invalid team)
---Server only.
---@param flRegrowAfter number
---@param nTeamNumberKnownTo integer
function CDOTA_MapTree:CutDownRegrowAfter(flRegrowAfter, nTeamNumberKnownTo) end

---Grows back the tree if it was cut down.
---Server only.
function CDOTA_MapTree:GrowBack() end

---Server only.
function CDOTA_MapTree:IsNull(...) end

---Returns true if the tree is standing, false if it has been cut down
---Server only.
---@return boolean
function CDOTA_MapTree:IsStanding() end
