---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_NeutralSpawner : CPointEntity
CDOTA_NeutralSpawner = {}

---Server only.
function CDOTA_NeutralSpawner:CreatePendingUnits() end

---Server only.
function CDOTA_NeutralSpawner:IsNull(...) end

---Server only.
function CDOTA_NeutralSpawner:SelectSpawnType() end

---Server only.
---@param bIgnoreBlockers boolean
function CDOTA_NeutralSpawner:SpawnNextBatch(bIgnoreBlockers) end
