---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTABaseGameMode : CBaseEntity
CDOTABaseGameMode = {}

---const char* pszAbilityName
---Server only.
---@param pszAbilityName string
function CDOTABaseGameMode:AddAbilityUpgradeToWhitelist(pszAbilityName) end

---( pszItem, pszShop, pszCategory ) Add an item to purchase at a custom shop.
---Server only.
---@param pszItemName string
---@param pszShopName string
---@param pszCategory string
function CDOTABaseGameMode:AddItemToCustomShop(pszItemName, pszShopName, pszCategory) end

---Begin tracking a sequence of events using the real time combat analyzer.
---Server only.
---@param hQueryTable handle
---@param hPlayer handle
---@param pszQueryName string
---@return integer
function CDOTABaseGameMode:AddRealTimeCombatAnalyzerQuery(hQueryTable, hPlayer, pszQueryName) end

---Allocates an entity which can be used by custom games to control FoW occlusion volumes
---Server only.
---@param flMinX number
---@param flMinY number
---@param flMaxX number
---@param flMaxY number
---@param flGridSize number
---@return handle
function CDOTABaseGameMode:AllocateFowBlockerRegion(flMinX, flMinY, flMaxX, flMaxY, flGridSize) end

---Get if weather effects are disabled on the client.
---Server only.
---@return boolean
function CDOTABaseGameMode:AreWeatherEffectsDisabled() end

---Clear the script filter that controls bounty rune pickup behavior.
---Server only.
function CDOTABaseGameMode:ClearBountyRunePickupFilter() end

---Clear the script filter that controls how a unit takes damage.
---Server only.
function CDOTABaseGameMode:ClearDamageFilter() end

---Clear the script filter that controls when a unit picks up an item.
---Server only.
function CDOTABaseGameMode:ClearExecuteOrderFilter() end

---Clear the script filter that controls how a unit heals.
---Server only.
function CDOTABaseGameMode:ClearHealingFilter() end

---Clear the script filter that controls the item added to inventory filter.
---Server only.
function CDOTABaseGameMode:ClearItemAddedToInventoryFilter() end

---Clear the script filter that controls the modifier filter.
---Server only.
function CDOTABaseGameMode:ClearModifierGainedFilter() end

---Clear the script filter that controls how hero experience is modified.
---Server only.
function CDOTABaseGameMode:ClearModifyExperienceFilter() end

---Clear the script filter that controls how hero gold is modified.
---Server only.
function CDOTABaseGameMode:ClearModifyGoldFilter() end

---Clear the script filter that controls what rune spawns.
---Server only.
function CDOTABaseGameMode:ClearRuneSpawnFilter() end

---Clear the script filter that controls when tracking projectiles are launched.
---Server only.
function CDOTABaseGameMode:ClearTrackingProjectileFilter() end

---Disable npc_dota_creature clumping behavior by default.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:DisableClumpingBehaviorByDefault(bDisabled) end

---Use to disable hud flip for this mod
---Server only.
---@param bDisable boolean
function CDOTABaseGameMode:DisableHudFlip(bDisable) end

---bool bEnabled
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:EnableAbilityUpgradeWhitelist(bEnabled) end

---Show the player hero's inventory in the HUD, regardless of what unit is selected.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetAlwaysShowPlayerInventory() end

---Get whether player names are always shown, regardless of client setting.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetAlwaysShowPlayerNames() end

---Are in-game announcers disabled?
---Server only.
---@return boolean
function CDOTABaseGameMode:GetAnnouncerDisabled() end

---Is the announcer announcing the mode / saying Choose Your Hero on start of custom games disabled?
---Server only.
---@return boolean
function CDOTABaseGameMode:GetAnnouncerGameModeAnnounceDisabled() end

---Set a different camera distance; dota default is 1134.
---Server only.
---@return number
function CDOTABaseGameMode:GetCameraDistanceOverride() end

---Get current derived stat value constant.
---Server only.
---@param nDerivedStatType integer
---@return number
function CDOTABaseGameMode:GetCustomAttributeDerivedStatValue(nDerivedStatType) end

---Get the current rate cooldown ticks down for items in the backpack.
---Server only.
---@return number
function CDOTABaseGameMode:GetCustomBackpackCooldownPercent() end

---Get the current custom backpack swap cooldown.
---Server only.
---@return number
function CDOTABaseGameMode:GetCustomBackpackSwapCooldown() end

---Turns on capability to define custom buyback cooldowns.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetCustomBuybackCooldownEnabled() end

---Turns on capability to define custom buyback costs.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetCustomBuybackCostEnabled() end

---Get the topbar score display value for dire.
---Server only.
---@return integer
function CDOTABaseGameMode:GetCustomDireScore() end

---Get the current custom glyph cooldown.
---Server only.
---@return number
function CDOTABaseGameMode:GetCustomGlyphCooldown() end

---Allows definition of the max level heroes can achieve (default is 25).
---Server only.
---@return integer
function CDOTABaseGameMode:GetCustomHeroMaxLevel() end

---Get the topbar score display value for radiant.
---Server only.
---@return integer
function CDOTABaseGameMode:GetCustomRadiantScore() end

---Get the current custom scan cooldown.
---Server only.
---@return number
function CDOTABaseGameMode:GetCustomScanCooldown() end

---Get the rate at which the day/night cycle advances (1.0 = default).
---Server only.
---@return number
function CDOTABaseGameMode:GetDaynightCycleAdvanceRate() end

---Get the Game Seed passed from the GC.
---Server only.
---@return integer
function CDOTABaseGameMode:GetEventGameSeed() end

---Get the Event Window Start Time passed from the GC.
---Server only.
---@return integer
function CDOTABaseGameMode:GetEventWindowStartTime() end

---Gets the fixed respawn time.
---Server only.
---@return number
function CDOTABaseGameMode:GetFixedRespawnTime() end

---Turn the fog of war on or off.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetFogOfWarDisabled() end

---Turn the sound when gold is acquired off/on.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetGoldSoundDisabled() end

---Returns the HUD element visibility.
---Server only.
---@param iElement integer
---@return boolean
function CDOTABaseGameMode:GetHUDVisible(iElement) end

---Get the maximum attack speed for units.
---Server only.
---@return integer
function CDOTABaseGameMode:GetMaximumAttackSpeed() end

---Get the minimum attack speed for units.
---Server only.
---@return integer
function CDOTABaseGameMode:GetMinimumAttackSpeed() end

---Turn the panel for showing recommended items at the shop off/on.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetRecommendedItemsDisabled() end

---Returns the scale applied to non-fixed respawn times.
---Server only.
---@return number
function CDOTABaseGameMode:GetRespawnTimeScale() end

---Turn purchasing items to the stash off/on. If purchasing to the stash is off the player must be at a shop to purchase items.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetStashPurchasingDisabled() end

---Hide the sticky item in the quickbuy.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetStickyItemDisabled() end

---Override the values of the team values on the top game bar.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetTopBarTeamValuesOverride() end

---Turning on/off the team values on the top game bar.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetTopBarTeamValuesVisible() end

---Gets whether tower backdoor protection is enabled or not.
---Server only.
---@return boolean
function CDOTABaseGameMode:GetTowerBackdoorProtectionEnabled() end

---Are custom-defined XP values for hero level ups in use?
---Server only.
---@return boolean
function CDOTABaseGameMode:GetUseCustomHeroLevels() end

---Gets the time from game start during which water runes spawn
---Server only.
---@return number
function CDOTABaseGameMode:GetWaterRuneLastSpawnTime() end

---const char* pszAbilityName
---Server only.
---@param pszAbilityName string
---@return boolean
function CDOTABaseGameMode:IsAbilityUpgradeWhitelisted(pszAbilityName) end

---Enables or disables buyback completely.
---Server only.
---@return boolean
function CDOTABaseGameMode:IsBuybackEnabled() end

---Is the day/night cycle disabled?
---Server only.
---@return boolean
function CDOTABaseGameMode:IsDaynightCycleDisabled() end

---Server only.
function CDOTABaseGameMode:IsNull(...) end

---Set function and context for real time combat analyzer query failed.
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:ListenForQueryFailed(hFunction, hContext) end

---Set function and context for real time combat analyzer query progress changed.
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:ListenForQueryProgressChanged(hFunction, hContext) end

---Set function and context for real time combat analyzer query succeeded.
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:ListenForQuerySucceeded(hFunction, hContext) end

---const char* pszAbilityName
---Server only.
---@param pszAbilityName string
function CDOTABaseGameMode:RemoveAbilityUpgradeFromWhitelist(pszAbilityName) end

---( pszItem, pszShop ) Remove an item to purchase at a custom shop.
---Server only.
---@param pszItemName string
---@param pszShopName string
function CDOTABaseGameMode:RemoveItemFromCustomShop(pszItemName, pszShopName) end

---Stop tracking a combat analyzer query.
---Server only.
---@param nQueryID integer
function CDOTABaseGameMode:RemoveRealTimeCombatAnalyzerQuery(nQueryID) end

---Set a filter function to control the tuning values that abilities use. (Modify the table and Return true to use new values, return false to use the old values)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetAbilityTuningValueFilter(hFunction, hContext) end

---If set to true, neutral items will be dropped on killing neutral monsters.  Otherwise nothing will be dropped.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetAllowNeutralItemDrops(bEnabled) end

---Show the player hero's inventory in the HUD, regardless of what unit is selected.
---Server only.
---@param bAlwaysShow boolean
function CDOTABaseGameMode:SetAlwaysShowPlayerInventory(bAlwaysShow) end

---Set whether player names are always shown, regardless of client setting.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetAlwaysShowPlayerNames(bEnabled) end

---Mutes the in-game announcer.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetAnnouncerDisabled(bDisabled) end

---Disables the announcer announcing the mode / saying Choose Your Hero on start of custom games.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetAnnouncerGameModeAnnounceDisabled(bDisabled) end

---Enables/Disables bots in custom games. Note: this will only work with default heroes in the dota map.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetBotThinkingEnabled(bEnabled) end

---Set if the bots should try their best to push with a human player.
---Server only.
---@param bAlwaysPush boolean
function CDOTABaseGameMode:SetBotsAlwaysPushWithHuman(bAlwaysPush) end

---Set if bots should enable their late game behavior.
---Server only.
---@param bLateGame boolean
function CDOTABaseGameMode:SetBotsInLateGame(bLateGame) end

---Set the max tier of tower that bots want to push. (-1 to disable)
---Server only.
---@param nMaxTier integer
function CDOTABaseGameMode:SetBotsMaxPushTier(nMaxTier) end

---Set a filter function to control the behavior when a bounty rune is picked up. (Modify the table and Return true to use new values, return false to cancel the event)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetBountyRunePickupFilter(hFunction, hContext) end

---Set bounty rune spawn rate
---Server only.
---@param flInterval number
function CDOTABaseGameMode:SetBountyRuneSpawnInterval(flInterval) end

---Enables or disables buyback completely.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetBuybackEnabled(bEnabled) end

---Set a different camera distance; dota default is 1134.
---Server only.
---@param flCameraDistanceOverride number
function CDOTABaseGameMode:SetCameraDistanceOverride(flCameraDistanceOverride) end

---Set a different camera smooth count; dota default is 8.
---Server only.
---@param nSmoothCount integer
function CDOTABaseGameMode:SetCameraSmoothCountOverride(nSmoothCount) end

---Sets the camera Z range
---Server only.
---@param flMinZ number
---@param flMaxZ number
function CDOTABaseGameMode:SetCameraZRange(flMinZ, flMaxZ) end

---bool bAllow
---Server only.
---@param bAllow boolean
function CDOTABaseGameMode:SetCanSellAnywhere(bAllow) end

---Modify derived stat value constants. ( AttributeDerivedStat eStatType, float flNewValue.
---Server only.
---@param nStatType integer
---@param flNewValue number
function CDOTABaseGameMode:SetCustomAttributeDerivedStatValue(nStatType, flNewValue) end

---Set the rate cooldown ticks down for items in the backpack.
---Server only.
---@param flPercent number
function CDOTABaseGameMode:SetCustomBackpackCooldownPercent(flPercent) end

---Set a custom cooldown for swapping items into the backpack.
---Server only.
---@param flCooldown number
function CDOTABaseGameMode:SetCustomBackpackSwapCooldown(flCooldown) end

---Turns on capability to define custom buyback cooldowns.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetCustomBuybackCooldownEnabled(bEnabled) end

---Turns on capability to define custom buyback costs.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetCustomBuybackCostEnabled(bEnabled) end

---Sets the topbar score display value for dire.
---Server only.
---@param nScore integer
function CDOTABaseGameMode:SetCustomDireScore(nScore) end

---Force all players to use the specified hero and disable the normal hero selection process. Must be used before hero selection.
---Server only.
---@param pHeroName string
function CDOTABaseGameMode:SetCustomGameForceHero(pHeroName) end

---Set a custom cooldown for team Glyph ability.
---Server only.
---@param flCooldown number
function CDOTABaseGameMode:SetCustomGlyphCooldown(flCooldown) end

---Allows definition of the max level heroes can achieve (default is 25).
---Server only.
---@param int_1 integer
function CDOTABaseGameMode:SetCustomHeroMaxLevel(int_1) end

---Sets the topbar score display value for radiant.
---Server only.
---@param nScore integer
function CDOTABaseGameMode:SetCustomRadiantScore(nScore) end

---Set a custom cooldown for team Scan ability.
---Server only.
---@param flCooldown number
function CDOTABaseGameMode:SetCustomScanCooldown(flCooldown) end

---Set a custom max charges for team Scan ability.
---Server only.
---@param iMaxCharges integer
function CDOTABaseGameMode:SetCustomScanMaxCharges(iMaxCharges) end

---Set the effect used as a custom weather effect, when units are on non-default terrain, in this mode.
---Server only.
---@param pszEffectName string
function CDOTABaseGameMode:SetCustomTerrainWeatherEffect(pszEffectName) end

---Allows definition of a table of hero XP values.
---Server only.
---@param hTable handle
function CDOTABaseGameMode:SetCustomXPRequiredToReachNextLevel(hTable) end

---Set a filter function to control the behavior when a unit takes damage. (Modify the table and Return true to use new values, return false to cancel the event)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetDamageFilter(hFunction, hContext) end

---Sets the rate at which the day/night cycle advances (1.0 = default).
---Server only.
---@param flRate number
function CDOTABaseGameMode:SetDaynightCycleAdvanceRate(flRate) end

---Enable or disable the day/night cycle.
---Server only.
---@param bDisable boolean
function CDOTABaseGameMode:SetDaynightCycleDisabled(bDisable) end

---Specify whether the full screen death overlay effect plays when the selected hero dies.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetDeathOverlayDisabled(bDisabled) end

---Disables chat tips on death.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetDeathTipsDisabled(bDisabled) end

---Sets the default sticky item in the quickbuy
---Server only.
---@param pItem string
function CDOTABaseGameMode:SetDefaultStickyItem(pItem) end

---Set drafting hero banning time
---Server only.
---@param flValue number
function CDOTABaseGameMode:SetDraftingBanningTimeOverride(flValue) end

---Set drafting hero pick time
---Server only.
---@param flValue number
function CDOTABaseGameMode:SetDraftingHeroPickSelectTimeOverride(flValue) end

---Set a filter function to control the behavior when a unit picks up an item. (Modify the table and Return true to use new values, return false to cancel the event)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetExecuteOrderFilter(hFunction, hContext) end

---Set a fixed delay for all players to respawn after.
---Server only.
---@param flFixedRespawnTime number
function CDOTABaseGameMode:SetFixedRespawnTime(flFixedRespawnTime) end

---Turn the fog of war on or off.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetFogOfWarDisabled(bDisabled) end

---Prevent users from using the right click deny setting.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetForceRightClickAttackDisabled(bDisabled) end

---Specify a HUD skin that is forced on for this game mode.
---Server only.
---@param pValue string
function CDOTABaseGameMode:SetForcedHUDSkin(pValue) end

---Caps the number of players spawned when the game is reset. Used in tutorials where players are spawned in the script.
---Server only.
---@param cap integer
function CDOTABaseGameMode:SetForcedHeroCapOnReset(cap) end

---Set the constant rate that the fountain will regen mana. (-1 for default)
---Server only.
---@param flConstantManaRegen number
function CDOTABaseGameMode:SetFountainConstantManaRegen(flConstantManaRegen) end

---Set the percentage rate that the fountain will regen health. (-1 for default)
---Server only.
---@param flPercentageHealthRegen number
function CDOTABaseGameMode:SetFountainPercentageHealthRegen(flPercentageHealthRegen) end

---Set the percentage rate that the fountain will regen mana. (-1 for default)
---Server only.
---@param flPercentageManaRegen number
function CDOTABaseGameMode:SetFountainPercentageManaRegen(flPercentageManaRegen) end

---If set to true, enable 7.23 free courier mode.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetFreeCourierModeEnabled(bEnabled) end

---Allows clicks on friendly buildings to be handled normally.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetFriendlyBuildingMoveToEnabled(bEnabled) end

---bool bGive
---Server only.
---@param bGive boolean
function CDOTABaseGameMode:SetGiveFreeTPOnDeath(bGive) end

---Turn the sound when gold is acquired off/on.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetGoldSoundDisabled(bDisabled) end

---Set the HUD element visibility.
---Server only.
---@param iHUDElement integer
---@param bVisible boolean
function CDOTABaseGameMode:SetHUDVisible(iHUDElement, bVisible) end

---Set a filter function to control the behavior when a unit heals. (Modify the table and Return true to use new values, return false to cancel the event)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetHealingFilter(hFunction, hContext) end

---Specify whether the default combat events will show in the HUD.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetHudCombatEventsDisabled(bDisabled) end

---Set the amount blocked innately by melee heroes.
---Server only.
---@param nAmount integer
function CDOTABaseGameMode:SetInnateMeleeDamageBlockAmount(nAmount) end

---Set the amount innately blocked by melee heroes gained per level.
---Server only.
---@param nPerLevelAmount integer
function CDOTABaseGameMode:SetInnateMeleeDamageBlockPerLevelAmount(nPerLevelAmount) end

---Set the percent chance a melee hero will innately block damage.
---Server only.
---@param nPercent integer
function CDOTABaseGameMode:SetInnateMeleeDamageBlockPercent(nPercent) end

---Set a filter function to control what happens to items that are added to an inventory, return false to cancel the event
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetItemAddedToInventoryFilter(hFunction, hContext) end

---Set whether tombstones can be channeled to be removed by enemy heroes.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetKillableTombstones(bEnabled) end

---Mutes the in-game killing spree announcer.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetKillingSpreeAnnouncerDisabled(bDisabled) end

---Use to disable gold loss on death.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetLoseGoldOnDeath(bEnabled) end

---Server only.
---@param hScript handle
function CDOTABaseGameMode:SetLuaGameMode(hScript) end

---Set the maximum attack speed for units.
---Server only.
---@param nMaxSpeed integer
function CDOTABaseGameMode:SetMaximumAttackSpeed(nMaxSpeed) end

---Set the minimum attack speed for units.
---Server only.
---@param nMinSpeed integer
function CDOTABaseGameMode:SetMinimumAttackSpeed(nMinSpeed) end

---Set a filter function to control modifiers that are gained, return false to destroy modifier.
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetModifierGainedFilter(hFunction, hContext) end

---Set a filter function to control the behavior when a hero's experience is modified. (Modify the table and Return true to use new values, return false to cancel the event)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetModifyExperienceFilter(hFunction, hContext) end

---Set a filter function to control the behavior when a hero's gold is modified. (Modify the table and Return true to use new values, return false to cancel the event)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetModifyGoldFilter(hFunction, hContext) end

---When enabled, undiscovered items in the neutral item stash are hidden.
---Server only.
---@param bEnable boolean
function CDOTABaseGameMode:SetNeutralItemHideUndiscoveredEnabled(bEnable) end

---Allow items to be sent to the neutral stash.
---Server only.
---@param bEnable boolean
function CDOTABaseGameMode:SetNeutralStashEnabled(bEnable) end

---When enabled, the all neutral items tab cannot be viewed.
---Server only.
---@param bEnable boolean
function CDOTABaseGameMode:SetNeutralStashTeamViewOnlyEnabled(bEnable) end

---Set an override for the default selection entity, instead of each player's hero.
---Server only.
---@param hOverrideEntity handle
function CDOTABaseGameMode:SetOverrideSelectionEntity(hOverrideEntity) end

---Set pausing enabled/disabled
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetPauseEnabled(bEnabled) end

---bool bFilter
---Server only.
---@param bFilter boolean
function CDOTABaseGameMode:SetPlayerHeroAvailabilityFiltered(bFilter) end

---Set power rune spawn rate
---Server only.
---@param flInterval number
function CDOTABaseGameMode:SetPowerRuneSpawnInterval(flInterval) end

---Disables bonus items for randoming a hero.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetRandomHeroBonusItemGrantDisabled(bDisabled) end

---Turn the panel for showing recommended items at the shop off/on.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetRecommendedItemsDisabled(bDisabled) end

---Make it so illusions are immediately removed upon death, rather than sticking around for a few seconds.
---Server only.
---@param bRemove boolean
function CDOTABaseGameMode:SetRemoveIllusionsOnDeath(bRemove) end

---Sets the scale applied to non-fixed respawn times. 1 = default DOTA respawn calculations.
---Server only.
---@param flValue number
function CDOTABaseGameMode:SetRespawnTimeScale(flValue) end

---Set if a given type of rune is enabled.
---Server only.
---@param nRune integer
---@param bEnabled boolean
function CDOTABaseGameMode:SetRuneEnabled(nRune, bEnabled) end

---Set a filter function to control what rune spawns. (Modify the table and Return true to use new values, return false to cancel the event)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetRuneSpawnFilter(hFunction, hContext) end

---Enable/disable gold penalty for late picking.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetSelectionGoldPenaltyEnabled(bEnabled) end

---Allow items to be sent to the stash.
---Server only.
---@param bEnable boolean
function CDOTABaseGameMode:SetSendToStashEnabled(bEnable) end

---Turn purchasing items to the stash off/on. If purchasing to the stash is off the player must be at a shop to purchase items.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetStashPurchasingDisabled(bDisabled) end

---Hide the sticky item in the quickbuy.
---Server only.
---@param bDisabled boolean
function CDOTABaseGameMode:SetStickyItemDisabled(bDisabled) end

---Sets the item which goes in the TP scroll slot
---Server only.
---@param pItemName string
function CDOTABaseGameMode:SetTPScrollSlotItemOverride(pItemName) end

---Set the team values on the top game bar.
---Server only.
---@param iTeam integer
---@param nValue integer
function CDOTABaseGameMode:SetTopBarTeamValue(iTeam, nValue) end

---Override the values of the team values on the top game bar.
---Server only.
---@param bOverride boolean
function CDOTABaseGameMode:SetTopBarTeamValuesOverride(bOverride) end

---Turning on/off the team values on the top game bar.
---Server only.
---@param bVisible boolean
function CDOTABaseGameMode:SetTopBarTeamValuesVisible(bVisible) end

---Enables/Disables tower backdoor protection.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetTowerBackdoorProtectionEnabled(bEnabled) end

---Set a filter function to control when tracking projectiles are launched. (Modify the table and Return true to use new values, return false to cancel the event)
---Server only.
---@param hFunction handle
---@param hContext handle
function CDOTABaseGameMode:SetTrackingProjectileFilter(hFunction, hContext) end

---Enable or disable unseen fog of war. When enabled parts of the map the player has never seen will be completely hidden by fog of war.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetUnseenFogOfWarEnabled(bEnabled) end

---Turn on custom-defined XP values for hero level ups.  The table should be defined before switching this on.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetUseCustomHeroLevels(bEnabled) end

---If set to true, use current rune spawn rules.  Either setting respects custom spawn intervals.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetUseDefaultDOTARuneSpawnLogic(bEnabled) end

---Enables or disables turbo couriers.
---Server only.
---@param bEnabled boolean
function CDOTABaseGameMode:SetUseTurboCouriers(bEnabled) end

---Sets the time from game start during which water runes spawn
---Server only.
---@param flValue number
function CDOTABaseGameMode:SetWaterRuneLastSpawnTime(flValue) end

---Set if weather effects are disabled.
---Server only.
---@param bDisable boolean
function CDOTABaseGameMode:SetWeatherEffectsDisabled(bDisable) end

---Set xp rune spawn rate
---Server only.
---@param flInterval number
function CDOTABaseGameMode:SetXPRuneSpawnInterval(flInterval) end

---Server only.
---@return boolean
function CDOTABaseGameMode:ShouldGiveFreeTPOnDeath() end
