---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDotaTutorialNPCBlocker : CBaseAnimatingOverlay
CDotaTutorialNPCBlocker = {}

---Server only.
function CDotaTutorialNPCBlocker:IsNull(...) end

---Server only.
---@param bEnabled boolean
function CDotaTutorialNPCBlocker:SetEnabled(bEnabled) end

---Server only.
---@param hBlocker handle
function CDotaTutorialNPCBlocker:SetOtherBlocker(hBlocker) end
