---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTATutorial
CDOTATutorial = {}

---Add a computer controlled bot.
---Server only.
---@param string_1 string
---@param string_2 string
---@param string_3 string
---@param bool_4 boolean
---@return boolean
function CDOTATutorial:AddBot(string_1, string_2, string_3, bool_4) end

---Add a quest to the quest log
---Server only.
---@param string_1 string
---@param int_2 integer
---@param string_3 string
---@param string_4 string
function CDOTATutorial:AddQuest(string_1, int_2, string_3, string_4) end

---Add an item to the shop whitelist.
---Server only.
---@param string_1 string
function CDOTATutorial:AddShopWhitelistItem(string_1) end

---Complete a quest,
---Server only.
---@param string_1 string
function CDOTATutorial:CompleteQuest(string_1) end

---Add a task to move to a specific location
---Server only.
---@param unknown_1 any
function CDOTATutorial:CreateLocationTask(unknown_1) end

---Alert the player when a creep becomes agro to their hero.
---Server only.
---@param bool_1 boolean
function CDOTATutorial:EnableCreepAggroViz(bool_1) end

---Enable the tip to alert players how to find their hero.
---Server only.
---@param bool_1 boolean
function CDOTATutorial:EnablePlayerOffscreenTip(bool_1) end

---Alert the player when a tower becomes agro to their hero.
---Server only.
---@param bool_1 boolean
function CDOTATutorial:EnableTowerAggroViz(bool_1) end

---End the tutorial.
---Server only.
function CDOTATutorial:FinishTutorial() end

---Force the start of the game.
---Server only.
function CDOTATutorial:ForceGameStart() end

---Is this item currently in the white list.
---Server only.
---@param string_1 string
---@return boolean
function CDOTATutorial:IsItemInWhiteList(string_1) end

---Server only.
function CDOTATutorial:IsNull(...) end

---Moves the camera to a position.
---Server only.
---@param unknown_1 any
function CDOTATutorial:MoveCameraToLocation(unknown_1) end

---Remove an item from the shop whitelist.
---Server only.
---@param string_1 string
function CDOTATutorial:RemoveShopWhitelistItem(string_1) end

---Select a hero for the local player
---Server only.
---@param string_1 string
function CDOTATutorial:SelectHero(string_1) end

---Select the team for the local player
---Server only.
---@param string_1 string
function CDOTATutorial:SelectPlayerTeam(string_1) end

---Set the current item guide.
---Server only.
---@param string_1 string
function CDOTATutorial:SetItemGuide(string_1) end

---Set gold amount for the tutorial player. (int) GoldAmount, (bool) true=Set, false=Modify
---Server only.
---@param int_1 integer
---@param bool_2 boolean
function CDOTATutorial:SetOrModifyPlayerGold(int_1, bool_2) end

---Set players quick buy item.
---Server only.
---@param string_1 string
function CDOTATutorial:SetQuickBuy(string_1) end

---Set the shop open or closed.
---Server only.
---@param bool_1 boolean
function CDOTATutorial:SetShopOpen(bool_1) end

---Set a tutorial convar
---Server only.
---@param string_1 string
---@param string_2 string
function CDOTATutorial:SetTutorialConvar(string_1, string_2) end

---Set the UI to use a reduced version to focus attention to specific elements.
---Server only.
---@param int_1 integer
function CDOTATutorial:SetTutorialUI(int_1) end

---Set if we should whitelist shop items.
---Server only.
---@param bool_1 boolean
function CDOTATutorial:SetWhiteListEnabled(bool_1) end

---Initialize Tutorial Mode
---Server only.
function CDOTATutorial:StartTutorialMode() end

---Upgrade a specific ability for the local hero
---Server only.
---@param string_1 string
function CDOTATutorial:UpgradePlayerAbility(string_1) end
