---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTAVoteSystem
CDOTAVoteSystem = {}

---Server only.
function CDOTAVoteSystem:IsNull(...) end

---Starts a vote, based upon a table of parameters
---Server only.
---@param handle_1 handle
function CDOTAVoteSystem:StartVote(handle_1) end
