---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_CustomUIManager
CDOTA_CustomUIManager = {}

---Create a new custom UI HUD element for the specified player(s). ( PlayerID_t PlayerID /*-1 means everyone*/, string ElementID /* should be unique */, string LayoutFileName, table DialogVariables /* can be nil */ )
---Server only.
---@param int_1 integer
---@param string_2 string
---@param string_3 string
---@param handle_4 handle
function CDOTA_CustomUIManager:DynamicHud_Create(int_1, string_2, string_3, handle_4) end

---Destroy a custom hud element ( PlayerID_t PlayerID /*-1 means everyone*/, string ElementID )
---Server only.
---@param int_1 integer
---@param string_2 string
function CDOTA_CustomUIManager:DynamicHud_Destroy(int_1, string_2) end

---Add or modify dialog variables for an existing custom hud element ( PlayerID_t PlayerID /*-1 means everyone*/, string ElementID, table DialogVariables )
---Server only.
---@param int_1 integer
---@param string_2 string
---@param handle_3 handle
function CDOTA_CustomUIManager:DynamicHud_SetDialogVariables(int_1, string_2, handle_3) end

---Toggle the visibility of an existing custom hud element ( PlayerID_t PlayerID /*-1 means everyone*/, string ElementID, bool Visible )
---Server only.
---@param int_1 integer
---@param string_2 string
---@param bool_3 boolean
function CDOTA_CustomUIManager:DynamicHud_SetVisible(int_1, string_2, bool_3) end

---Server only.
function CDOTA_CustomUIManager:IsNull(...) end
