---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_PlayerResource : CBaseEntity
CDOTA_PlayerResource = {}

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:AddAegisPickup(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@param nReason integer
function CDOTA_PlayerResource:AddCandyEvent(iPlayerID, nReason) end

---Server only.
---@param iPlayerID integer
---@param flFarmValue number
---@param bEarnedValue boolean
function CDOTA_PlayerResource:AddClaimedFarm(iPlayerID, flFarmValue, bEarnedValue) end

---Server only.
---@param iPlayerID integer
---@param iCost integer
function CDOTA_PlayerResource:AddGoldSpentOnSupport(iPlayerID, iCost) end

---Server only.
---@param iPlayerID integer
---@param nTeamNumber integer
---@param hItem handle
function CDOTA_PlayerResource:AddNeutralItemToStash(iPlayerID, nTeamNumber, hItem) end

---Server only.
---@param iPlayerID integer
---@param nRunes integer
function CDOTA_PlayerResource:AddRunePickup(iPlayerID, nRunes) end

---Server only.
---@param nUnitOwnerPlayerID integer
---@param nOtherPlayerID integer
---@return boolean
function CDOTA_PlayerResource:AreUnitsSharedWithPlayerID(nUnitOwnerPlayerID, nOtherPlayerID) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:CanRepick(iPlayerID) end

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:ClearKillsMatrix(iPlayerID) end

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:ClearLastHitMultikill(iPlayerID) end

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:ClearLastHitStreak(iPlayerID) end

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:ClearPlayer(iPlayerID) end

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:ClearRawPlayerDamageMatrix(iPlayerID) end

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:ClearStreak(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetAegisPickups(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetAssists(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetBroadcasterChannel(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetBroadcasterChannelSlot(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetClaimedDenies(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@param bOnlyEarned boolean
---@return number
function CDOTA_PlayerResource:GetClaimedFarm(iPlayerID, bOnlyEarned) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetClaimedMisses(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return any
function CDOTA_PlayerResource:GetConnectionState(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@param bTotal boolean
---@return number
function CDOTA_PlayerResource:GetCreepDamageTaken(iPlayerID, bTotal) end

---Server only.
function CDOTA_PlayerResource:GetCreepDamageTaken_Engine(...) end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetCustomBuybackCooldown(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetCustomBuybackCost(iPlayerID) end

---Get the current custom team assignment for this player.
---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetCustomTeamAssignment(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@param iVictimID integer
---@return number
function CDOTA_PlayerResource:GetDamageDoneToHero(iPlayerID, iVictimID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetDeaths(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetDenies(iPlayerID) end

---(nPlayerID)
---Server only.
---@param nPlayerID integer
---@return handle
function CDOTA_PlayerResource:GetEventGameUpgrades(nPlayerID) end

---Server only.
---@param nPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetEventPointsForPlayerID(nPlayerID) end

---Server only.
---@param nPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetEventPremiumPoints(nPlayerID) end

---Server only.
function CDOTA_PlayerResource:GetEventPremiumPointsGranted(...) end

---Server only.
function CDOTA_PlayerResource:GetEventRankGranted(...) end

---Server only.
---@param nPlayerID integer
---@return any
function CDOTA_PlayerResource:GetEventRanks(nPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetGold(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetGoldLostToDeath(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetGoldPerMin(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetGoldSpentOnBuybacks(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetGoldSpentOnConsumables(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetGoldSpentOnItems(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetGoldSpentOnSupport(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetHealing(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@param bTotal boolean
---@return number
function CDOTA_PlayerResource:GetHeroDamageTaken(iPlayerID, bTotal) end

---Server only.
function CDOTA_PlayerResource:GetHeroDamageTaken_Engine(...) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetKills(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@param iVictimID integer
---@return integer
function CDOTA_PlayerResource:GetKillsDoneToHero(iPlayerID, iVictimID) end

---(nPlayerID)
---Server only.
---@param nPlayerID integer
---@return handle
function CDOTA_PlayerResource:GetLabyrinthEventGameHeroUnlocks(nPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetLastHitMultikill(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetLastHitStreak(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetLastHits(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetLevel(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return any
function CDOTA_PlayerResource:GetLiveSpectatorTeam(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetMisses(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetNearbyCreepDeaths(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetNetWorth(iPlayerID) end

---(nPlayerID, eEvent, nActionID)
---Server only.
---@param nPlayerID integer
---@param nEventID integer
---@param unActionID integer
---@return integer
function CDOTA_PlayerResource:GetNetworkedEventActionClaimCount(nPlayerID, nEventID, unActionID) end

---(nPlayerID, eEvent, pActionName)
---Server only.
---@param nPlayerID integer
---@param nEventID integer
---@param pActionName string
---@return integer
function CDOTA_PlayerResource:GetNetworkedEventActionClaimCountByName(nPlayerID, nEventID, pActionName) end

---Server only.
---@param nCourierIndex integer
---@param nTeamNumber integer
---@return handle
function CDOTA_PlayerResource:GetNthCourierForTeam(nCourierIndex, nTeamNumber) end

---Server only.
---@param iTeamNumber integer
---@param iNthPlayer integer
---@return integer
function CDOTA_PlayerResource:GetNthPlayerIDOnTeam(iTeamNumber, iNthPlayer) end

---Players on a valid team (radiant, dire, or custom*) who haven't abandoned the game
---Server only.
---@return integer
function CDOTA_PlayerResource:GetNumConnectedHumanPlayers() end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetNumConsumablesPurchased(iPlayerID) end

---Server only.
---@param nTeamNumber integer
---@return integer
function CDOTA_PlayerResource:GetNumCouriersForTeam(nTeamNumber) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetNumItemsPurchased(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return any
function CDOTA_PlayerResource:GetPartyID(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return handle
function CDOTA_PlayerResource:GetPlayer(iPlayerID) end

---Includes spectators and players not assigned to a team
---Server only.
---@return integer
function CDOTA_PlayerResource:GetPlayerCount() end

---Server only.
---@param iTeam integer
---@return integer
function CDOTA_PlayerResource:GetPlayerCountForTeam(iTeam) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:GetPlayerLoadedCompletely(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return string
function CDOTA_PlayerResource:GetPlayerName(iPlayerID) end

---Server only.
---@param nPlayerId integer
---@return handle
function CDOTA_PlayerResource:GetPreferredCourierForPlayer(nPlayerId) end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetRawPlayerDamage(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetReliableGold(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetRespawnSeconds(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetRoshanKills(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetRunePickups(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return handle
function CDOTA_PlayerResource:GetSelectedHeroEntity(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetSelectedHeroID(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return string
function CDOTA_PlayerResource:GetSelectedHeroName(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetSteamAccountID(iPlayerID) end

---Get the 64 bit steam ID for a given player.
---Server only.
---@param iPlayerID integer
---@return any
function CDOTA_PlayerResource:GetSteamID(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetStreak(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetStuns(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetTeam(iPlayerID) end

---Server only.
---@param iTeam integer
---@return integer
function CDOTA_PlayerResource:GetTeamKills(iTeam) end

---(Deprecated: use GetNumConnectedHumanPlayers) Players on a valid team (radiant, dire, or custom*) who haven't abandoned the game
---Server only.
---@return integer
function CDOTA_PlayerResource:GetTeamPlayerCount() end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetTimeOfLastConsumablePurchase(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetTimeOfLastDeath(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetTimeOfLastItemPurchase(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetTotalEarnedGold(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetTotalEarnedXP(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetTotalGoldSpent(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@param bTotal boolean
---@return number
function CDOTA_PlayerResource:GetTowerDamageTaken(iPlayerID, bTotal) end

---Server only.
function CDOTA_PlayerResource:GetTowerDamageTaken_Engine(...) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetTowerKills(iPlayerID) end

---Server only.
---@param nPlayerID integer
---@param nOtherPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetUnitShareMaskForPlayer(nPlayerID, nOtherPlayerID) end

---Server only.
---@param iPlayerID integer
---@return integer
function CDOTA_PlayerResource:GetUnreliableGold(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return number
function CDOTA_PlayerResource:GetXPPerMin(iPlayerID) end

---Does this player have a custom game ticket for this game?
---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:HasCustomGameTicketForPlayerID(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:HasRandomed(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:HasSelectedHero(iPlayerID) end

---Server only.
---@return boolean
function CDOTA_PlayerResource:HasSetNetworkedEventActionClaimCount() end

---Server only.
---@return boolean
function CDOTA_PlayerResource:HaveAllPlayersJoined() end

---Defined in scripts/vscripts/game/gameinit.lua:151.
---Server only.
function CDOTA_PlayerResource:HeroLevelUp(nPlayerID) end

---Server only.
---@param iPlayerID integer
---@param iVictimID integer
function CDOTA_PlayerResource:IncrementAssists(iPlayerID, iVictimID) end

---Server only.
---@param iPlayerID integer
---@param nValue integer
function CDOTA_PlayerResource:IncrementClaimedDenies(iPlayerID, nValue) end

---Server only.
---@param iPlayerID integer
---@param nValue integer
function CDOTA_PlayerResource:IncrementClaimedMisses(iPlayerID, nValue) end

---Server only.
---@param iPlayerID integer
---@param iKillerID integer
function CDOTA_PlayerResource:IncrementDeaths(iPlayerID, iKillerID) end

---Server only.
function CDOTA_PlayerResource:IncrementDeaths_Engine(...) end

---Server only.
---@param iPlayerID integer
---@param nValue integer
function CDOTA_PlayerResource:IncrementDenies(iPlayerID, nValue) end

---Server only.
---@param iPlayerID integer
---@param iVictimID integer
function CDOTA_PlayerResource:IncrementKills(iPlayerID, iVictimID) end

---Server only.
---@param iPlayerID integer
---@param nCount integer
function CDOTA_PlayerResource:IncrementLastHitMultikill(iPlayerID, nCount) end

---Server only.
---@param iPlayerID integer
---@param nCount integer
function CDOTA_PlayerResource:IncrementLastHitStreak(iPlayerID, nCount) end

---Server only.
---@param iPlayerID integer
---@param nCount integer
function CDOTA_PlayerResource:IncrementLastHits(iPlayerID, nCount) end

---Server only.
---@param iPlayerID integer
---@param nValue integer
function CDOTA_PlayerResource:IncrementMisses(iPlayerID, nValue) end

---Server only.
---@param iPlayerID integer
---@param nCreeps integer
function CDOTA_PlayerResource:IncrementNearbyCreepDeaths(iPlayerID, nCreeps) end

---Server only.
---@param iPlayerID integer
---@param nCount integer
function CDOTA_PlayerResource:IncrementStreak(iPlayerID, nCount) end

---Server only.
---@param iPlayerID integer
---@param iXP integer
---@param nReason integer
function CDOTA_PlayerResource:IncrementTotalEarnedXP(iPlayerID, iXP, nReason) end

---Server only.
function CDOTA_PlayerResource:IncrementTotalEarnedXP_Engine(...) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:IsBroadcaster(iPlayerID) end

---Server only.
---@param nPlayerID integer
---@param nOtherPlayerID integer
---@return boolean
function CDOTA_PlayerResource:IsDisableHelpSetForPlayerID(nPlayerID, nOtherPlayerID) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:IsFakeClient(iPlayerID) end

---Server only.
---@param pHeroname string
---@param bIgnoreUnrevealedPick boolean
---@return boolean
function CDOTA_PlayerResource:IsHeroSelected(pHeroname, bIgnoreUnrevealedPick) end

---Server only.
---@param nUnitOwnerPlayerID integer
---@param nOtherPlayerID integer
---@return boolean
function CDOTA_PlayerResource:IsHeroSharedWithPlayerID(nUnitOwnerPlayerID, nOtherPlayerID) end

---Server only.
function CDOTA_PlayerResource:IsNull(...) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:IsValidPlayer(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:IsValidPlayerID(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@return boolean
function CDOTA_PlayerResource:IsValidTeamPlayer(iPlayerID) end

---Server only.
---@param nPlayerID integer
---@return boolean
function CDOTA_PlayerResource:IsValidTeamPlayerID(nPlayerID) end

---Server only.
---@param iPlayerID integer
---@param iGoldChange integer
---@param bReliable boolean
---@param nReason integer
---@return integer
function CDOTA_PlayerResource:ModifyGold(iPlayerID, iGoldChange, bReliable, nReason) end

---Server only.
---@return integer
function CDOTA_PlayerResource:NumPlayers() end

---Server only.
---@return integer
function CDOTA_PlayerResource:NumTeamPlayers() end

---Increment or decrement consumable charges (nPlayerID, item_definition_index, nChargeIncrementOrDecrement)
---Server only.
---@param iPlayerID integer
---@param item_definition_index integer
---@param nChargeIncrementOrDecrement integer
function CDOTA_PlayerResource:RecordConsumableAbilityChargeChange(iPlayerID, item_definition_index, nChargeIncrementOrDecrement) end

---Server only.
---@param iPlayerID integer
---@param eEvent integer
---@param unActionID integer
---@param unAudit integer
---@param unQuantity integer
---@param unAuditData integer
function CDOTA_PlayerResource:RecordEventActionGrant(iPlayerID, eEvent, unActionID, unAudit, unQuantity, unAuditData) end

---Server only.
---@param iPlayerID integer
---@param pszActionName string
---@param unAudit integer
---@param unQuantity integer
---@param unAuditData integer
function CDOTA_PlayerResource:RecordEventActionGrantForPrimaryEvent(iPlayerID, pszActionName, unAudit, unQuantity, unAuditData) end

---(playerID, heroClassName, gold, XP) - replaces the player's hero with a new one of the specified class, gold and XP
---Server only.
---@param iPlayerID integer
---@param pszHeroClass string
---@param nGold integer
---@param nXP integer
---@return handle
function CDOTA_PlayerResource:ReplaceHeroWith(iPlayerID, pszHeroClass, nGold, nXP) end

---(playerID, heroClassName, gold, XP) - replaces the player's hero with a new one of the specified class, gold and XP, without transferring items/abilities if same hero
---Server only.
---@param iPlayerID integer
---@param pszHeroClass string
---@param nGold integer
---@param nXP integer
---@return handle
function CDOTA_PlayerResource:ReplaceHeroWithNoTransfer(iPlayerID, pszHeroClass, nGold, nXP) end

---Server only.
---@param nPlayerID integer
function CDOTA_PlayerResource:ResetBuybackCostTime(nPlayerID) end

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:ResetTotalEarnedGold(iPlayerID) end

---Server only.
---@param nPlayerID integer
---@param flBuybackCooldown number
function CDOTA_PlayerResource:SetBuybackCooldownTime(nPlayerID, flBuybackCooldown) end

---Server only.
---@param nPlayerID integer
---@param flBuybackCooldown number
function CDOTA_PlayerResource:SetBuybackGoldLimitTime(nPlayerID, flBuybackCooldown) end

---(playerID, entity) - force the given player's camera to follow the given entity
---Server only.
---@param nPlayerID integer
---@param hTarget handle
function CDOTA_PlayerResource:SetCameraTarget(nPlayerID, hTarget) end

---Server only.
---@param iPlayerID integer
---@param bCanRepick boolean
function CDOTA_PlayerResource:SetCanRepick(iPlayerID, bCanRepick) end

---Set the buyback cooldown for this player.
---Server only.
---@param iPlayerID integer
---@param flCooldownTime number
function CDOTA_PlayerResource:SetCustomBuybackCooldown(iPlayerID, flCooldownTime) end

---Set the buyback cost for this player.
---Server only.
---@param iPlayerID integer
---@param iGoldCost integer
function CDOTA_PlayerResource:SetCustomBuybackCost(iPlayerID, iGoldCost) end

---Server only.
---@param iPlayerID integer
---@param iParam integer
function CDOTA_PlayerResource:SetCustomIntParam(iPlayerID, iParam) end

---Set custom color for player (minimap, scoreboard, etc)
---Server only.
---@param iPlayerID integer
---@param r integer
---@param g integer
---@param b integer
function CDOTA_PlayerResource:SetCustomPlayerColor(iPlayerID, r, g, b) end

---Set custom team assignment for this player.
---Server only.
---@param iPlayerID integer
---@param iTeamAssignment integer
function CDOTA_PlayerResource:SetCustomTeamAssignment(iPlayerID, iTeamAssignment) end

---Server only.
---@param iPlayerID integer
---@param iGold integer
---@param bReliable boolean
function CDOTA_PlayerResource:SetGold(iPlayerID, iGold, bReliable) end

---Server only.
---@param iPlayerID integer
function CDOTA_PlayerResource:SetHasRandomed(iPlayerID) end

---Server only.
---@param iPlayerID integer
---@param flLastBuybackTime number
function CDOTA_PlayerResource:SetLastBuybackTime(iPlayerID, flLastBuybackTime) end

---Set the forced selection entity for a player.
---Server only.
---@param nPlayerID integer
---@param hEntity handle
function CDOTA_PlayerResource:SetOverrideSelectionEntity(nPlayerID, hEntity) end

---Server only.
---@param nPlayerID integer
---@param nOtherPlayerID integer
---@param nFlag integer
---@param bState boolean
function CDOTA_PlayerResource:SetUnitShareMaskForPlayer(nPlayerID, nOtherPlayerID, nFlag, bState) end

---Server only.
---@param iPlayerID integer
---@param iCost integer
---@param iReason integer
function CDOTA_PlayerResource:SpendGold(iPlayerID, iCost, iReason) end

---Server only.
---@param iPlayerID integer
---@param iTeamNumber integer
---@param desiredSlot integer
function CDOTA_PlayerResource:UpdateTeamSlot(iPlayerID, iTeamNumber, desiredSlot) end

---Server only.
---@param pHeroFilename string
---@param bIgnoreUnrevealedPick boolean
---@return integer
function CDOTA_PlayerResource:WhoSelectedHero(pHeroFilename, bIgnoreUnrevealedPick) end
