---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_ShopTrigger : CBaseTrigger
CDOTA_ShopTrigger = {}

---Get the DOTA_SHOP_TYPE
---Server only.
---@return integer
function CDOTA_ShopTrigger:GetShopType() end

---Server only.
function CDOTA_ShopTrigger:IsNull(...) end

---Set the DOTA_SHOP_TYPE.
---Server only.
---@param eShopType integer
function CDOTA_ShopTrigger:SetShopType(eShopType) end
