---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Ability_Nian_Roar : CDOTABaseAbility
CDOTA_Ability_Nian_Roar = {}

---Number of times Nian has used the roar
---Server only.
---@return integer
function CDOTA_Ability_Nian_Roar:GetCastCount() end

---Server only.
function CDOTA_Ability_Nian_Roar:IsNull(...) end
