---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CDOTA_Item_BagOfGold : CDOTA_Item
CDOTA_Item_BagOfGold = {}

---Server only.
function CDOTA_Item_BagOfGold:IsNull(...) end

---Set the life time of this item
---Server only.
---@param flTime number
function CDOTA_Item_BagOfGold:SetLifeTime(flTime) end
