---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---@class CEntities
CEntities = CEntities

---Creates an entity by classname
---Server only.
---@param string_1 string
---@return handle
function CEntities:CreateByClassname(string_1) end

---Finds all entities by class name. Returns an array containing all the found entities.
---Server only.
---@param string_1 string
---@return table
function CEntities:FindAllByClassname(string_1) end

---Find entities by class name within a radius.
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param float_3 number
---@return table
function CEntities:FindAllByClassnameWithin(string_1, unknown_2, float_3) end

---Find entities by model name.
---Server only.
---@param string_1 string
---@return table
function CEntities:FindAllByModel(string_1) end

---Find all entities by name. Returns an array containing all the found entities in it.
---Server only.
---@param string_1 string
---@return table
function CEntities:FindAllByName(string_1) end

---Find entities by name within a radius.
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param float_3 number
---@return table
function CEntities:FindAllByNameWithin(string_1, unknown_2, float_3) end

---Find entities by targetname.
---Server only.
---@param string_1 string
---@return table
function CEntities:FindAllByTarget(string_1) end

---Find entities within a radius.
---Server only.
---@param unknown_1 any
---@param float_2 number
---@return table
function CEntities:FindAllInSphere(unknown_1, float_2) end

---Find entities by class name. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
---Server only.
---@param handle_1 handle
---@param string_2 string
---@return handle
function CEntities:FindByClassname(handle_1, string_2) end

---Find entities by class name nearest to a point.
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param float_3 number
---@return handle
function CEntities:FindByClassnameNearest(string_1, unknown_2, float_3) end

---Find entities by class name within a radius. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param unknown_3 any
---@param float_4 number
---@return handle
function CEntities:FindByClassnameWithin(handle_1, string_2, unknown_3, float_4) end

---Find entities by model name. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
---Server only.
---@param handle_1 handle
---@param string_2 string
---@return handle
function CEntities:FindByModel(handle_1, string_2) end

---Find entities by model name within a radius. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param unknown_3 any
---@param float_4 number
---@return handle
function CEntities:FindByModelWithin(handle_1, string_2, unknown_3, float_4) end

---Find entities by name. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
---Server only.
---@param handle_1 handle
---@param string_2 string
---@return handle
function CEntities:FindByName(handle_1, string_2) end

---Find entities by name nearest to a point.
---Server only.
---@param string_1 string
---@param unknown_2 any
---@param float_3 number
---@return handle
function CEntities:FindByNameNearest(string_1, unknown_2, float_3) end

---Find entities by name within a radius. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
---Server only.
---@param handle_1 handle
---@param string_2 string
---@param unknown_3 any
---@param float_4 number
---@return handle
function CEntities:FindByNameWithin(handle_1, string_2, unknown_3, float_4) end

---Find entities by targetname. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
---Server only.
---@param handle_1 handle
---@param string_2 string
---@return handle
function CEntities:FindByTarget(handle_1, string_2) end

---Find entities within a radius. Pass 'null' to start an iteration, or reference to a previously found entity to continue a search
---Server only.
---@param handle_1 handle
---@param unknown_2 any
---@param float_3 number
---@return handle
function CEntities:FindInSphere(handle_1, unknown_2, float_3) end
