---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CEnvEntityMaker : CBaseEntity
CEnvEntityMaker = {}

---Server only.
function CEnvEntityMaker:IsNull(...) end

---Create an entity at the location of the maker
---Server only.
function CEnvEntityMaker:SpawnEntity() end

---Create an entity at the location of a specified entity instance
---Server only.
---@param hEntity handle
function CEnvEntityMaker:SpawnEntityAtEntityOrigin(hEntity) end

---Create an entity at a specified location and orientaton, orientation is Euler angle in degrees (pitch, yaw, roll)
---Server only.
---@param vecAlternateOrigin any
---@param vecAlternateAngles Vector
function CEnvEntityMaker:SpawnEntityAtLocation(vecAlternateOrigin, vecAlternateAngles) end

---Create an entity at the location of a named entity
---Server only.
---@param pszName string
function CEnvEntityMaker:SpawnEntityAtNamedEntityOrigin(pszName) end
