---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CFoWBlockerRegion : CBaseEntity
CFoWBlockerRegion = {}

---AddRectangularBlocker( vMins, vMaxs, bClear ) : Sets or clears a blocker rectangle
---Server only.
---@param vMins any
---@param vMaxs any
---@param bClearRegion boolean
function CFoWBlockerRegion:AddRectangularBlocker(vMins, vMaxs, bClearRegion) end

---AddRectangularOutlineBlocker( vMins, vMaxs, bClear ) : Sets or clears a blocker rectangle outline
---Server only.
---@param vMins any
---@param vMaxs any
---@param bClearRegion boolean
function CFoWBlockerRegion:AddRectangularOutlineBlocker(vMins, vMaxs, bClearRegion) end

---Server only.
function CFoWBlockerRegion:IsNull(...) end
