---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CInfoData : CBaseEntity
CInfoData = {}

---Server only.
function CInfoData:IsNull(...) end

---Query color data for this key
---Server only.
---@param tok any
---@param vDefault Vector
---@return Vector
function CInfoData:QueryColor(tok, vDefault) end

---Query float data for this key
---Server only.
---@param tok any
---@param flDefault number
---@return number
function CInfoData:QueryFloat(tok, flDefault) end

---Query int data for this key
---Server only.
---@param tok any
---@param nDefault integer
---@return integer
function CInfoData:QueryInt(tok, nDefault) end

---Query number data for this key
---Server only.
---@param tok any
---@param flDefault number
---@return number
function CInfoData:QueryNumber(tok, flDefault) end

---Query string data for this key
---Server only.
---@param tok any
---@param pDefault string
---@return string
function CInfoData:QueryString(tok, pDefault) end

---Query vector data for this key
---Server only.
---@param tok any
---@param vDefault Vector
---@return Vector
function CInfoData:QueryVector(tok, vDefault) end
