---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CInfoPlayerStartDota : CPointEntity
CInfoPlayerStartDota = {}

---Returns whether the object is currently active
---Server only.
---@return boolean
function CInfoPlayerStartDota:IsEnabled() end

---Server only.
function CInfoPlayerStartDota:IsNull(...) end

---Enable or disable the obstruction
---Server only.
---@param bEnabled boolean
function CInfoPlayerStartDota:SetEnabled(bEnabled) end
