---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CLogicScript : CBaseEntity
CLogicScript = {}

---Server only.
function CLogicScript:IsNull(...) end
