---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CMarkupVolumeTagged : CBaseEntity
CMarkupVolumeTagged = {}

---Does this volume have the given tag.
---Server only.
---@param pszTagName any
---@return boolean
function CMarkupVolumeTagged:HasTag(pszTagName) end

---Server only.
function CMarkupVolumeTagged:IsNull(...) end
