---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CParticleSystem : CBaseModelEntity
CParticleSystem = {}

---Server only.
function CParticleSystem:IsNull(...) end
