---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CPhysicsProp : CBaseAnimatingActivity
CPhysicsProp = {}

---Disable motion for the prop
---Server only.
function CPhysicsProp:DisableMotion() end

---Enable motion for the prop
---Server only.
function CPhysicsProp:EnableMotion() end

---Server only.
function CPhysicsProp:IsNull(...) end
