---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CPointEntity : CBaseEntity
CPointEntity = {}

---Server only.
function CPointEntity:IsNull(...) end
