---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CPointClientUIWorldPanel : CBaseModelEntity
CPointClientUIWorldPanel = {}

---Tells the panel to accept user input.
---Server only.
function CPointClientUIWorldPanel:AcceptUserInput() end

---Adds CSS class(es) to the panel
---Server only.
---@param pszClasses string
function CPointClientUIWorldPanel:AddCSSClasses(pszClasses) end

---Tells the panel to ignore user input.
---Server only.
function CPointClientUIWorldPanel:IgnoreUserInput() end

---Returns whether this entity is grabbable.
---Server only.
---@return boolean
function CPointClientUIWorldPanel:IsGrabbable() end

---Server only.
function CPointClientUIWorldPanel:IsNull(...) end

---Remove CSS class(es) from the panel
---Server only.
---@param pszClasses string
function CPointClientUIWorldPanel:RemoveCSSClasses(pszClasses) end
