---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CPointWorldText : CBaseModelEntity
CPointWorldText = {}

---Server only.
function CPointWorldText:IsNull(...) end

---Set the message on this entity.
---Server only.
---@param pMessage string
function CPointWorldText:SetMessage(pMessage) end
