---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CSceneEntity : CBaseEntity
CSceneEntity = {}

---Adds a team (by index) to the broadcast list
---Server only.
---@param int_1 integer
function CSceneEntity:AddBroadcastTeamTarget(int_1) end

---Cancel scene playback
---Server only.
function CSceneEntity:Cancel() end

---Returns length of this scene in seconds.
---Server only.
---@return number
function CSceneEntity:EstimateLength() end

---given an entity reference, such as !target, get actual entity from scene object
---Server only.
---@param string_1 string
---@return handle
function CSceneEntity:FindNamedEntity(string_1) end

---Server only.
function CSceneEntity:IsNull(...) end

---If this scene is currently paused.
---Server only.
---@return boolean
function CSceneEntity:IsPaused() end

---If this scene is currently playing.
---Server only.
---@return boolean
function CSceneEntity:IsPlayingBack() end

---Removes a team (by index) from the broadcast list
---Server only.
---@param int_1 integer
function CSceneEntity:RemoveBroadcastTeamTarget(int_1) end

---Start scene playback, takes activatorEntity as param
---Server only.
---@param handle_1 handle
function CSceneEntity:Start(handle_1) end
