---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CScriptHeroList
CScriptHeroList = {}

---Returns all the heroes in the world
---Server only.
---@return table
function CScriptHeroList:GetAllHeroes() end

---Get the Nth hero in the Hero List
---Server only.
---@param int_1 integer
---@return handle
function CScriptHeroList:GetHero(int_1) end

---Returns the number of heroes in the world
---Server only.
---@return integer
function CScriptHeroList:GetHeroCount() end

---Server only.
function CScriptHeroList:IsNull(...) end
