---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CScriptUniformRandomStream
CScriptUniformRandomStream = {}

---Server only.
function CScriptUniformRandomStream:IsNull(...) end

---Server only.
---@param flMinVal number
---@param flMaxVal number
---@return number
function CScriptUniformRandomStream:RandomFloat(flMinVal, flMaxVal) end

---Server only.
---@param flMinVal number
---@param flMaxVal number
---@param flExponent number
---@return number
function CScriptUniformRandomStream:RandomFloatExp(flMinVal, flMaxVal, flExponent) end

---Server only.
---@param iMinVal integer
---@param iMaxVal integer
---@return integer
function CScriptUniformRandomStream:RandomInt(iMinVal, iMaxVal) end

---Server only.
---@param iPercentage integer
---@return boolean
function CScriptUniformRandomStream:RollPercentage(iPercentage) end
