---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class CTakeDamageInfo
CTakeDamageInfo = {}

---Server only.
---@param flAddAmount number
function CTakeDamageInfo:AddDamage(flAddAmount) end

---Server only.
---@param iDamageType integer
function CTakeDamageInfo:AddDamageType(iDamageType) end

---Server only.
---@return integer
function CTakeDamageInfo:GetAmmoType() end

---Server only.
---@return handle
function CTakeDamageInfo:GetAttacker() end

---Server only.
---@return number
function CTakeDamageInfo:GetDamage() end

---Server only.
---@return integer
function CTakeDamageInfo:GetDamageCustom() end

---Server only.
---@return Vector
function CTakeDamageInfo:GetDamageForce() end

---Server only.
---@return any
function CTakeDamageInfo:GetDamagePosition() end

---Server only.
---@return any
function CTakeDamageInfo:GetDamageType() end

---Server only.
---@return handle
function CTakeDamageInfo:GetInflictor() end

---Server only.
---@return number
function CTakeDamageInfo:GetOriginalDamage() end

---Server only.
---@return any
function CTakeDamageInfo:GetReportedPosition() end

---Server only.
---@return number
function CTakeDamageInfo:GetTotalledDamage() end

---Server only.
---@param iDamageType integer
---@return boolean
function CTakeDamageInfo:HasDamageType(iDamageType) end

---Server only.
function CTakeDamageInfo:IsNull(...) end

---Server only.
---@param flScaleAmount number
function CTakeDamageInfo:ScaleDamage(flScaleAmount) end

---Server only.
---@param iAmmoType integer
function CTakeDamageInfo:SetAmmoType(iAmmoType) end

---Server only.
---@param hAttacker handle
function CTakeDamageInfo:SetAttacker(hAttacker) end

---Server only.
---@param flDamage number
function CTakeDamageInfo:SetDamage(flDamage) end

---Server only.
---@param iDamageCustom integer
function CTakeDamageInfo:SetDamageCustom(iDamageCustom) end

---Server only.
---@param damageForce Vector
function CTakeDamageInfo:SetDamageForce(damageForce) end

---Server only.
---@param damagePosition any
function CTakeDamageInfo:SetDamagePosition(damagePosition) end

---Server only.
---@param iDamageType integer
function CTakeDamageInfo:SetDamageType(iDamageType) end

---Server only.
---@param flOriginalDamage number
function CTakeDamageInfo:SetOriginalDamage(flOriginalDamage) end

---Server only.
---@param reportedPosition any
function CTakeDamageInfo:SetReportedPosition(reportedPosition) end
