---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class GridNav
GridNav = {}

---Determine if it is possible to reach the specified end point from the specified start point. bool (vStart, vEnd)
---Server only.
---@param unknown_1 any
---@param unknown_2 any
---@return boolean
function GridNav:CanFindPath(unknown_1, unknown_2) end

---Destroy all trees in the area(vPosition, flRadius, bFullCollision
---Server only.
---@param unknown_1 any
---@param float_2 number
---@param bool_3 boolean
function GridNav:DestroyTreesAroundPoint(unknown_1, float_2, bool_3) end

---Find a path between the two points an return the length of the path. If there is not a path between the points the returned value will be -1. float (vStart, vEnd )
---Server only.
---@param unknown_1 any
---@param unknown_2 any
---@return number
function GridNav:FindPathLength(unknown_1, unknown_2) end

---Returns a table full of tree HSCRIPTS (vPosition, flRadius, bFullCollision).
---Server only.
---@param unknown_1 any
---@param float_2 number
---@param bool_3 boolean
---@return table
function GridNav:GetAllTreesAroundPoint(unknown_1, float_2, bool_3) end

---Get the X position of the center of a given X index
---Server only.
---@param int_1 integer
---@return number
function GridNav:GridPosToWorldCenterX(int_1) end

---Get the Y position of the center of a given Y index
---Server only.
---@param int_1 integer
---@return number
function GridNav:GridPosToWorldCenterY(int_1) end

---Checks whether the given position is blocked
---Server only.
---@param unknown_1 any
---@return boolean
function GridNav:IsBlocked(unknown_1) end

---(position, radius, checkFullTreeRadius?) Checks whether there are any trees overlapping the given point
---Server only.
---@param unknown_1 any
---@param float_2 number
---@param bool_3 boolean
---@return boolean
function GridNav:IsNearbyTree(unknown_1, float_2, bool_3) end

---Server only.
function GridNav:IsNull(...) end

---Checks whether the given position is traversable
---Server only.
---@param unknown_1 any
---@return boolean
function GridNav:IsTraversable(unknown_1) end

---Causes all trees in the map to regrow
---Server only.
function GridNav:RegrowAllTrees() end

---Get the X index of a given world X position
---Server only.
---@param float_1 number
---@return integer
function GridNav:WorldToGridPosX(float_1) end

---Get the Y index of a given world Y position
---Server only.
---@param float_1 number
---@return integer
function GridNav:WorldToGridPosY(float_1) end
