---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class ProjectileManager
ProjectileManager = {}

---Update speed
---Server only.
---@param handle_1 handle
---@param int_2 integer
function ProjectileManager:ChangeTrackingProjectileSpeed(handle_1, int_2) end

---Creates a linear projectile and returns the projectile ID
---Server only.
---@param handle_1 handle
---@return integer
function ProjectileManager:CreateLinearProjectile(handle_1) end

---Creates a tracking projectile
---Server only.
---@param handle_1 handle
---@return integer
function ProjectileManager:CreateTrackingProjectile(handle_1) end

---Destroys the linear projectile matching the argument ID
---Server only.
---@param int_1 integer
function ProjectileManager:DestroyLinearProjectile(int_1) end

---Destroy a tracking projectile early
---Server only.
---@param int_1 integer
function ProjectileManager:DestroyTrackingProjectile(int_1) end

---Returns current location of projectile
---Server only.
---@param int_1 integer
---@return any
function ProjectileManager:GetLinearProjectileLocation(int_1) end

---Returns current radius of projectile
---Server only.
---@param int_1 integer
---@return number
function ProjectileManager:GetLinearProjectileRadius(int_1) end

---Returns a vector representing the current velocity of the projectile.
---Server only.
---@param int_1 integer
---@return Vector
function ProjectileManager:GetLinearProjectileVelocity(int_1) end

---Returns current location of projectile
---Server only.
---@param int_1 integer
---@return any
function ProjectileManager:GetTrackingProjectileLocation(int_1) end

---Server only.
function ProjectileManager:IsNull(...) end

---Is this a valid projectile?
---Server only.
---@param int_1 integer
---@return boolean
function ProjectileManager:IsValidProjectile(int_1) end

---Makes the specified unit dodge projectiles
---Server only.
---@param handle_1 handle
function ProjectileManager:ProjectileDodge(handle_1) end

---Update velocity
---Server only.
---@param int_1 integer
---@param Vector_2 Vector
---@param float_3 number
function ProjectileManager:UpdateLinearProjectileDirection(int_1, Vector_2, float_3) end
