---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Server only.
---@class SteamInfo
SteamInfo = {}

---Server only.
function SteamInfo:IsNull(...) end

---Is the script connected to the public Steam universe
---Server only.
---@return boolean
function SteamInfo:IsPublicUniverse() end
