---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Get the local player ID.
---Client only.
---@return integer
function GetLocalPlayerID() end

---Get the local player team.
---Client only.
---@param int_1 integer
---@return integer
function GetLocalPlayerTeam(int_1) end

---Returns true if whatever alt is remapped to is pressed
---Client only.
---@return boolean
function IsDotaAltPressed() end

---Returns true if whatever ctrl is remapped to is pressed
---Client only.
---@return boolean
function IsDotaCtrlPressed() end
