---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_BaseEntity : CEntityInstance
C_BaseEntity = {}

---Client only.
---@return any
function C_BaseEntity:GetAbsOrigin() end

---Client only.
---@return integer
function C_BaseEntity:GetHealth() end

---Client only.
---@return integer
function C_BaseEntity:GetMaxHealth() end

---Client only.
---@return integer
function C_BaseEntity:GetTeamNumber() end

---Defined in scripts/vscripts/utils/vscriptinit.lua:708.
---Client only.
function C_BaseEntity:IsInstance(classOrClassName) end

---Client only.
function C_BaseEntity:IsNull(...) end

---Set a think function on this entity.
---Client only.
---@param pszContextName string
---@param hThinkFunc handle
---@param flInterval number
function C_BaseEntity:SetContextThink(pszContextName, hThinkFunc, flInterval) end

---Defined in scripts/vscripts/utils/vscriptinit.lua:654.
---Client only.
function C_BaseEntity:SetThink(fnname, ...) end

---Defined in scripts/vscripts/utils/vscriptinit.lua:704.
---Client only.
function C_BaseEntity:StopThink(contextName) end
