---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_BaseModelEntity : C_BaseEntity
C_BaseModelEntity = {}

---GetRenderAlpha(): Get the alpha modulation of this entity.
---Client only.
---@return integer
function C_BaseModelEntity:GetRenderAlpha() end

---Client only.
function C_BaseModelEntity:IsNull(...) end
