---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_BaseCombatCharacter : C_BaseAnimatingOverlay
C_BaseCombatCharacter = {}

---Client only.
function C_BaseCombatCharacter:IsNull(...) end
