---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_BaseAnimatingOverlay : CBaseAnimatingActivity
C_BaseAnimatingOverlay = {}

---Client only.
function C_BaseAnimatingOverlay:IsNull(...) end
