---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_DOTA_BaseNPC : C_BaseEntity
C_DOTA_BaseNPC = {}

---Retrieve an ability by name from the unit.
---Client only.
---@param pAbilityName string
---@return handle
function C_DOTA_BaseNPC:FindAbilityByName(pAbilityName) end

---Client only.
---@return integer
function C_DOTA_BaseNPC:GetAbilityCount() end

---Client only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function C_DOTA_BaseNPC:GetAttackSpeed(bIgnoreTempAttackSpeed) end

---Client only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function C_DOTA_BaseNPC:GetAttacksPerSecond(bIgnoreTempAttackSpeed) end

---Client only.
---@param bIgnoreModifiers boolean
---@return number
function C_DOTA_BaseNPC:GetBaseAttackTime(bIgnoreModifiers) end

---Returns base magical armor value.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetBaseMagicalResistanceValue() end

---Client only.
---@return number
function C_DOTA_BaseNPC:GetBaseMoveSpeed() end

---Client only.
---@return number
function C_DOTA_BaseNPC:GetCastRangeBonus() end

---Returns the size of the collision padding around the hull.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetCollisionPadding() end

---Client only.
---@return number
function C_DOTA_BaseNPC:GetCooldownReduction() end

---Gets the current vision range.
---Client only.
---@return integer
function C_DOTA_BaseNPC:GetCurrentVisionRange() end

---Client only.
---@return integer
function C_DOTA_BaseNPC:GetDamageMax() end

---Client only.
---@return integer
function C_DOTA_BaseNPC:GetDamageMin() end

---Returns the vision range after modifiers.
---Client only.
---@return integer
function C_DOTA_BaseNPC:GetDayTimeVisionRange() end

---Client only.
---@return number
function C_DOTA_BaseNPC:GetHasteFactor() end

---Get the current health percent of the unit.
---Client only.
---@return integer
function C_DOTA_BaseNPC:GetHealthPercent() end

---Get the collision hull radius of this NPC.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetHullRadius() end

---Returns speed after all modifiers.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetIdealSpeed() end

---Returns speed after all modifiers, but excluding those that reduce speed.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetIdealSpeedNoSlows() end

---Client only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function C_DOTA_BaseNPC:GetIncreasedAttackSpeed(bIgnoreTempAttackSpeed) end

---Returns the level of this unit.
---Client only.
---@return integer
function C_DOTA_BaseNPC:GetLevel() end

---Get the mana on this unit.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetMana() end

---Client only.
---@return number
function C_DOTA_BaseNPC:GetManaRegen() end

---Get the maximum mana of this unit.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetMaxMana() end

---Client only.
---@return number
function C_DOTA_BaseNPC:GetModelRadius() end

---Gets the stack count of a given modifier.
---Client only.
---@param pszScriptName string
---@param hCaster handle
---@return integer
function C_DOTA_BaseNPC:GetModifierStackCount(pszScriptName, hCaster) end

---Client only.
---@param flBaseSpeed number
---@param bReturnUnslowed boolean
---@return number
function C_DOTA_BaseNPC:GetMoveSpeedModifier(flBaseSpeed, bReturnUnslowed) end

---Returns the vision range after modifiers.
---Client only.
---@return integer
function C_DOTA_BaseNPC:GetNightTimeVisionRange() end

---Client only.
---@return integer
function C_DOTA_BaseNPC:GetOpposingTeamNumber() end

---Get the collision hull radius (including padding) of this NPC.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetPaddedCollisionRadius() end

---Returns base physical armor value.
---Client only.
---@return number
function C_DOTA_BaseNPC:GetPhysicalArmorBaseValue() end

---Returns current physical armor value.
---Client only.
---@param bIgnoreBase boolean
---@return number
function C_DOTA_BaseNPC:GetPhysicalArmorValue(bIgnoreBase) end

---Get the owner player ID for this unit.
---Client only.
---@return integer
function C_DOTA_BaseNPC:GetPlayerOwnerID() end

---Client only.
---@param bIgnoreTempAttackSpeed boolean
---@return number
function C_DOTA_BaseNPC:GetSecondsPerAttack(bIgnoreTempAttackSpeed) end

---Get how much gold has been spent on ability upgrades.
---Client only.
---@return integer
function C_DOTA_BaseNPC:GetTotalPurchasedUpgradeGoldCost() end

---Client only.
---@return string
function C_DOTA_BaseNPC:GetUnitLabel() end

---Get the localization token for this unit's name.
---Client only.
---@return string
function C_DOTA_BaseNPC:GetUnitLocToken() end

---Get the name of this unit.
---Client only.
---@return string
function C_DOTA_BaseNPC:GetUnitName() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:HasAttackCapability() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:HasFlyMovementCapability() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:HasFlyingVision() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:HasGroundMovementCapability() end

---See whether this unit has an item by name.
---Client only.
---@param pItemName string
---@return boolean
function C_DOTA_BaseNPC:HasItemInInventory(pItemName) end

---Sees if this unit has a given modifier.
---Client only.
---@param pszScriptName string
---@return boolean
function C_DOTA_BaseNPC:HasModifier(pszScriptName) end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:HasMovementCapability() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:HasScepter() end

---Is this unit an Ancient?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsAncient() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsAttackImmune() end

---Is this unit a Barracks?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsBarracks() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsBlind() end

---Is this unit a boss?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsBoss() end

---Is this unit a building?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsBuilding() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsCommandRestricted() end

---Is this unit a considered a hero for targeting purposes?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsConsideredHero() end

---Is this unit controlled by any non-bot player?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsControllableByAnyPlayer() end

---Is this unit a courier?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsCourier() end

---Is this a Creature type NPC?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsCreature() end

---Is this unit a creep?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsCreep() end

---Is this a creep hero?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsCreepHero() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsDebuffImmune() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsDisarmed() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsDominated() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsEvadeDisabled() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsFeared() end

---Is this unit an Ancient?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsFort() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsFrozen() end

---Is this a hero or hero illusion?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsHero() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsHexed() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsIllusion() end

---Does this unit have an inventory.
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsInventoryEnabled() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsInvisible() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsInvulnerable() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsLowAttackPriority() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsMagicImmune() end

---Is this unit moving?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsMoving() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsMuted() end

---Is this a neutral?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsNeutralUnitType() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsNightmared() end

---Client only.
function C_DOTA_BaseNPC:IsNull(...) end

---Is this unit a ward-type unit?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsOther() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsOutOfGame() end

---Is this unit owned by any non-bot player?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsOwnedByAnyPlayer() end

---Is this a phantom unit?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsPhantom() end

---Is this unit a ranged attacker?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsRangedAttacker() end

---Is this a real hero?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsRealHero() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsRooted() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsSilenced() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsSpeciallyDeniable() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsSpeciallyUndeniable() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsStrongIllusion() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsStunned() end

---Is this unit summoned?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsSummoned() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsTaunted() end

---Is this a tower?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsTower() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsUnselectable() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:IsUntargetable() end

---Client only.
---@param pTargettingSource handle
---@return boolean
function C_DOTA_BaseNPC:IsUntargetableFrom(pTargettingSource) end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:NoHealthBar() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:NoTeamMoveTo() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:NoTeamSelect() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:NoUnitCollision() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:NotOnMinimap() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:NotOnMinimapForEnemies() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:PassivesDisabled() end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:ProvidesVision() end

---Gets this unit's attack range after all modifiers.
---Client only.
---@return number
function C_DOTA_BaseNPC:Script_GetAttackRange() end

---Returns current magical armor value.
---Client only.
---@param inflictor handle
---@return number
function C_DOTA_BaseNPC:Script_GetMagicalArmorValue(inflictor) end

---Client only.
---@return boolean
function C_DOTA_BaseNPC:Script_IsDeniable() end

---Can the unit respawn?
---Client only.
---@return boolean
function C_DOTA_BaseNPC:UnitCanRespawn() end
