---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_DOTABaseAbility : C_BaseEntity
C_DOTABaseAbility = {}

---Name of this ability.
---Client only.
---@return string
function C_DOTABaseAbility:GetAbilityName() end

---Client only.
---@return number
function C_DOTABaseAbility:GetBehavior() end

---Get ability behavior flags as an int for compatibility.
---Client only.
---@return integer
function C_DOTABaseAbility:GetBehaviorInt() end

---Client only.
---@return number
function C_DOTABaseAbility:GetCastPointModifier() end

---Get the owner of this ability.
---Client only.
---@return handle
function C_DOTABaseAbility:GetCaster() end

---The number of charges remaining on this ability.
---Client only.
---@return integer
function C_DOTABaseAbility:GetCurrentAbilityCharges() end

---Return the level of the ability
---Client only.
---@return integer
function C_DOTABaseAbility:GetLevel() end

---Gets a value from this ability's special value block for passed level.
---Client only.
---@param szName string
---@param nLevel integer
---@return table
function C_DOTABaseAbility:GetLevelSpecialValueFor(szName, nLevel) end

---Client only.
---@param szName string
---@param nLevel integer
---@return table
function C_DOTABaseAbility:GetLevelSpecialValueNoOverride(szName, nLevel) end

---Gets a value from this ability's special value block for its current level.
---Client only.
---@param szName string
---@return table
function C_DOTABaseAbility:GetSpecialValueFor(szName) end

---Whether or not this ability is toggled.
---Client only.
---@return boolean
function C_DOTABaseAbility:GetToggleState() end

---Whether or not this ability is an item.
---Client only.
---@return boolean
function C_DOTABaseAbility:IsItem() end

---Client only.
function C_DOTABaseAbility:IsNull(...) end
