---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_DOTA_Item : C_DOTABaseAbility
C_DOTA_Item = {}

---Client only.
---@return boolean
function C_DOTA_Item:CanOnlyPlayerHeroPickup() end

---Client only.
---@return integer
function C_DOTA_Item:GetCurrentCharges() end

---Client only.
---@return integer
function C_DOTA_Item:GetInitialCharges() end

---Client only.
---@return integer
function C_DOTA_Item:GetItemSlot() end

---Client only.
---@return integer
function C_DOTA_Item:GetSecondaryCharges() end

---Client only.
---@return integer
function C_DOTA_Item:GetShareability() end

---Client only.
---@return boolean
function C_DOTA_Item:IsAlertableItem() end

---Client only.
---@return boolean
function C_DOTA_Item:IsCastOnPickup() end

---Client only.
---@return boolean
function C_DOTA_Item:IsDisassemblable() end

---Client only.
---@return boolean
function C_DOTA_Item:IsDroppable() end

---Client only.
---@return boolean
function C_DOTA_Item:IsInBackpack() end

---Client only.
---@return boolean
function C_DOTA_Item:IsItem() end

---Client only.
---@return boolean
function C_DOTA_Item:IsKillable() end

---Client only.
---@return boolean
function C_DOTA_Item:IsMuted() end

---Client only.
function C_DOTA_Item:IsNull(...) end

---Client only.
---@return boolean
function C_DOTA_Item:IsPermanent() end

---Client only.
---@return boolean
function C_DOTA_Item:IsPurchasable() end

---Client only.
---@return boolean
function C_DOTA_Item:IsRecipe() end

---Client only.
---@return boolean
function C_DOTA_Item:IsRecipeGenerated() end

---Client only.
---@return boolean
function C_DOTA_Item:IsSellable() end

---Client only.
---@return boolean
function C_DOTA_Item:IsStackable() end

---Client only.
---@return boolean
function C_DOTA_Item:RequiresCharges() end
