---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_DOTA_Item_Lua : C_DOTA_Item
C_DOTA_Item_Lua = {}

---Determine whether an issued command with no target is valid.
---Client only.
---@return integer
function C_DOTA_Item_Lua:CastFilterResult() end

---(VectorWS vLocation) Determine whether an issued command on a location is valid.
---Client only.
---@param vLocation any
---@return integer
function C_DOTA_Item_Lua:CastFilterResultLocation(vLocation) end

---(HSCRIPT hTarget) Determine whether an issued command on a target is valid.
---Client only.
---@param hTarget handle
---@return integer
function C_DOTA_Item_Lua:CastFilterResultTarget(hTarget) end

---Controls the size of the AOE casting cursor.
---Client only.
---@return number
function C_DOTA_Item_Lua:GetAOERadius() end

---Allows code overriding of the item texture shown in the HUD.
---Client only.
---@return string
function C_DOTA_Item_Lua:GetAbilityTextureName() end

---Return cast behavior type of this ability.
---Client only.
---@return number
function C_DOTA_Item_Lua:GetBehavior() end

---Return cast range of this ability.
---Client only.
---@param vLocation any
---@param hTarget handle
---@return integer
function C_DOTA_Item_Lua:GetCastRange(vLocation, hTarget) end

---Return the channel start time of this ability.
---Client only.
---@return number
function C_DOTA_Item_Lua:GetChannelStartTime() end

---Return the channel time of this ability.
---Client only.
---@return number
function C_DOTA_Item_Lua:GetChannelTime() end

---Return health cost per second of channeling at the given level (-1 is current).
---Client only.
---@param iLevel integer
---@return integer
function C_DOTA_Item_Lua:GetChannelledHealthCostPerSecond(iLevel) end

---Return mana cost at the given level per second while channeling (-1 is current).
---Client only.
---@param iLevel integer
---@return integer
function C_DOTA_Item_Lua:GetChannelledManaCostPerSecond(iLevel) end

---Return cooldown of this ability.
---Client only.
---@param iLevel integer
---@return number
function C_DOTA_Item_Lua:GetCooldown(iLevel) end

---Return the error string of a failed command with no target.
---Client only.
---@return string
function C_DOTA_Item_Lua:GetCustomCastError() end

---(VectorWS vLocation) Return the error string of a failed command on a location.
---Client only.
---@param vLocation any
---@return string
function C_DOTA_Item_Lua:GetCustomCastErrorLocation(vLocation) end

---(HSCRIPT hTarget) Return the error string of a failed command on a target.
---Client only.
---@param hTarget handle
---@return string
function C_DOTA_Item_Lua:GetCustomCastErrorTarget(hTarget) end

---(DOTA_INVALID_ORDERS nReason) Return the error string of a failed order.
---Client only.
---@param nReason integer
---@return string
function C_DOTA_Item_Lua:GetCustomHudErrorMessage(nReason) end

---Return cast range of this ability, taking modifiers into account.
---Client only.
---@param vLocation any
---@param hTarget handle
---@return integer
function C_DOTA_Item_Lua:GetEffectiveCastRange(vLocation, hTarget) end

---Return gold cost at the given level (-1 is current).
---Client only.
---@param iLevel integer
---@return integer
function C_DOTA_Item_Lua:GetGoldCost(iLevel) end

---Return health cost at the given level (-1 is current).
---Client only.
---@param iLevel integer
---@return integer
function C_DOTA_Item_Lua:GetHealthCost(iLevel) end

---Return mana cost at the given level (-1 is current).
---Client only.
---@param iLevel integer
---@return integer
function C_DOTA_Item_Lua:GetManaCost(iLevel) end

---Returns whether this item is muted or not.
---Client only.
---@return boolean
function C_DOTA_Item_Lua:IsMuted() end

---Client only.
function C_DOTA_Item_Lua:IsNull(...) end
