---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_DOTA_Item_EmptyBottle : C_DOTA_Item
C_DOTA_Item_EmptyBottle = {}

---Client only.
function C_DOTA_Item_EmptyBottle:IsNull(...) end
