---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_DOTA_BaseNPC_Hero : C_DOTA_BaseNPC
C_DOTA_BaseNPC_Hero = {}

---Client only.
---@return number
function C_DOTA_BaseNPC_Hero:GetAgility() end

---Client only.
---@return integer
function C_DOTA_BaseNPC_Hero:GetHeroFacetID() end

---Client only.
---@param bSkipNoConsume boolean
---@return number
function C_DOTA_BaseNPC_Hero:GetIntellect(bSkipNoConsume) end

---Client only.
---@return number
function C_DOTA_BaseNPC_Hero:GetStrength() end

---Client only.
function C_DOTA_BaseNPC_Hero:IsNull(...) end
