---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_DOTAPlayerController : C_BaseEntity
C_DOTAPlayerController = {}

---Client only.
---@return handle
function C_DOTAPlayerController:GetActiveAbility() end

---Client only.
---@return any
function C_DOTAPlayerController:GetClickBehaviors() end

---Client only.
---@return handle
function C_DOTAPlayerController:GetQueryUnit() end

---Client only.
function C_DOTAPlayerController:IsNull(...) end

---Client only.
---@return boolean
function C_DOTAPlayerController:ShouldDisplayInWorldUIElements() end
