---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_PointWorldText : C_BaseModelEntity
C_PointWorldText = {}

---Client only.
function C_PointWorldText:IsNull(...) end

---Set the message on this entity.
---Client only.
---@param pMessage string
function C_PointWorldText:SetMessage(pMessage) end
