---@meta
-- Generated by tools/dota-api/generate.mjs from the game API dumps. Do not edit.

---Client only.
---@class C_PointEntity : C_BaseEntity
C_PointEntity = {}

---Client only.
function C_PointEntity:IsNull(...) end
